# Table of Content

- [Table of Content](#table-of-content)
- [0-General](#0-general)

# General
[Back to Table of Content](#table-of-content)
# Cold Water Exposure and Mental Health in Adults: A Systematic Review and Meta-Analysis

## Introduction
[Back to Table of Content](#table-of-content)

Mental disorders such as depression and anxiety are among the leading causes of disability worldwide, causing substantial impairments in quality of life, social functioning, and physical health. Although pharmacological and psychotherapeutic treatments are effective, they face important limitations, adverse effects, limited accessibility, and long waiting times remain persistent barriers. Consequently, there is growing interest in low-threshold, safe, and biologically plausible interventions that can complement existing treatments and broaden the therapeutic landscape.

Cold-water exposure (CWE), including practices such as ice bathing, winter swimming, and cold showers, has gained increasing public and scientific attention as a potential approach to support mental health and well-being. Historically rooted in hydrotherapy, CWE is now being examined for its psychophysiological effects on stress regulation, mood, and resilience. Preliminary evidence suggests that repeated exposure to cold water may reduce depressive and anxiety symptoms, lower perceived stress, and enhance general well-being.

Mechanistically, CWE is conceptualized as an acute stressor that triggers adaptive responses in autonomic and neuroendocrine systems. With repeated exposure, these systems may recalibrate toward improved stress tolerance and emotional regulation, consistent with the principle of cross-stressor adaptation. Additional hypotheses include transient neurotransmitter changes (e.g., dopamine, serotonin) and behavioral mechanisms such as increased self-efficacy and mastery, which parallel elements of behavioral activation in depression.

However, the available evidence remains fragmented. Studies differ widely in design, population, exposure protocols, and outcome measures, and few include clinical populations or long-term follow-up. This systematic review and meta-analysis therefore synthesizes the full range of available studies to clarify the effects of CWE on mental health outcomes in adults, integrating psychological, physiological, and safety data to provide a comprehensive and clinically meaningful synthesis.

## Objective
[Back to Table of Content](#table-of-content)

1. **Primary Objective:**  
   To evaluate the effects of cold-water exposure (CWE) on key mental health outcomes in adult populations, specifically: 
   - Reducing depressive symptoms, anxiety, and perceived stress 
   - Improving general mental well-being as assessed by validated psychometric instruments 

2. **Secondary Objectives:**  
   - Examine effects of CWE on broader psychological and physiological variables associated with mental health, including sleep quality, thermoregulatory responses (core and skin temperature), metabolic outcomes, and neurobiological markers (cortisol, norepinephrine, inflammatory cytokines such as IL-6, TNF-α, and CRP). 
   - Compare the effects of CWE between healthy individuals and clinical populations (somatic or psychiatric).
   - Identify whether the effects of CWE vary by:
     - Type of exposure: full-body versus chest-level
     - Frequency and duration: single versus repeated sessions
     - Water temperature: <5°C, 5–11°C, 12–18°C, 19–24°C
     - Modality: active (e.g., swimming) versus passive (e.g., bathing, showering)
     - Sex and body composition/BMI
   - Assess dose–response relationships, determining the minimum effective duration or frequency of CWE required for psychological benefits.
   - Evaluate the sustainability of effects four weeks or more after the final intervention session, and identify adherence barriers and motivators for continued practice.
   - Summarize adverse events, safety concerns, and contraindications, as well as practical barriers to real-world implementation.

## Hypotheses
#### Primary Hypotheses
- **H1:** CWE significantly improves mental health outcomes in adults, specifically by reducing depressive symptoms, anxiety, and perceived stress, and by enhancing general mental well-being compared to no intervention or passive control.

#### Secondary Hypotheses
- **H2a:** CWE improves sleep quality and modulates physiological systems relevant to mental health, including reduced core and skin temperature, decreased cortisol concentrations, increased norepinephrine levels, and reduced pro-inflammatory cytokines (e.g., IL-6, TNF-α, CRP).  
- **H2b:** The beneficial effects of CWE are stronger in clinical populations (e.g., individuals with depression, anxiety, or somatic illness) compared to healthy participants.
- **H2c:** The effects of CWE vary by:
  - Type of exposure, with full-body immersion yielding stronger effects than partial immersion.
  - Frequency and duration, with repeated exposures producing greater effects than single sessions.
  - Water temperature, with colder exposures (<12°C) producing stronger effects than moderate ones.
  - Modality, with active exposure (swimming) differing in effect pattern from passive exposure (bathing, showering).
  - Sex and body composition/BMI, reflecting thermoregulatory and metabolic differences.
- **H2d:** CWE shows a dose–response relationship, with longer and/or more frequent exposures leading to greater improvements in mental health.
- **H2e:** The psychological benefits of CWE persist for at least four weeks after the intervention.
- **H2f:** Adherence to CWE protocols declines over time, particularly at very low temperatures (<5°C), due to discomfort or safety concerns.
- **H2g:** CWE may entail adverse effects in vulnerable populations (e.g., cardiovascular disease, PTSD), and practical barriers such as discomfort, accessibility, and safety concerns may limit its broad implementation.

## Acknowledgements
[Back to Table of Content](#table-of-content)

This review is conducted within the framework of the **Charité Competence Center for Traditional and Integrative Medicine (CCCTIM)**. We acknowledge the contributions of all co-authors, student assistants, and reviewers involved in screening and extraction. Statistical analysis and review methodology are overseen by **Dr. Steven Ngandeu Schepanski**.

## Questionnaire Scale Overview
[Back to Table of Content](#table-of-content)

This notebook provides a harmonized overview of all psychological questionnaires included in the review and assigns each instrument to a clearly defined construct domain for meta-analysis.

The following domain structure is used:
- Depression: CES-D, PHQ-9, BDI-II, DEPS
- Anxiety: GAD-7, BSI Anxiety subscale, PSWQ
- Perceived Stress: PSS
- Mood / Affect: PANAS (Positive Affect, Negative Affect), POMS (Tension, Fatigue, Vigor, Depression), MDES (Positive, Negative), OIRE Mood
- Wellbeing: WEMWBS, SHS
- Sleep: PSQI, VAS Sleep
- Global Psychopathology / Trauma-related Symptoms: TSC-40, CCEI

Multi-subscale instruments (e.g., PANAS, POMS, MDES, OIRE) are not aggregated; each subscale is treated as an independent outcome to maintain conceptual clarity and prevent mixing distinct affective or cognitive constructs. This harmonized domain structure forms the foundation for all subsequent effect size calculation, data cleaning, and meta-analytic models.

# Packages
[Back to Table of Content](#table-of-content)

In [1]:
# Define required packages
packages <- c("tidyverse", "readxl", "janitor", "writexl", "lubridate", "stringr", 
              "metafor", "robumeta", "clubSandwich", "grid",
              "MASS", "data.table", "gridExtra", "naniar", "haven",
              "broom", "rlang", "visdat", "estmeansd", "meta")

# Function to install and load packages silently
install_and_load <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg, quiet = TRUE)
  suppressPackageStartupMessages(
    library(pkg, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
  )
}

# Apply function to all packages
invisible(lapply(packages, install_and_load))

Warning message:
“package ‘ggplot2’ was built under R version 4.3.3”
Warning message:
“package ‘tibble’ was built under R version 4.3.3”
Warning message:
“package ‘purrr’ was built under R version 4.3.3”
Warning message:
“package ‘lubridate’ was built under R version 4.3.3”
Warning message:
“package ‘readxl’ was built under R version 4.3.3”
Warning message:
“package ‘janitor’ was built under R version 4.3.3”
Warning message:
“package ‘writexl’ was built under R version 4.3.3”
Warning message:
“package ‘metafor’ was built under R version 4.3.3”
Warning message:
“package ‘metadat’ was built under R version 4.3.3”
Warning message:
“package ‘robumeta’ was built under R version 4.3.3”
Registered S3 method overwritten by 'clubSandwich':
  method    from
  bread.mlm sandwich

Warning message:
“package ‘clubSandwich’ was built under R version 4.3.3”
Warning message:
“package ‘data.table’ was built under R version 4.3.3”
Warning message:
“package ‘haven’ was built under R version 4.3.3”
Warning message:
“package ‘broom’ was built under R version 4.3.3”
Warning message:
“package ‘rlang’ was built under R version 4.3.3”
Warning message:
“package ‘estmeansd’ was built under R version 4.3.3”
Warning message:
“package ‘meta’ was built under R version 4.3.3”

In [2]:
# Define the working directory
path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/"
file <- file.path(path, "processed", "CWE_metadata_mental_nonmental.xlsx")

In [3]:
# Define graph output directory and create it if needed
graph_path <- file.path(path, "graphs")
if (!dir.exists(graph_path)) {
  dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
}

In [4]:
# Helper to read + clean a sheet
read_clean <- function(path, sheet_name) {
  readxl::read_excel(path, sheet = sheet_name, guess_max = 10000) |>
    janitor::clean_names()
}

In [5]:
# Read all three sheets
metadata  <- read_clean(file, "metadata")
mental    <- read_clean(file, "mental")
nonmental <- read_clean(file, "nonmental")

# **Objective 1: Mental Health Outcomes**
[Back to Table of Content](#table-of-content)

#### To evaluate the effects of cold-water exposure (CWE) on key mental health outcomes: depressive symptoms, anxiety, perceived stress, general well-being.

In [6]:
# Quick overview: structure of the mental sheet
glimpse(mental)

Rows: 199
Columns: 26
$ study_id                   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ instrument                 <chr> "CES-D", "CES-D", "CES-D", "CES-D", "CES-D"…
$ instrument_domain          <chr> "Depression", "Depression", "Depression", "…
$ subscale                   <chr> "na", "na", "na", "na", "na", "na", "na", "…
$ timepoint_label            <chr> "Pre", "Pre", "Post", "Post", "Follow-Up", …
$ timepoint_days             <chr> "0", "0", "21", "21", "105", "105", "0", "0…
$ group                      <chr> "Intervention", "Control", "Intervention", …
$ analysis_set               <chr> "PP", "PP", "PP", "PP", "PP", "PP", "PP", "…
$ n                          <dbl> 42, 41, 37, 41, 23, 23, 43, 41, 37, 41, 23,…
$ mean                       <dbl> 22.70, 24.20, 18.13, 17.60, 15.83, 16.09, 8…
$ sd                         <dbl> 7.72, 9.72, 10.17, 10.76, 8.74, 11.66, 4.44…
$ se                         <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ci_l                       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ci_u                       <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ median                     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ iqr_l                      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ iqr_u                      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ change_mean                <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ change_sd                  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ study_id_factor            <chr> "1", "1", "1", "1", "1", "1", "1", "1", "1"…
$ timepoint_label_raw        <chr> "Pre", "Pre", "Post", "Post", "Follow-Up", …
$ timepoint_days_raw         <chr> "0", "0", "21", "21", "105", "105", "0", "0…
$ group_raw                  <chr> "Intervention", "Control", "Intervention", …
$ timepoint_label_harmonised <chr> "Pre", "Pre", "Post", "Post", "Follow-Up", …
$ timepoint_days_num         <dbl> 0, 0, 21, 21, 105, 105, 0, 0, 21, 21, 105, …
$ group_harmonised           <chr> "Intervention", "Control", "Intervention", …

In [7]:
# Helper: standardize strings for matching (instrument + subscale)
std_key <- function(x) {
  x %>%
    replace_na("") %>%
    str_squish() %>%           # collapse whitespace + trim
    str_replace_all("\r\n|\n|\r", " ") %>%  # normalize line breaks
    str_squish() %>%
    str_to_lower()
}

mental2 <- mental %>%
  mutate(
    instrument_key = std_key(instrument),
    subscale_key   = std_key(subscale)
  )

In [8]:
# Define your mapping table (instrument + subscale -> instrument_domain_new)
domain_map <- tibble::tribble(
  ~instrument, ~subscale, ~instrument_domain_new,
  "CES-D", "na", "Depression",
  "GAD-7", "na", "Anxiety",
  "PSS", "na", "Perceived Stress",
  "Stress rumination", "na", "Cognitive Stress",
  "MDES", "positive", "Mood_Affect",
  "MDES", "negative", "Mood_Affect",
  "SF-36", "physical component score (PCS)", "Physical Quality of Life",
  "SF-36", "mental component score (MCS)",   "Mental Quality of Life",
  "BSI", "anxiety", "Anxiety",
  "PANAS", "positive affect", "Mood_Affect",
  "PANAS", "negative affect", "Mood_Affect",
  "PHQ-9", "na", "Depression",
  "WEMWBS", "nr", "Wellbeing",
  "DEPS", "nr", "Depression",
  "VAS", "nr", "Sleep",
  "TAS-20", "total", "Alexithymia",
  "CCEI", "free-floating anxiety", "Psychopathology",
  "CCEI", "hysteria", "Psychopathology",
  "CCEI", "obsessionality", "Psychopathology",
  "POMS", "tension", "Mood_Affect",
  "POMS", "fatigue", "Mood_Affect",
  "POMS", "vigor", "Mood_Affect",
  "POMS", "depression", "Mood_Affect",
  "OIRE", "mood", "Mood_Affect",
  "OIRE", "memory", "Cognitive Functioning",
  "PSWQ", "nr", "Anxiety",
  "SHS", "nr", "Wellbeing",
  "PSQI", "nr", "Sleep",
  "TSC-40", "nr", "Psychopathology",
  "BDI-II", "nr", "Depression"
) %>%
  mutate(
    instrument_key = std_key(instrument),
    subscale_key   = std_key(subscale)
  ) %>%
  distinct(instrument_key, subscale_key, .keep_all = TRUE)

# mapping must be unique per key
stopifnot(nrow(domain_map) == nrow(distinct(domain_map, instrument_key, subscale_key)))

In [9]:
# Apply mapping: replace instrument_domain when a match exists
mental <- mental2 %>%
  dplyr::left_join(
    domain_map %>% dplyr::select(instrument_key, subscale_key, instrument_domain_new),
    by = c("instrument_key", "subscale_key")
  ) %>%
  dplyr::mutate(
    instrument_domain = dplyr::coalesce(instrument_domain_new, instrument_domain)
  ) %>%
  dplyr::select(-instrument_key, -subscale_key, -instrument_domain_new)


# Quick check
mental %>%
  count(instrument, subscale, instrument_domain, sort = TRUE)

   instrument        subscale
1  PSS               na
2  BSI               anxiety
3  CES-D             na
4  SF-36             mental\r\r\ncomponent\r\r\nscore (MCS)
5  SF-36             physical\r\r\ncomponent\r\r\nscore (PCS)
6  GAD-7             na
7  PANAS             negative affect
8  PANAS             positive affect
9  MDES              negative
10 MDES              positive
11 WEMWBS            nr
12 GAD-7             nr
13 PSQI              nr
14 PSWQ              nr
15 SHS               nr
16 TAS-20            Total
17 BDI-II            nr
18 DEPS              nr
19 OIRE              memory
20 OIRE              mood
21 PHQ-9             na
22 POMS              Depression
23 POMS              Fatigue
24 POMS              Tension
25 POMS              Vigor
26 TSC-40            nr
27 VAS               nr
28 PHQ-9             nr
29 PSS               nr
30 Stress rumination na
31 CCEI              Free-floating anxiety
32 CCEI              Hysteria
33 CCEI              Obsessionality
   instrument_domain        n
1  Perceived Stress         16
2  Anxiety                  12
3  Depression               12
4  Mental Quality of Life   12
5  Physical Quality of Life 12
6  Anxiety                  10
7  Mood_Affect               9
8  Mood_Affect               9
9  Mood_Affect               8
10 Mood_Affect               8
11 Wellbeing                 8
12 Anxiety                   6
13 Sleep                     6
14 Anxiety                   6
15 Wellbeing                 6
16 Alexithymia               6
17 Depression                4
18 Depression                4
19 Cognitive Functioning     4
20 Mood_Affect               4
21 Depression                4
22 Mood_Affect               4
23 Mood_Affect               4
24 Mood_Affect               4
25 Mood_Affect               4
26 Psychopathology           4
27 Sleep                     4
28 Depression                2
29 Perceived Stress          2
30 Cognitive Stress          2
31 Psychopathology           1
32 Psychopathology           1
33 Psychopathology           1

In [10]:
## ============================================================
## FIX HARMONISATION FOR STUDY 6 (DEPS)
## Day 1 = Pre
## Day 5 = Post
## ============================================================

mental <- mental %>%
  mutate(
    timepoint_label_harmonised = case_when(
      study_id == 6 & str_detect(timepoint_label_raw, "Day 1") ~ "Pre",
      study_id == 6 & str_detect(timepoint_label_raw, "Day 5") ~ "Post",
      TRUE ~ timepoint_label_harmonised
    )
  )

In [11]:
# How many unique studies per instrument_domain?
domain_counts <- mental |>
  # focus on rows where a mental health domain is defined
  filter(!is.na(instrument_domain)) |>
  # make sure each study is counted only once per domain
  distinct(study_id, instrument_domain) |>
  # count number of studies per domain
  count(instrument_domain, name = "k_studies") |>
  filter(k_studies >= 2) |>
  arrange(desc(k_studies))

domain_counts

  instrument_domain k_studies
1 Depression        6
2 Mood_Affect       6
3 Anxiety           4
4 Perceived Stress  4
5 Psychopathology   2
6 Sleep             2
7 Wellbeing         2

**_Exclusion of the 'Psychopathology' Domain:_** _Our domain screening identified only two studies contributing data to the Psychopathology domain. However, one of these studies does not provide extractable quantitative data for the relevant outcomes. As a result, the minimum threshold of at least two studies with usable data per outcome is not met. Consequently, Psychopathology cannot be subjected to quantitative synthesis and is not considered further in the subsequent meta-analyses._

## **Depression**
[Back to Table of Content](#table-of-content)

In [12]:
# Filter all rows where instrument_domain is "Depression"
mental_dep <- mental |>
  filter(instrument_domain == "Depression")

# Quick check
mental_dep %>%
  dplyr::distinct(study_id, instrument, group_harmonised, timepoint_label_harmonised) %>%
  arrange(study_id, group_harmonised, timepoint_label_harmonised)

   study_id instrument group_harmonised timepoint_label_harmonised
1   1       CES-D      Control          Follow-Up
2   1       CES-D      Control          Post
3   1       CES-D      Control          Pre
4   1       CES-D      Intervention     Follow-Up
5   1       CES-D      Intervention     Post
6   1       CES-D      Intervention     Pre
7   4       PHQ-9      Control          Post
8   4       PHQ-9      Control          Pre
9   4       PHQ-9      Intervention     Post
10  4       PHQ-9      Intervention     Pre
11  5       PHQ-9      SingleGroup      Post
12  5       PHQ-9      SingleGroup      Pre
13  6       DEPS       Control          Post
14  6       DEPS       Control          Pre
15  6       DEPS       Intervention     Post
16  6       DEPS       Intervention     Pre
17 10       BDI-II     Control          Post
18 10       BDI-II     Control          Pre
19 10       BDI-II     Intervention     Post
20 10       BDI-II     Intervention     Pre
21 13       CES-D      Control          Follow-Up
22 13       CES-D      Control          Post
23 13       CES-D      Control          Pre
24 13       CES-D      Intervention     Follow-Up
25 13       CES-D      Intervention     Post
26 13       CES-D      Intervention     Pre

In [13]:
## ==========================================
## Reconstruct missing change SD from 95% CI
## ==========================================

mental_dep <- mental_dep %>%
  dplyr::mutate(
    # SE for change_mean from 95%-CI: CI = mean ± 1.96 * SE
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) & !is.na(ci_l) & !is.na(ci_u) ~
        (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    # derive change_sd if n is available
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [14]:
# Check which rows now have change_mean + change_sd
mental_dep %>%
  dplyr::select(study_id, instrument, timepoint_label_harmonised,
                group_harmonised, n, change_mean, change_sd) %>%
  arrange(study_id, group_harmonised, timepoint_label_harmonised)

   study_id instrument timepoint_label_harmonised group_harmonised n
1   1       CES-D      Follow-Up                  Control           23
2   1       CES-D      Post                       Control           41
3   1       CES-D      Pre                        Control           41
4   1       CES-D      Follow-Up                  Intervention      23
5   1       CES-D      Post                       Intervention      37
6   1       CES-D      Pre                        Intervention      42
7   4       PHQ-9      Post                       Control           13
8   4       PHQ-9      Pre                        Control           13
9   4       PHQ-9      Post                       Intervention      11
10  4       PHQ-9      Pre                        Intervention      11
11  5       PHQ-9      Post                       SingleGroup       29
12  5       PHQ-9      Pre                        SingleGroup       29
13  6       DEPS       Post                       Control          121
14  6       DEPS       Pre                        Control          121
15  6       DEPS       Post                       Intervention     121
16  6       DEPS       Pre                        Intervention     121
17 10       BDI-II     Post                       Control            7
18 10       BDI-II     Pre                        Control            5
19 10       BDI-II     Post                       Intervention       7
20 10       BDI-II     Pre                        Intervention       6
21 13       CES-D      Follow-Up                  Control           22
22 13       CES-D      Post                       Control           36
23 13       CES-D      Pre                        Control           44
24 13       CES-D      Follow-Up                  Intervention      20
25 13       CES-D      Post                       Intervention      34
26 13       CES-D      Pre                        Intervention      37
   change_mean change_sd
1      NA            NA
2      NA            NA
3      NA            NA
4      NA            NA
5      NA            NA
6      NA            NA
7   0.769      4.891409
8      NA            NA
9  -2.182      2.583075
10     NA            NA
11     NA            NA
12     NA            NA
13     NA            NA
14     NA            NA
15     NA            NA
16     NA            NA
17     NA            NA
18     NA            NA
19     NA            NA
20     NA            NA
21     NA            NA
22     NA            NA
23     NA            NA
24     NA            NA
25     NA            NA
26     NA            NA

In [15]:
## ====================================================================
## Pre–Post selection per study x group
## ONE row per study_id × group_harmonised × timepoint_label_harmonised
## Prefer ITT over PP if both exist
## Keep only Pre and Post timepoints for the primary analysis
## ====================================================================

# Preferred order of analysis sets
analysis_set_levels <- c("ITT", "PP")

dep_prepost <- mental_dep %>%
  # Focus on Pre vs Post exclude Follow-Up for primary analysis
  dplyr::filter(timepoint_label_harmonised %in% c("Pre", "Post")) %>%
  # Make analysis_set an ordered factor so ITT is preferred over PP
  dplyr::mutate(
    analysis_set = factor(analysis_set,
                          levels = analysis_set_levels)
  ) %>%
  # Order rows so preferred analysis_set comes first
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  # One row per study_id × group_harmonised × timepoint_label_harmonised
  dplyr::group_by(study_id, group_harmonised, timepoint_label_harmonised) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

# Quick check
dep_prepost %>%
  dplyr::count(study_id, group_harmonised, timepoint_label_harmonised)

   study_id group_harmonised timepoint_label_harmonised n
1   1       Control          Post                       1
2   1       Control          Pre                        1
3   1       Intervention     Post                       1
4   1       Intervention     Pre                        1
5   4       Control          Post                       1
6   4       Control          Pre                        1
7   4       Intervention     Post                       1
8   4       Intervention     Pre                        1
9   5       SingleGroup      Post                       1
10  5       SingleGroup      Pre                        1
11  6       Control          Post                       1
12  6       Control          Pre                        1
13  6       Intervention     Post                       1
14  6       Intervention     Pre                        1
15 10       Control          Post                       1
16 10       Control          Pre                        1
17 10       Intervention     Post                       1
18 10       Intervention     Pre                        1
19 13       Control          Post                       1
20 13       Control          Pre                        1
21 13       Intervention     Post                       1
22 13       Intervention     Pre                        1

In [16]:
## ============================================================
## Compute Change scores (Δ = Post − Pre) per group
## after pivoting Pre/Post to wide format
## Two sources of change information:
##  a) directly reported change_mean / change_sd (e.g. study 4)
##  b) derived from Pre/Post mean & SD with assumed r
## ============================================================

# Assumed pre–post correlation for deriving SD of change
r_change <- 0.5

dep_wide <- dep_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    # Prefer Post n; if missing, fallback to Pre n
    n_change = dplyr::coalesce(n_Post, n_Pre),

    # CHANGE MEAN
    #  If a change_mean is explicitly reported at Post, use it
    #  Otherwise compute Δ = mean_Post − mean_Pre
    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    # CHANGE SD
    #  If change_sd is explicitly reported at Post, use it
    #  Otherwise derive it from pre + post SD and assumed r
    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

# Quick check
dep_wide %>%
  dplyr::select(study_id, group_harmonised,
                n_change, change_mean_calc, change_sd_calc) %>%
  arrange(study_id, group_harmonised)

   study_id group_harmonised n_change change_mean_calc change_sd_calc
1   1       Control           41       -6.600          10.279533
2   1       Intervention      37       -4.570           9.193199
3   4       Control           13        0.769           4.891409
4   4       Intervention      11       -2.182           2.583075
5   5       SingleGroup       29       -3.890           3.640824
6   6       Control          121       -0.900           4.471018
7   6       Intervention     121       -1.000           4.450843
8  10       Control            7        4.600           6.068965
9  10       Intervention       7       -0.750           1.860405
10 13       Control           36       -9.150           7.055827
11 13       Intervention      34      -11.500           6.544639

In [17]:
## ================================================================
## Classify study designs for Depression
##  - "controlled": Intervention + Control groups
##  - "single_group": SingleGroup only
##  - "other": anything else will be excluded from primary analysis
## ================================================================

dep_wide <- dep_wide %>%
  dplyr::group_by(study_id) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

# Quick check
dep_wide %>%
  dplyr::distinct(study_id, design)

  study_id design
1  1       controlled
2  4       controlled
3  5       single_group
4  6       controlled
5 10       controlled
6 13       controlled

In [18]:
## ==============================================================
## Prepare group-level change data in a form suitable for effect
## size computation
## Keep only rows where change_mean & change_sd & n are available
## ==============================================================

dep_change_groups <- dep_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id, design, group_harmonised,
    change_mean_calc, change_sd_calc, n_change
  )

# Quick check
dep_change_groups %>%
  arrange(study_id, group_harmonised)

   study_id design       group_harmonised change_mean_calc change_sd_calc
1   1       controlled   Control           -6.600          10.279533
2   1       controlled   Intervention      -4.570           9.193199
3   4       controlled   Control            0.769           4.891409
4   4       controlled   Intervention      -2.182           2.583075
5   5       single_group SingleGroup       -3.890           3.640824
6   6       controlled   Control           -0.900           4.471018
7   6       controlled   Intervention      -1.000           4.450843
8  10       controlled   Control            4.600           6.068965
9  10       controlled   Intervention      -0.750           1.860405
10 13       controlled   Control           -9.150           7.055827
11 13       controlled   Intervention     -11.500           6.544639
   n_change
1   41
2   37
3   13
4   11
5   29
6  121
7  121
8    7
9    7
10  36
11  34

In [19]:
## ==================================================================
## EFFECT SIZES — CONTROLLED TRIALS
## ------------------------------------------------------------
## Change scores should be variables:
##   ΔI = change_mean_calc_Intervention
##   ΔC = change_mean_calc_Control
##
## Using metafor::escalc(measure = "SMD") on change scores:
##   - yi = Hedges g (SMD of change scores, Intervention vs Control)
##   - vi = sampling variance of g
## ------------------------------------------------------------
## Denominator: pooled SD of change scores across groups.
## Interpretation, e.g. for Depression scales where lower is better:
## Negative g = stronger reduction in depressive symptoms in the
## Intervention vs Control (i.e., beneficial CWE effect).
## ==================================================================

# Wide format: one row per study, with separate columns for Intervention, Control, SingleGroup
dep_change_wide_study <- dep_change_groups %>%
  tidyr::pivot_wider(
    id_cols   = c(study_id, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

# Controlled trials: Intervention vs Control
es_dep_controlled <- dep_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",  # standardised difference in change scores
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .
  ) %>%
  dplyr::mutate(
    outcome_domain = "Depression",
    design_type    = "controlled"
  )

# Quick check
es_dep_controlled %>%
  dplyr::select(study_id, yi, vi, outcome_domain, design_type)

  study_id yi          vi         outcome_domain design_type
1  1        0.20551007 0.05168800 Depression     controlled
2  4       -0.71041360 0.17834649 Depression     controlled
3  6       -0.02234665 0.01652996 Depression     controlled
4 10       -1.11557922 0.33016132 Depression     controlled
5 13       -0.34113094 0.05802076 Depression     controlled

In [20]:
## ============================================================
## Sample size summary for DEPRESSION meta-analysis
## N per study and total N across all included studies
## ============================================================

dep_N_by_study <- dep_change_wide_study %>%
  dplyr::mutate(
    # For controlled designs, total N is Intervention + Control
    # For single-group designs, total N is the single-group N
    N_study = dplyr::case_when(
      design == "controlled"    ~ n_change_Intervention + n_change_Control,
      design == "single_group"  ~ n_change_SingleGroup,
      TRUE                      ~ NA_real_
    )
  ) %>%
  dplyr::filter(!is.na(N_study))

# Number of studies contributing to the depression meta-analysis
k_dep <- nrow(dep_N_by_study)

# Total number of participants across all depression studies
N_dep_total <- sum(dep_N_by_study$N_study, na.rm = TRUE)

# Optional: N by design type (controlled vs single_group)
dep_N_by_design <- dep_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups  = "drop"
  )

# Print results in a readable form
cat("\nDepression meta-analysis:\n")
cat("  Number of studies (k): ", k_dep, "\n", sep = "")
cat("  Total participants (N): ", N_dep_total, "\n", sep = "")
cat("\nBreakdown by design:\n")
print(dep_N_by_design)

Depression meta-analysis:
  Number of studies (k): 6
  Total participants (N): 457

Breakdown by design:
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          5      428
2 single_group        1       29

In [21]:
## ============================================================
## EFFECT SIZES — SINGLE-GROUP PRE–POST (UNCONTROLLED)
## ------------------------------------------------------------
## For uncontrolled cohorts, standardised mean change should be
## used within the only group (SingleGroup):
##
##   d = Δ / SDΔ
##   g = J * d  (Hedges small-sample correction)
##   var(d) = 1/n + d^2/(2n)
##   var(g) = J^2 * var(d)
##
## Again, Δ and SDΔ are based on change scores.
## Interpretation: Negative g = reduction in depressive
## symptoms over time.
## ============================================================

es_dep_single <- dep_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    # Raw Cohen's d for one-sample standardised change
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    # Hedges J correction factor
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,  # Hedges g
    # Variance of d and g (approximation for one-sample SMD)
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Depression",
    design_type    = "single_group"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

# Quick check
es_dep_single

  study_id outcome_domain design_type  yi        vi
1 5        Depression     single_group -1.040567 0.05137574

In [22]:
## ============================================================
## COMBINE EFFECT SIZES ACROSS DESIGNS
## Controlled (ΔI vs ΔC) + Single-group (Δ vs 0)
## Hedges g on change scores
## ============================================================

es_dep_all <- dplyr::bind_rows(
  es_dep_controlled %>%
    dplyr::select(study_id, outcome_domain, design_type, yi, vi),
  es_dep_single
)

# Quick check
es_dep_all

  study_id outcome_domain design_type  yi          vi
1  1       Depression     controlled    0.20551007 0.05168800
2  4       Depression     controlled   -0.71041360 0.17834649
3  6       Depression     controlled   -0.02234665 0.01652996
4 10       Depression     controlled   -1.11557922 0.33016132
5 13       Depression     controlled   -0.34113094 0.05802076
6  5       Depression     single_group -1.04056710 0.05137574

In [23]:
## ============================================================
## DEPRESSION
## MAIN MODEL AND CONTROLLED-ONLY SENSITIVITY
## Multilevel random-effects framework as default
## Hartung-Knapp-like inference via t-distribution
## ============================================================

## --------------------------------------------
## Prepare analysis datasets
## --------------------------------------------

dep_main_dat <- es_dep_all %>%
  dplyr::arrange(study_id)

dep_controlled_dat <- es_dep_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id)

In [24]:
# Quick checks
dep_main_dat
dep_controlled_dat

cat("\nDepression main dataset\n")
cat("  k =", nrow(dep_main_dat), "\n")
cat("  studies =", paste(dep_main_dat$study_id, collapse = ", "), "\n")

cat("\nDepression controlled-only dataset\n")
cat("  k =", nrow(dep_controlled_dat), "\n")
cat("  studies =", paste(dep_controlled_dat$study_id, collapse = ", "), "\n")

  study_id outcome_domain design_type  yi          vi
1  1       Depression     controlled    0.20551007 0.05168800
2  4       Depression     controlled   -0.71041360 0.17834649
3  5       Depression     single_group -1.04056710 0.05137574
4  6       Depression     controlled   -0.02234665 0.01652996
5 10       Depression     controlled   -1.11557922 0.33016132
6 13       Depression     controlled   -0.34113094 0.05802076

  study_id outcome_domain design_type yi          vi
1  1       Depression     controlled   0.20551007 0.05168800
2  4       Depression     controlled  -0.71041360 0.17834649
3  6       Depression     controlled  -0.02234665 0.01652996
4 10       Depression     controlled  -1.11557922 0.33016132
5 13       Depression     controlled  -0.34113094 0.05802076

Depression main dataset
  k = 6
  studies = 1, 4, 5, 6, 10, 13

Depression controlled-only dataset
  k = 5
  studies = 1, 4, 6, 10, 13

In [25]:
## --------------------------------------------
## Main multilevel random-effects model
## --------------------------------------------
## One random intercept per study
## With one effect size per study this behaves similarly
## to a standard random-effects model, but keeps the
## multilevel framework as the default analysis strategy

res_dep_main_mv <- metafor::rma.mv(
  yi     = yi,
  V      = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test   = "t",
  dfs    = "contain",
  data   = dep_main_dat
)

print(res_dep_main_mv)
broom::tidy(res_dep_main_mv)

Multivariate Meta-Analysis Model (k = 6; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.2116  0.4600      6     no  study_id

Test for Heterogeneity:
Q(df = 5) = 22.9143, p-val = 0.0004

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.4189  0.2230  -1.8780   5  0.1192  -0.9922  0.1545

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.4188595 0.2230302 -1.87804  0.1191764

In [26]:
## --------------------------------------------
## Controlled-only sensitivity analysis
## --------------------------------------------
## This is the key design-aware sensitivity model
## It excludes the single-group pre-post study

res_dep_controlled_mv <- metafor::rma.mv(
  yi     = yi,
  V      = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test   = "t",
  dfs    = "contain",
  data   = dep_controlled_dat
)

print(res_dep_controlled_mv)
broom::tidy(res_dep_controlled_mv)

Multivariate Meta-Analysis Model (k = 5; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0730  0.2701      5     no  study_id

Test for Heterogeneity:
Q(df = 4) = 8.3858, p-val = 0.0784

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.2043  0.1733  -1.1785   4  0.3039  -0.6855  0.2770

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary -0.204256 0.1733225 -1.178473 0.3039256

In [27]:
## --------------------------------------------
## Compact comparison table
## --------------------------------------------

dep_model_compare <- dplyr::bind_rows(
  broom::tidy(res_dep_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  broom::tidy(res_dep_controlled_mv) %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

dep_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall -0.4188595 0.2230302 -1.878040 0.1191764
2 controlled_only  overall -0.2042560 0.1733225 -1.178473 0.3039256

In [28]:
## ============================================================
## Add readable study labels for leave-one-out tables
## ============================================================

study_labels <- tibble::tibble(
  study_id = c(1, 4, 5, 6, 10, 13),
  study_label = c(
    "Blades et al. 2024",
    "Slezakova et al. 2025",
    "Faid et al. 2022",
    "Hinkka et al. 2016",
    "Petraskova Touskova et al. 2022",
    "Epel et al. 2025"
  )
)

In [29]:
## ============================================================
## DEPRESSION
## Leave-one-out sensitivity analysis
## Based on the multilevel model framework
## ============================================================

## --------------------------------------------
## Leave-one-out for all designs combined
## --------------------------------------------

dep_loo_results <- purrr::map_dfr(
  unique(dep_main_dat$study_id),
  function(drop_study) {

    loo_dat <- dep_main_dat %>%
      dplyr::filter(study_id != drop_study)

    loo_model <- metafor::rma.mv(
      yi     = yi,
      V      = vi,
      random = ~ 1 | study_id,
      method = "REML",
      test   = "t",
      dfs    = "contain",
      data   = loo_dat
    )

    tibble::tibble(
      dropped_study = drop_study,
      k_remaining   = nrow(loo_dat),
      estimate      = as.numeric(loo_model$b),
      se            = loo_model$se,
      ci_lb         = loo_model$ci.lb,
      ci_ub         = loo_model$ci.ub,
      p_value       = loo_model$pval,
      tau2          = loo_model$sigma2,
      direction     = dplyr::case_when(
        estimate < 0 ~ "negative",
        estimate > 0 ~ "positive",
        TRUE ~ "null"
      ),
      significant   = p_value < 0.05
    )
  }
)

dep_loo_results <- dep_loo_results %>%
  dplyr::left_join(study_labels, by = c("dropped_study" = "study_id")) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

dep_loo_results

  dropped_study study_label                     k_remaining estimate
1  1            Blades et al. 2024              5           -0.5546686
2  6            Hinkka et al. 2016              5           -0.5329537
3 13            Epel et al. 2025                5           -0.4532231
4  4            Slezakova et al. 2025           5           -0.3827977
5 10            Petraskova Touskova et al. 2022 5           -0.3479360
6  5            Faid et al. 2022                5           -0.2042560
  se        ci_lb      ci_ub      p_value   tau2       direction significant
1 0.2308445 -1.1955956 0.08625849 0.0741325 0.17466498 negative  FALSE
2 0.2614542 -1.2588669 0.19295949 0.1111430 0.23395080 negative  FALSE
3 0.2781085 -1.2253760 0.31892971 0.1785056 0.28819939 negative  FALSE
4 0.2539411 -1.0878513 0.32225586 0.2061828 0.24695955 negative  FALSE
5 0.2320765 -0.9922837 0.29641172 0.2081894 0.20715805 negative  FALSE
6 0.1733225 -0.6854764 0.27696445 0.3039256 0.07297264 negative  FALSE

In [30]:
## --------------------------------------------
## Leave-one-out only among controlled studies
## --------------------------------------------

dep_loo_controlled_results <- purrr::map_dfr(
  unique(dep_controlled_dat$study_id),
  function(drop_study) {

    loo_dat <- dep_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    loo_model <- metafor::rma.mv(
      yi     = yi,
      V      = vi,
      random = ~ 1 | study_id,
      method = "REML",
      test   = "t",
      dfs    = "contain",
      data   = loo_dat
    )

    tibble::tibble(
      dropped_study = drop_study,
      k_remaining   = nrow(loo_dat),
      estimate      = as.numeric(loo_model$b),
      se            = loo_model$se,
      ci_lb         = loo_model$ci.lb,
      ci_ub         = loo_model$ci.ub,
      p_value       = loo_model$pval,
      tau2          = loo_model$sigma2,
      direction     = dplyr::case_when(
        estimate < 0 ~ "negative",
        estimate > 0 ~ "positive",
        TRUE ~ "null"
      ),
      significant   = p_value < 0.05
    )
  }
)

dep_loo_controlled_results <- dep_loo_controlled_results %>%
  dplyr::left_join(study_labels, by = c("dropped_study" = "study_id")) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

dep_loo_controlled_results

  dropped_study study_label                     k_remaining estimate
1  1            Blades et al. 2024              4           -0.3436342
2  6            Hinkka et al. 2016              4           -0.3479943
3 13            Epel et al. 2025                4           -0.2270943
4 10            Petraskova Touskova et al. 2022 4           -0.1003450
5  4            Slezakova et al. 2025           4           -0.1047195
  se        ci_lb      ci_ub     p_value   tau2       direction significant
1 0.2059292 -0.9989930 0.3117245 0.1937688 0.08186943 negative  FALSE
2 0.2651589 -1.1918484 0.4958597 0.2807637 0.16149318 negative  FALSE
3 0.2524900 -1.0306303 0.5764417 0.4347159 0.15561297 negative  FALSE
4 0.1351644 -0.5304984 0.3298085 0.5116932 0.02429769 negative  FALSE
5 0.1464280 -0.5707188 0.3612799 0.5261427 0.03169444 negative  FALSE

In [31]:
## --------------------------------------------
## Simple classification of robustness
## --------------------------------------------

dep_robustness_summary <- tibble::tibble(
  analysis = c("all_designs", "controlled_only"),
  all_negative_direction = c(
    all(dep_loo_results$estimate < 0),
    all(dep_loo_controlled_results$estimate < 0)
  ),
  any_significant_models = c(
    any(dep_loo_results$significant),
    any(dep_loo_controlled_results$significant)
  ),
  estimate_min = c(
    min(dep_loo_results$estimate),
    min(dep_loo_controlled_results$estimate)
  ),
  estimate_max = c(
    max(dep_loo_results$estimate),
    max(dep_loo_controlled_results$estimate)
  ),
  tau2_min = c(
    min(dep_loo_results$tau2),
    min(dep_loo_controlled_results$tau2)
  ),
  tau2_max = c(
    max(dep_loo_results$tau2),
    max(dep_loo_controlled_results$tau2)
  )
)

dep_robustness_summary

  analysis        all_negative_direction any_significant_models estimate_min
1 all_designs     TRUE                   FALSE                  -0.5546686
2 controlled_only TRUE                   FALSE                  -0.3479943
  estimate_max tau2_min   tau2_max
1 -0.204256    0.07297264 0.2881994
2 -0.100345    0.02429769 0.1614932

In [32]:
## ============================================================
## DEPRESSION
## Bayesian-style heterogeneity sensitivity analysis
## Weakly informative tau² grid approach
## ============================================================

## ------------------------------------------------------------
## Rationale
## ------------------------------------------------------------
## With very low k, tau² estimates are unstable.
## Instead of relying only on the REML estimate, we rerun the
## main model with tau² fixed to several plausible values.
##
## This is not a fully Bayesian model, but it approximates the
## question:
## "Do conclusions change meaningfully if heterogeneity is lower
## or higher than estimated by REML?"
##
## tau² values chosen:
## 0.00 = no heterogeneity
## 0.05 = low heterogeneity
## 0.10 = modest heterogeneity
## 0.20 = close to observed REML estimate
## 0.40 = high heterogeneity
## ------------------------------------------------------------

tau2_grid <- c(0.00, 0.05, 0.10, 0.20, 0.40)

dep_tau_sensitivity <- purrr::map_dfr(
  tau2_grid,
  function(tau2_value) {

    tau_model <- metafor::rma.uni(
      yi     = yi,
      vi     = vi,
      method = "REML",
      tau2   = tau2_value,
      weighted = TRUE,
      test   = "knha",
      data   = dep_main_dat
    )

    tibble::tibble(
      tau2_fixed = tau2_value,
      estimate   = as.numeric(tau_model$b),
      se         = tau_model$se,
      ci_lb      = tau_model$ci.lb,
      ci_ub      = tau_model$ci.ub,
      p_value    = tau_model$pval
    )
  }
)

dep_tau_sensitivity <- dep_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative",
      estimate > 0 ~ "positive",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

dep_tau_sensitivity

  tau2_fixed estimate   se        ci_lb      ci_ub     p_value    direction
1 0.00       -0.2466209 0.1913390 -0.7384734 0.2452316 0.25383480 negative
2 0.05       -0.3487108 0.2120352 -0.8937647 0.1963431 0.16097466 negative
3 0.10       -0.3825184 0.2154852 -0.9364408 0.1714040 0.13604228 negative
4 0.20       -0.4162275 0.2178291 -0.9761750 0.1437201 0.11426922 negative
5 0.40       -0.4462476 0.2193087 -1.0099986 0.1175034 0.09751378 negative
  significant
1 FALSE
2 FALSE
3 FALSE
4 FALSE
5 FALSE

In [33]:
## ============================================================
## Depression summary table for manuscript interpretation
## ============================================================

dep_summary_for_writeup <- tibble::tibble(
  analysis = c(
    "Main model all designs",
    "Controlled only",
    "Leave one out range",
    "Tau sensitivity range"
  ),
  result = c(
    paste0(
      "g = ",
      round(as.numeric(res_dep_main_mv$b), 2),
      ", p = ",
      round(res_dep_main_mv$pval, 3)
    ),
    paste0(
      "g = ",
      round(as.numeric(res_dep_controlled_mv$b), 2),
      ", p = ",
      round(res_dep_controlled_mv$pval, 3)
    ),
    paste0(
      round(min(dep_loo_results$estimate), 2),
      " to ",
      round(max(dep_loo_results$estimate), 2)
    ),
    paste0(
      round(min(dep_tau_sensitivity$estimate), 2),
      " to ",
      round(max(dep_tau_sensitivity$estimate), 2)
    )
  )
)

dep_summary_for_writeup

  analysis               result
1 Main model all designs g = -0.42, p = 0.119
2 Controlled only        g = -0.2, p = 0.304
3 Leave one out range    -0.55 to -0.2
4 Tau sensitivity range  -0.45 to -0.25

In [34]:
## ============================================================
## DEPRESSION
## Publication style forest plots using metafor
## ============================================================

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [35]:
## ------------------------------------------------------------
## Study metadata for plotting
## ------------------------------------------------------------

dep_plot_info <- dep_change_wide_study %>%
  dplyr::left_join(study_labels, by = "study_id") %>%
  dplyr::mutate(
    n_int = dplyr::if_else(design == "controlled", n_change_Intervention, NA_real_),
    n_con = dplyr::if_else(design == "controlled", n_change_Control, NA_real_),
    n_sg  = dplyr::if_else(design == "single_group", n_change_SingleGroup, NA_real_),
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    ),
    design_label = dplyr::case_when(
      design == "controlled"   ~ "Controlled",
      design == "single_group" ~ "Single group",
      TRUE ~ design
    )
  ) %>%
  dplyr::select(
    study_id,
    study_label,
    design,
    design_label,
    n_int,
    n_con,
    n_sg,
    N_study
  )

In [36]:
## ------------------------------------------------------------
## Controlled only forest plot dataset
## ------------------------------------------------------------

dep_forest_controlled <- es_dep_controlled %>%
  dplyr::left_join(dep_plot_info, by = "study_id") %>%
  dplyr::mutate(
    sei = sqrt(vi)
  ) %>%
  dplyr::arrange(study_id)

## This model is only for plotting the pooled diamond
## Main inference should still come from your rma.mv model
res_dep_controlled_plot <- metafor::rma.uni(
  yi     = yi,
  vi     = vi,
  method = "REML",
  test   = "knha",
  data   = dep_forest_controlled
)

dep_forest_controlled <- dep_forest_controlled %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_dep_controlled_plot) / sum(weights(res_dep_controlled_plot)),
    ci_lb_plot    = yi - 1.96 * sei,
    ci_ub_plot    = yi + 1.96 * sei,
    effect_ci     = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    n_int_lab     = ifelse(is.na(n_int), "", as.character(as.integer(n_int))),
    n_con_lab     = ifelse(is.na(n_con), "", as.character(as.integer(n_con))),
    weight_lab    = sprintf("%.0f%%", round(weight_random, 0))
  )

In [37]:
## ------------------------------------------------------------
## All designs forest plot dataset
## ------------------------------------------------------------

dep_forest_all <- es_dep_all %>%
  dplyr::left_join(dep_plot_info, by = "study_id") %>%
  dplyr::mutate(
    sei = sqrt(vi)
  ) %>%
  dplyr::arrange(study_id)

res_dep_all_plot <- metafor::rma.uni(
  yi     = yi,
  vi     = vi,
  method = "REML",
  test   = "knha",
  data   = dep_forest_all
)

dep_forest_all <- dep_forest_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_dep_all_plot) / sum(weights(res_dep_all_plot)),
    ci_lb_plot    = yi - 1.96 * sei,
    ci_ub_plot    = yi + 1.96 * sei,
    effect_ci     = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab         = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    weight_lab    = sprintf("%.0f%%", round(weight_random, 0))
  )

In [38]:
## Plot labels
## ------------------------------------------------------------

dep_forest_controlled <- dep_forest_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

dep_forest_all <- dep_forest_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [39]:
## Helper function
## Controlled study forest plot in table style
## ------------------------------------------------------------

save_forest_controlled_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Depression"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  ## Column positions
  x_study  <- -4.65
  x_nint   <- -3.00
  x_ncon   <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  ## Header
  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_nint,   k + 1.15, "CWE\n(n)", font = 2, cex = 0.9)
  text(x_ncon,   k + 1.15, "Control\n(n)", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  ## Study table text
  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_nint,   rows, dat$n_int_lab, cex = 0.88)
  text(x_ncon,   rows, dat$n_con_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  ## Overall row
  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  ## Bottom labels
  mtext("Standardised mean difference (Hedges g)", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [40]:
## Helper function
## All designs forest plot in table style
## ------------------------------------------------------------

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Depression"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  ## Column positions
  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  ## Header
  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  ## Study table text
  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  ## Overall row
  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  ## Bottom labels
  mtext("Standardised mean difference (Hedges g)", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [41]:
## ------------------------------------------------------------
## Save controlled only journal style forest plot
## ------------------------------------------------------------

save_forest_controlled_journal(
  dat = dep_forest_controlled,
  model = res_dep_controlled_plot,
  file = file.path(graph_path, "forest_depression_controlled_journal_style.pdf"),
  outcome_title = "Depression, controlled studies"
)

## ------------------------------------------------------------
## Save all designs journal style forest plot
## ------------------------------------------------------------

save_forest_all_designs_journal(
  dat = dep_forest_all,
  model = res_dep_all_plot,
  file = file.path(graph_path, "forest_depression_all_designs_journal_style.pdf"),
  outcome_title = "Depression, all designs"
)

agg_record_1503543430
                    2

agg_record_1503543430
                    2

In [42]:
## ------------------------------------------------------------
## Prepare leave one out plot data
## ------------------------------------------------------------

dep_total_N_all <- sum(dep_plot_info$N_study, na.rm = TRUE)

dep_total_N_controlled <- dep_plot_info %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

dep_loo_plot_all <- dep_loo_results %>%
  dplyr::left_join(
    dep_plot_info %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = dep_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb = estimate - 1.96 * se,
    ci_ub = estimate + 1.96 * se,
    model_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Drop: Petraskova Touskova et al.\n2022",
      model_label
    ),
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb, ci_ub)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    ci_lb,
    ci_ub,
    estimate_lab,
    se_lab,
    effect_ci
  )

dep_loo_plot_controlled <- dep_loo_controlled_results %>%
  dplyr::left_join(
    dep_plot_info %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = dep_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb = estimate - 1.96 * se,
    ci_ub = estimate + 1.96 * se,
    model_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Drop: Petraskova Touskova et al.\n2022",
      model_label
    ),
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb, ci_ub)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    ci_lb,
    ci_ub,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [43]:
## ------------------------------------------------------------
## Prepare tau sensitivity plot data
## ------------------------------------------------------------

dep_tau_plot <- dep_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_fixed, format = "f", digits = 2)),
    TE = estimate,
    seTE = se,
    ci_lb = estimate - 1.96 * se,
    ci_ub = estimate + 1.96 * se,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb, ci_ub)
  ) %>%
  dplyr::select(
    model_label,
    N_lab,
    TE,
    seTE,
    ci_lb,
    ci_ub,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [44]:
## ------------------------------------------------------------
## Generic helper
## Journal style sensitivity forest plot
## ------------------------------------------------------------

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  ## Column positions
  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  ## Header
  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  ## Model labels
  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  ## Bottom labels
  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [45]:
## ------------------------------------------------------------
## Save leave one out forest plot for all designs
## ------------------------------------------------------------

save_sensitivity_forest_journal(
  dat = dep_loo_plot_all,
  file = file.path(graph_path, "forest_depression_leave_one_out_all_designs.pdf"),
  title_left = "Depression, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_dep_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

## ------------------------------------------------------------
## Save leave one out forest plot for controlled only
## ------------------------------------------------------------

save_sensitivity_forest_journal(
  dat = dep_loo_plot_controlled,
  file = file.path(graph_path, "forest_depression_leave_one_out_controlled_only.pdf"),
  title_left = "Depression, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = as.numeric(res_dep_controlled_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

## ------------------------------------------------------------
## Save tau sensitivity forest plot
## ------------------------------------------------------------

save_sensitivity_forest_journal(
  dat = dep_tau_plot,
  file = file.path(graph_path, "forest_depression_tau_sensitivity.pdf"),
  title_left = "Depression, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_dep_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_513809325
                   2

agg_record_513809325
                   2

agg_record_513809325
                   2

In [46]:
## ------------------------------------------------------------
## Create tables with rounded values
## ------------------------------------------------------------

round_df_2 <- function(df) {
  df %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )
}

In [47]:
## ------------------------------------------------------------
## Helper to build study level export tables
## ------------------------------------------------------------

make_study_effect_table <- function(df) {

  df_export <- df

  ## Standardise design column
  if ("design_type" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(design_type = as.character(design_type))
  } else if ("design" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(design_type = as.character(design))
  } else if ("design_label" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(design_type = as.character(design_label))
  } else {
    df_export <- df_export %>%
      dplyr::mutate(design_type = NA_character_)
  }

  ## Standardise study N column
  if (!"N_study" %in% names(df_export)) {
    if ("N" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::rename(N_study = N)
    } else {
      df_export <- df_export %>%
        dplyr::mutate(N_study = NA_real_)
    }
  }

  ## Build final export table
  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

In [48]:
## ------------------------------------------------------------
## Study level tables
## ------------------------------------------------------------

tab_dep_main_studies <- make_study_effect_table(dep_forest_all)

tab_dep_controlled_studies <- make_study_effect_table(dep_forest_controlled)

In [49]:
## ------------------------------------------------------------
## Model comparison table
## ------------------------------------------------------------

tab_dep_model_compare <- tibble::tibble(
  model    = c("main_all_designs", "controlled_only"),
  k        = c(nrow(dep_main_dat), nrow(dep_controlled_dat)),
  estimate = c(
    as.numeric(res_dep_main_mv$b),
    as.numeric(res_dep_controlled_mv$b)
  ),
  se       = c(
    as.numeric(res_dep_main_mv$se),
    as.numeric(res_dep_controlled_mv$se)
  ),
  ci_lb    = c(
    as.numeric(res_dep_main_mv$ci.lb),
    as.numeric(res_dep_controlled_mv$ci.lb)
  ),
  ci_ub    = c(
    as.numeric(res_dep_main_mv$ci.ub),
    as.numeric(res_dep_controlled_mv$ci.ub)
  ),
  p_value  = c(
    as.numeric(res_dep_main_mv$pval),
    as.numeric(res_dep_controlled_mv$pval)
  ),
  tau2     = c(
    as.numeric(res_dep_main_mv$sigma2),
    as.numeric(res_dep_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

In [50]:
## ------------------------------------------------------------
## Leave one out tables
## ------------------------------------------------------------

tab_dep_loo_all <- dep_loo_results %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2,
    direction,
    significant
  ) %>%
  round_df_2()

tab_dep_loo_controlled <- dep_loo_controlled_results %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2,
    direction,
    significant
  ) %>%
  round_df_2()

In [51]:
## ------------------------------------------------------------
## Tau sensitivity table
## ------------------------------------------------------------

tab_dep_tau_sensitivity <- dep_tau_sensitivity %>%
  dplyr::select(
    tau2_fixed,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    direction,
    significant
  ) %>%
  round_df_2()

In [52]:
## ------------------------------------------------------------
## Sample size tables
## ------------------------------------------------------------

tab_dep_N_by_study <- dep_N_by_study %>%
  round_df_2()

tab_dep_N_by_design <- dep_N_by_design %>%
  round_df_2()

In [53]:
## ------------------------------------------------------------
## Save tables as csv
## ------------------------------------------------------------

readr::write_csv(
  tab_dep_main_studies,
  file.path(table_path, "depression_study_effects_main_all_designs.csv")
)

readr::write_csv(
  tab_dep_controlled_studies,
  file.path(table_path, "depression_study_effects_controlled_only.csv")
)

readr::write_csv(
  tab_dep_model_compare,
  file.path(table_path, "depression_model_comparison.csv")
)

readr::write_csv(
  tab_dep_loo_all,
  file.path(table_path, "depression_leave_one_out_all_designs.csv")
)

readr::write_csv(
  tab_dep_loo_controlled,
  file.path(table_path, "depression_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_dep_tau_sensitivity,
  file.path(table_path, "depression_tau_sensitivity.csv")
)

readr::write_csv(
  tab_dep_N_by_study,
  file.path(table_path, "depression_sample_size_by_study.csv")
)

readr::write_csv(
  tab_dep_N_by_design,
  file.path(table_path, "depression_sample_size_by_design.csv")
)

In [54]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved tables to:\n", table_path, "\n", sep = "")

cat("\nSaved depression csv files:\n")
print(list.files(table_path, pattern = "depression.*csv$", full.names = TRUE))

Saved PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

Saved depression csv files:
[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_leave_one_out_all_designs.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_leave_one_out_controlled_only.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_model_comparison.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_sample_size_by_design.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_sample_size_by_study.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_study_effects_controlled_only.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_study_effects_main_all_designs.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/depression_tau_sensitivity.csv"

#### **Overall Interpretation** 
The main multilevel model including all study designs suggested a small-to-moderate reduction in depressive symptoms associated with CWE (g ≈ −0.42), but with wide uncertainty and no statistically reliable effect under Hartung-Knapp-style inference. The controlled-only model attenuated notably to around g ≈ −0.20, suggesting that a substantial part of the apparent benefit may be driven by the uncontrolled single-group study rather than by comparative treatment effects.

The leave-one-out results shows that the direction remained negative in every single model, both in the all-designs analysis and in the controlled-only analysis. That means the conclusion is not being reversed by any individual study. However, the magnitude varied considerably:
* all-designs models ranged from about −0.55 to −0.20
* controlled-only models ranged from about −0.35 to −0.10

This pattern suggests that the depression signal is directionally stable but quantitatively fragile. The tau sensitivity analysis strengthens that interpretation further. Across a wide range of assumed heterogeneity values, the pooled effect remained consistently negative, roughly between −0.25 and −0.45. So the overall conclusion is not very sensitive to assumptions about heterogeneity. What changes is not the direction of the effect, but the certainty around it.

All in all, CWE showed a consistent tendency toward reduced depressive symptoms across analyses, but the magnitude of this association was modest and depended partly on study design. Effects were attenuated when analyses were restricted to controlled studies, suggesting that uncontrolled within-person improvement may contribute to the larger effects observed in the overall synthesis. Leave-one-out and heterogeneity sensitivity analyses showed that the direction of effect was stable, although the estimated magnitude varied across models. Overall, the evidence suggests a possible signal toward benefit, but current findings remain imprecise, heterogeneous, and design-dependent.

## **Mood/Affect**
[Back to Table of Content](#table-of-content)

In [55]:
## ============================================================
## Filter mental data to Mood/Affect + code valence
## ============================================================

mental_mood <- mental %>%
  dplyr::filter(instrument_domain == "Mood_Affect") %>%
  dplyr::mutate(
    # Valence of the score: does a higher score mean better or worse mood?
    valence = dplyr::case_when(
      instrument == "PANAS" & subscale == "positive affect" ~ "positive",  # higher = better
      instrument == "PANAS" & subscale == "negative affect" ~ "negative",  # higher = worse

      instrument == "MDES"  & subscale == "positive"        ~ "positive",
      instrument == "MDES"  & subscale == "negative"        ~ "negative",

      instrument == "POMS"  & subscale == "Vigor"           ~ "positive",
      instrument == "POMS"  & subscale %in% c("Tension", "Fatigue", "Depression") ~ "negative",

      # Huttunen et al. use OIRE mood “negative state points”: higher = worse mood
      instrument == "OIRE"  & subscale == "mood"            ~ "negative",

      TRUE ~ NA_character_
    ),

    # direction_factor:
    #   +1 : keep sign (higher = better → positive SMD = better)
    #   -1 : flip sign (higher = worse → negative SMD becomes positive = better)
    direction_factor = dplyr::case_when(
      valence == "positive" ~  1,
      valence == "negative" ~ -1,
      TRUE                  ~ NA_real_
    )
  )

# One row per subscale used later to join valence information
mood_valence_map <- mental_mood %>%
  dplyr::distinct(study_id, instrument, subscale, valence, direction_factor)

In [56]:
## ------------------------------------------------------------
## Reconstruct change SD from 95% CI if available
## ------------------------------------------------------------

mental_mood <- mental_mood %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [57]:
## ------------------------------------------------------------
## Estimate mean & SD from median + IQR where needed
## ------------------------------------------------------------

mental_mood <- mental_mood %>%
  dplyr::mutate(
    has_IQR = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_IQR & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_IQR & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_IQR)

In [58]:
## ------------------------------------------------------------
## Select Pre/Post data & prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

mood_prepost <- mental_mood %>%
  dplyr::filter(timepoint_label_harmonised %in% c("Pre", "Post")) %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels),
    group_harmonised = dplyr::case_when(
      study_id == 9 & group_harmonised == "Intervention" ~ "SingleGroup",
      TRUE ~ group_harmonised
    )
  ) %>%
  dplyr::arrange(
    study_id,
    instrument,
    subscale,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id, instrument, subscale,
    group_harmonised, timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

# Quick check
mood_prepost %>%
  dplyr::count(study_id, instrument, subscale,
               group_harmonised, timepoint_label_harmonised)

   study_id instrument subscale        group_harmonised
1   1       MDES       negative        Control
2   1       MDES       negative        Intervention
3   1       MDES       positive        Control
4   1       MDES       positive        Intervention
5   3       PANAS      negative affect Control
6   3       PANAS      negative affect Control
7   3       PANAS      negative affect Intervention
8   3       PANAS      negative affect Intervention
9   3       PANAS      positive affect Control
10  3       PANAS      positive affect Control
11  3       PANAS      positive affect Intervention
12  3       PANAS      positive affect Intervention
13  8       OIRE       mood            Control
14  8       OIRE       mood            Control
15  8       OIRE       mood            Intervention
16  8       OIRE       mood            Intervention
17  8       POMS       Depression      Control
18  8       POMS       Depression      Control
19  8       POMS       Depression      Intervention
20  8       POMS       Depression      Intervention
21  8       POMS       Fatigue         Control
22  8       POMS       Fatigue         Control
23  8       POMS       Fatigue         Intervention
24  8       POMS       Fatigue         Intervention
25  8       POMS       Tension         Control
26  8       POMS       Tension         Control
27  8       POMS       Tension         Intervention
28  8       POMS       Tension         Intervention
29  8       POMS       Vigor           Control
30  8       POMS       Vigor           Control
31  8       POMS       Vigor           Intervention
32  8       POMS       Vigor           Intervention
33 11       PANAS      negative affect SingleGroup
34 11       PANAS      negative affect SingleGroup
35 11       PANAS      positive affect SingleGroup
36 11       PANAS      positive affect SingleGroup
37 12       PANAS      negative affect SingleGroup
38 12       PANAS      negative affect SingleGroup
39 12       PANAS      positive affect SingleGroup
40 12       PANAS      positive affect SingleGroup
41 13       MDES       negative        Control
42 13       MDES       negative        Control
43 13       MDES       negative        Intervention
44 13       MDES       negative        Intervention
45 13       MDES       positive        Control
46 13       MDES       positive        Control
47 13       MDES       positive        Intervention
48 13       MDES       positive        Intervention
   timepoint_label_harmonised n
1  Post                       1
2  Post                       1
3  Post                       1
4  Post                       1
5  Post                       1
6  Pre                        1
7  Post                       1
8  Pre                        1
9  Post                       1
10 Pre                        1
11 Post                       1
12 Pre                        1
13 Post                       1
14 Pre                        1
15 Post                       1
16 Pre                        1
17 Post                       1
18 Pre                        1
19 Post                       1
20 Pre                        1
21 Post                       1
22 Pre                        1
23 Post                       1
24 Pre                        1
25 Post                       1
26 Pre                        1
27 Post                       1
28 Pre                        1
29 Post                       1
30 Pre                        1
31 Post                       1
32 Pre                        1
33 Post                       1
34 Pre                        1
35 Post                       1
36 Pre                        1
37 Post                       1
38 Pre                        1
39 Post                       1
40 Pre                        1
41 Post                       1
42 Pre                        1
43 Post                       1
44 Pre                        1
45 Post                       1
46 Pre                        1
47 Post                       1
48 Pre                        1

In [59]:
## ------------------------------------------------------------
## Compute change scores Δ = Post − Pre per group
## ------------------------------------------------------------

r_change <- 0.5  # assumed pre–post correlation

mood_wide <- mood_prepost %>%
  tidyr::pivot_wider(
    id_cols    = c(study_id, instrument, subscale, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      is.na(mean_Pre) | is.na(mean_Post)   ~ dplyr::coalesce(
        change_mean_Post,
        change_mean_Pre
      ),
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      (is.na(sd_Pre) | is.na(sd_Post)) ~ dplyr::coalesce(
        change_sd_Post,
        change_sd_Pre
      ),
      TRUE ~ NA_real_
    )
  )

mood_wide %>%
  dplyr::select(study_id, instrument, subscale,
                group_harmonised,
                n_change, change_mean_calc, change_sd_calc) %>%
  dplyr::arrange(study_id, instrument, subscale, group_harmonised)

   study_id instrument subscale        group_harmonised n_change
1   1       MDES       negative        Control          41
2   1       MDES       negative        Intervention     43
3   1       MDES       positive        Control          41
4   1       MDES       positive        Intervention     43
5   3       PANAS      negative affect Control          20
6   3       PANAS      negative affect Intervention     21
7   3       PANAS      positive affect Control          20
8   3       PANAS      positive affect Intervention     21
9   8       OIRE       mood            Control          13
10  8       OIRE       mood            Intervention     23
11  8       POMS       Depression      Control          13
12  8       POMS       Depression      Intervention     23
13  8       POMS       Fatigue         Control          13
14  8       POMS       Fatigue         Intervention     23
15  8       POMS       Tension         Control          13
16  8       POMS       Tension         Intervention     23
17  8       POMS       Vigor           Control          13
18  8       POMS       Vigor           Intervention     23
19 11       PANAS      negative affect SingleGroup      13
20 11       PANAS      positive affect SingleGroup      13
21 12       PANAS      negative affect SingleGroup      32
22 12       PANAS      positive affect SingleGroup      32
23 13       MDES       negative        Control          36
24 13       MDES       negative        Intervention     34
25 13       MDES       positive        Control          36
26 13       MDES       positive        Intervention     34
   change_mean_calc change_sd_calc
1       NA                 NA
2       NA                 NA
3       NA                 NA
4       NA                 NA
5  -0.0600          0.5086256
6   0.0300          0.5243091
7  -0.1800          0.3893584
8  -0.0400          0.3119295
9  -0.5000          2.1166010
10 -0.7000          2.0952327
11 -1.3000          6.2793312
12 -0.5000          5.0921508
13  0.1000          2.6514147
14 -1.6000          2.9137605
15 -1.2000          4.5044423
16 -0.8000          2.6057628
17  0.6000          4.8135226
18  0.8000          4.0595566
19 -2.0000          2.6457513
20 -1.0000          7.0000000
21 -4.6875          4.1560321
22  7.0000          6.9208987
23 -0.3000          0.5144900
24 -0.2600          0.4150904
25 -0.0100          0.7332803
26  0.4400          0.7213182

In [60]:
## ------------------------------------------------------------
## Classify designs
## ------------------------------------------------------------

mood_wide <- mood_wide %>%
  dplyr::group_by(study_id, instrument, subscale) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

mood_wide %>%
  dplyr::distinct(study_id, instrument, subscale, design)

   study_id instrument subscale        design
1   1       MDES       negative        controlled
2   1       MDES       positive        controlled
3   3       PANAS      negative affect controlled
4   3       PANAS      positive affect controlled
5   8       OIRE       mood            controlled
6   8       POMS       Depression      controlled
7   8       POMS       Fatigue         controlled
8   8       POMS       Tension         controlled
9   8       POMS       Vigor           controlled
10 11       PANAS      negative affect single_group
11 11       PANAS      positive affect single_group
12 12       PANAS      negative affect single_group
13 12       PANAS      positive affect single_group
14 13       MDES       negative        controlled
15 13       MDES       positive        controlled

In [61]:
## ------------------------------------------------------------
## Prepare group-level change data
## ------------------------------------------------------------

mood_change_groups <- mood_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id, instrument, subscale,
    design, group_harmonised,
    change_mean_calc, change_sd_calc, n_change
  )

mood_change_groups %>%
  dplyr::arrange(study_id, instrument, subscale, group_harmonised)

   study_id instrument subscale        design       group_harmonised
1   3       PANAS      negative affect controlled   Control
2   3       PANAS      negative affect controlled   Intervention
3   3       PANAS      positive affect controlled   Control
4   3       PANAS      positive affect controlled   Intervention
5   8       OIRE       mood            controlled   Control
6   8       OIRE       mood            controlled   Intervention
7   8       POMS       Depression      controlled   Control
8   8       POMS       Depression      controlled   Intervention
9   8       POMS       Fatigue         controlled   Control
10  8       POMS       Fatigue         controlled   Intervention
11  8       POMS       Tension         controlled   Control
12  8       POMS       Tension         controlled   Intervention
13  8       POMS       Vigor           controlled   Control
14  8       POMS       Vigor           controlled   Intervention
15 11       PANAS      negative affect single_group SingleGroup
16 11       PANAS      positive affect single_group SingleGroup
17 12       PANAS      negative affect single_group SingleGroup
18 12       PANAS      positive affect single_group SingleGroup
19 13       MDES       negative        controlled   Control
20 13       MDES       negative        controlled   Intervention
21 13       MDES       positive        controlled   Control
22 13       MDES       positive        controlled   Intervention
   change_mean_calc change_sd_calc n_change
1  -0.0600          0.5086256      20
2   0.0300          0.5243091      21
3  -0.1800          0.3893584      20
4  -0.0400          0.3119295      21
5  -0.5000          2.1166010      13
6  -0.7000          2.0952327      23
7  -1.3000          6.2793312      13
8  -0.5000          5.0921508      23
9   0.1000          2.6514147      13
10 -1.6000          2.9137605      23
11 -1.2000          4.5044423      13
12 -0.8000          2.6057628      23
13  0.6000          4.8135226      13
14  0.8000          4.0595566      23
15 -2.0000          2.6457513      13
16 -1.0000          7.0000000      13
17 -4.6875          4.1560321      32
18  7.0000          6.9208987      32
19 -0.3000          0.5144900      36
20 -0.2600          0.4150904      34
21 -0.0100          0.7332803      36
22  0.4400          0.7213182      34

In [62]:
## ------------------------------------------------------------
## EFFECT SIZES — CONTROLLED TRIALS (ΔI vs ΔC)
## ------------------------------------------------------------

mood_change_wide_study <- mood_change_groups %>%
  tidyr::pivot_wider(
    id_cols    = c(study_id, instrument, subscale, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

es_mood_controlled <- mood_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .
  ) %>%
  dplyr::mutate(
    outcome_domain = "Mood_Affect",
    design_type    = "controlled"
  )

es_mood_controlled %>%
  dplyr::select(
    study_id, instrument, subscale,
    yi, vi, outcome_domain, design_type
  )

  study_id instrument subscale        yi          vi         outcome_domain
1  3       PANAS      negative affect  0.17079818 0.09797480 Mood_Affect
2  3       PANAS      positive affect  0.39025754 0.09947638 Mood_Affect
3  8       OIRE       mood            -0.09299510 0.12052145 Mood_Affect
4  8       POMS       Depression       0.14118422 0.12067818 Mood_Affect
5  8       POMS       Fatigue         -0.58859896 0.12521313 Mood_Affect
6  8       POMS       Tension          0.11505578 0.12058520 Mood_Affect
7  8       POMS       Vigor            0.04505094 0.12042953 Mood_Affect
8 13       MDES       negative         0.08436271 0.05724038 Mood_Affect
9 13       MDES       positive         0.61170520 0.05986228 Mood_Affect
  design_type
1 controlled
2 controlled
3 controlled
4 controlled
5 controlled
6 controlled
7 controlled
8 controlled
9 controlled

In [63]:
## ------------------------------------------------------------
## SAMPLE SIZE SUMMARY for this outcome domain
## One N per study, no double-counting across subscales
## ------------------------------------------------------------

mood_N_by_study <- mood_change_wide_study %>%
  dplyr::group_by(study_id, design) %>%
  dplyr::reframe(
    N_study = dplyr::case_when(
      design == "controlled" ~ {
        x <- n_change_Intervention + n_change_Control
        if (all(is.na(x))) NA_real_ else max(x, na.rm = TRUE)
      },
      design == "single_group" ~ {
        x <- n_change_SingleGroup
        if (all(is.na(x))) NA_real_ else max(x, na.rm = TRUE)
      },
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::filter(!is.na(N_study))

# Number of studies contributing to this outcome domain
k_mood <- nrow(mood_N_by_study)

# Total number of participants across all included studies
N_mood_total <- sum(mood_N_by_study$N_study, na.rm = TRUE)

# Breakdown by design (controlled vs single_group)
mood_N_by_design <- mood_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups  = "drop"
  )

# Print summary
cat("\nMood/Affect meta-analysis:\n")
cat("  Number of studies (k): ", k_mood, "\n", sep = "")
cat("  Total participants (N): ", N_mood_total, "\n", sep = "")

cat("\nBreakdown by design:\n")
print(mood_N_by_design)

Mood/Affect meta-analysis:
  Number of studies (k): 13
  Total participants (N): 492

Breakdown by design:
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          9      402
2 single_group        4       90

In [64]:
## ------------------------------------------------------------
## EFFECT SIZES — SINGLE-GROUP PRE–POST
## ------------------------------------------------------------

es_mood_single <- mood_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Mood_Affect",
    design_type    = "single_group"
  ) %>%
  dplyr::select(
    study_id, instrument, subscale,
    outcome_domain, design_type, yi, vi
  )

es_mood_single

  study_id instrument subscale        outcome_domain design_type  yi
1 11       PANAS      negative affect Mood_Affect    single_group -0.7114625
2 11       PANAS      positive affect Mood_Affect    single_group -0.1344538
3 12       PANAS      negative affect Mood_Affect    single_group -1.1012359
4 12       PANAS      positive affect Mood_Affect    single_group  0.9875373
  vi
1 0.08760789
2 0.06883477
3 0.04873982
4 0.04502903

In [65]:
## ------------------------------------------------------------
## COMBINE EFFECT SIZES, ALIGN DIRECTION & META-ANALYZE
## ------------------------------------------------------------

es_mood_all <- dplyr::bind_rows(
  es_mood_controlled %>%
    dplyr::select(study_id, instrument, subscale,
                  outcome_domain, design_type, yi, vi),
  es_mood_single
) %>%
  dplyr::left_join(
    mood_valence_map,
    by = c("study_id", "instrument", "subscale")
  ) %>%
  dplyr::mutate(
    yi_aligned = dplyr::if_else(
      !is.na(direction_factor),
      yi * direction_factor,
      yi
    )
  )

es_mood_all

   study_id instrument subscale        outcome_domain design_type  yi
1   3       PANAS      negative affect Mood_Affect    controlled    0.17079818
2   3       PANAS      positive affect Mood_Affect    controlled    0.39025754
3   8       OIRE       mood            Mood_Affect    controlled   -0.09299510
4   8       POMS       Depression      Mood_Affect    controlled    0.14118422
5   8       POMS       Fatigue         Mood_Affect    controlled   -0.58859896
6   8       POMS       Tension         Mood_Affect    controlled    0.11505578
7   8       POMS       Vigor           Mood_Affect    controlled    0.04505094
8  13       MDES       negative        Mood_Affect    controlled    0.08436271
9  13       MDES       positive        Mood_Affect    controlled    0.61170520
10 11       PANAS      negative affect Mood_Affect    single_group -0.71146254
11 11       PANAS      positive affect Mood_Affect    single_group -0.13445378
12 12       PANAS      negative affect Mood_Affect    single_group -1.10123588
13 12       PANAS      positive affect Mood_Affect    single_group  0.98753730
   vi         valence  direction_factor yi_aligned
1  0.09797480 negative -1               -0.17079818
2  0.09947638 positive  1                0.39025754
3  0.12052145 negative -1                0.09299510
4  0.12067818 negative -1               -0.14118422
5  0.12521313 negative -1                0.58859896
6  0.12058520 negative -1               -0.11505578
7  0.12042953 positive  1                0.04505094
8  0.05724038 negative -1               -0.08436271
9  0.05986228 positive  1                0.61170520
10 0.08760789 negative -1                0.71146254
11 0.06883477 positive  1               -0.13445378
12 0.04873982 negative -1                1.10123588
13 0.04502903 positive  1                0.98753730

In [66]:
## ============================================================
## MOOD AFFECT
## MAIN MODEL AND CONTROLLED-ONLY SENSITIVITY
## Multilevel random-effects framework as default
## Hartung-Knapp-like inference via t-distribution
## ============================================================

## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_mood <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [67]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------
## Important
## Main inference stays at the effect size level with rma.mv
## Forest plots are based on aggregated study level effects
## for display only

mood_main_dat <- es_mood_all %>%
  dplyr::arrange(study_id, instrument, subscale)

mood_controlled_dat <- es_mood_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, instrument, subscale)

cat("\nMood Affective main dataset\n")
cat("  k effects =", nrow(mood_main_dat), "\n")
cat("  studies =", paste(sort(unique(mood_main_dat$study_id)), collapse = ", "), "\n")

cat("\nMood Affective controlled only dataset\n")
cat("  k effects =", nrow(mood_controlled_dat), "\n")
cat("  studies =", paste(sort(unique(mood_controlled_dat$study_id)), collapse = ", "), "\n")

Mood Affective main dataset
  k effects = 13
  studies = 3, 8, 11, 12, 13

Mood Affective controlled only dataset
  k effects = 9
  studies = 3, 8, 13

In [68]:
## ------------------------------------------------------------
## Main multilevel model
## ------------------------------------------------------------
## Random intercept for study and nested effect level
## Hartung Knapp like inference via t distribution

res_mood_main_mv <- metafor::rma.mv(
  yi     = yi_aligned,
  V      = vi,
  random = ~ 1 | study_id/subscale,
  method = "REML",
  test   = "t",
  dfs    = "contain",
  data   = mood_main_dat
)

print(res_mood_main_mv)
broom::tidy(res_mood_main_mv)

Multivariate Meta-Analysis Model (k = 13; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed             factor
sigma^2.1  0.1063  0.3261      5     no           study_id
sigma^2.2  0.0613  0.2475     13     no  study_id/subscale

Test for Heterogeneity:
Q(df = 12) = 37.9242, p-val = 0.0002

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.3554  0.1816  1.9568   4  0.1220  -0.1489  0.8597

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.3554222 0.1816376 1.956766  0.1220063

In [69]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## ------------------------------------------------------------

res_mood_controlled_mv <- metafor::rma.mv(
  yi     = yi_aligned,
  V      = vi,
  random = ~ 1 | study_id/subscale,
  method = "REML",
  test   = "t",
  dfs    = "contain",
  data   = mood_controlled_dat
)

print(res_mood_controlled_mv)
broom::tidy(res_mood_controlled_mv)

Multivariate Meta-Analysis Model (k = 9; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed             factor
sigma^2.1  0.0000  0.0000      3     no           study_id
sigma^2.2  0.0241  0.1551      9     no  study_id/subscale

Test for Heterogeneity:
Q(df = 8) = 9.0902, p-val = 0.3347

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.1488  0.1156  1.2873   2  0.3269  -0.3485  0.6460

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.1487766 0.115572  1.287306  0.3268529

In [70]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

mood_model_compare <- dplyr::bind_rows(
  broom::tidy(res_mood_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  broom::tidy(res_mood_controlled_mv) %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

mood_model_compare

  model            term    estimate  std.error statistic p.value
1 main_all_designs overall 0.3554222 0.1816376 1.956766  0.1220063
2 controlled_only  overall 0.1487766 0.1155720 1.287306  0.3268529

In [71]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------
## We omit one study at a time from the multilevel model
## This is the correct unit for the sensitivity analysis here

mood_loo_results <- purrr::map_dfr(
  sort(unique(mood_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- mood_main_dat %>%
      dplyr::filter(study_id != drop_study)

    loo_model <- metafor::rma.mv(
      yi     = yi_aligned,
      V      = vi,
      random = ~ 1 | study_id/subscale,
      method = "REML",
      test   = "t",
      dfs    = "contain",
      data   = loo_dat
    )

    tibble::tibble(
      dropped_study = drop_study,
      k_effects_remaining = nrow(loo_dat),
      n_studies_remaining = dplyr::n_distinct(loo_dat$study_id),
      estimate = as.numeric(loo_model$b),
      se = loo_model$se,
      ci_lb = loo_model$ci.lb,
      ci_ub = loo_model$ci.ub,
      p_value = loo_model$pval,
      tau2_study = loo_model$sigma2[1],
      tau2_effect = loo_model$sigma2[2],
      direction = dplyr::case_when(
        estimate > 0 ~ "positive",
        estimate < 0 ~ "negative",
        TRUE ~ "null"
      ),
      significant = p_value < 0.05
    )
  }
)

mood_loo_results <- mood_loo_results %>%
  dplyr::left_join(study_labels_mood, by = c("dropped_study" = "study_id")) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    tau2_effect,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

mood_loo_results

  dropped_study study_label             k_effects_remaining n_studies_remaining
1  8            Huttunen et al. 2004     8                  4
2  3            Ketelhut et al. 2023    11                  4
3 11            Reed et al. 2023        11                  4
4 13            Epel et al. 2025        11                  4
5 12            Yankouskaya et al. 2023 11                  4
  estimate  se        ci_lb      ci_ub     p_value   tau2_study   tau2_effect
1 0.4353484 0.2179502 -0.2582663 1.1289632 0.1396684 9.901905e-02 0.11251391
2 0.4095893 0.2172810 -0.2818959 1.1010745 0.1559123 1.348459e-01 0.06076680
3 0.3809723 0.2299332 -0.3507778 1.1127224 0.1961214 1.692215e-01 0.02672834
4 0.3803036 0.2322631 -0.3588612 1.1194683 0.2000741 1.697488e-01 0.03034960
5 0.1690935 0.1100350 -0.1810869 0.5192739 0.2219512 1.639655e-11 0.04017662
  direction significant
1 positive  FALSE
2 positive  FALSE
3 positive  FALSE
4 positive  FALSE
5 positive  FALSE

In [72]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

mood_loo_controlled_results <- purrr::map_dfr(
  sort(unique(mood_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- mood_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    loo_model <- metafor::rma.mv(
      yi     = yi_aligned,
      V      = vi,
      random = ~ 1 | study_id/subscale,
      method = "REML",
      test   = "t",
      dfs    = "contain",
      data   = loo_dat
    )

    tibble::tibble(
      dropped_study = drop_study,
      k_effects_remaining = nrow(loo_dat),
      n_studies_remaining = dplyr::n_distinct(loo_dat$study_id),
      estimate = as.numeric(loo_model$b),
      se = loo_model$se,
      ci_lb = loo_model$ci.lb,
      ci_ub = loo_model$ci.ub,
      p_value = loo_model$pval,
      tau2_study = loo_model$sigma2[1],
      tau2_effect = loo_model$sigma2[2],
      direction = dplyr::case_when(
        estimate > 0 ~ "positive",
        estimate < 0 ~ "negative",
        TRUE ~ "null"
      ),
      significant = p_value < 0.05
    )
  }
)

mood_loo_controlled_results <- mood_loo_controlled_results %>%
  dplyr::left_join(study_labels_mood, by = c("dropped_study" = "study_id")) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    tau2_effect,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

mood_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1  3            Ketelhut et al. 2023 7                   2
2  8            Huttunen et al. 2004 4                   2
3 13            Epel et al. 2025     7                   2
  estimate   se        ci_lb     ci_ub    p_value   tau2_study   tau2_effect
1 0.15862964 0.1360363 -1.569876 1.887135 0.4512830 3.165982e-11 3.341059e-02
2 0.19431398 0.1942168 -2.273444 2.662072 0.4998407 3.002385e-11 7.487989e-02
3 0.09608684 0.1275921 -1.525125 1.717298 0.5890822 0.000000e+00 1.529614e-11
  direction significant
1 positive  FALSE
2 positive  FALSE
3 positive  FALSE

In [73]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## ------------------------------------------------------------
## We fix only the study level heterogeneity component
## and keep the within study effect level component estimated

tau2_grid_mood <- c(0.00, 0.05, 0.10, 0.20, 0.40)

mood_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_mood,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi     = yi_aligned,
      V      = vi,
      random = ~ 1 | study_id/subscale,
      sigma2 = c(tau2_value, NA),
      method = "REML",
      test   = "t",
      dfs    = "contain",
      data   = mood_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      tau2_effect_est = tau_model$sigma2[2],
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

mood_tau_sensitivity <- mood_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate > 0 ~ "positive",
      estimate < 0 ~ "negative",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

mood_tau_sensitivity

  tau2_study_fixed tau2_effect_est estimate  se        ci_lb       ci_ub
1 0.00             0.15505265      0.3279469 0.1363122 -0.05051644 0.7064103
2 0.05             0.08455909      0.3516102 0.1533560 -0.07417435 0.7773948
3 0.10             0.06249961      0.3553470 0.1783932 -0.13995179 0.8506458
4 0.20             0.05429159      0.3550010 0.2263369 -0.27341093 0.9834129
5 0.40             0.05376218      0.3539550 0.3020768 -0.48474463 1.1926546
  p_value    direction significant
1 0.07388612 positive  FALSE
2 0.08360156 positive  FALSE
3 0.11719163 positive  FALSE
4 0.19184981 positive  FALSE
5 0.30633232 positive  FALSE

In [74]:
## ------------------------------------------------------------
## Create study level display data for forest plots only
## ------------------------------------------------------------
## Important
## The multilevel model remains the inferential model
## The forest plot is based on one display effect per study
## created via inverse variance pooling within each study

mood_N_by_study_unique <- mood_N_by_study %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    design = dplyr::first(design),
    N_study = max(N_study, na.rm = TRUE),
    .groups = "drop"
  )

mood_N_by_study_controlled_unique <- mood_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    design = "controlled",
    N_study = max(N_study, na.rm = TRUE),
    .groups = "drop"
  )

In [75]:
## ------------------------------------------------------------
## Create study level display data for forest plots only
## ------------------------------------------------------------

mood_study_display_all <- mood_main_dat %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    yi_agg = sum(yi_aligned / vi, na.rm = TRUE) / sum(1 / vi, na.rm = TRUE),
    vi_agg = 1 / sum(1 / vi, na.rm = TRUE),
    k_effects = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::left_join(study_labels_mood, by = "study_id") %>%
  dplyr::left_join(mood_N_by_study_unique, by = "study_id") %>%
  dplyr::mutate(
    N_study = as.integer(N_study),
    study_label_n = paste0(study_label, "  (N=", N_study, ")")
  ) %>%
  dplyr::arrange(study_id)

mood_study_display_controlled <- mood_controlled_dat %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    yi_agg = sum(yi_aligned / vi, na.rm = TRUE) / sum(1 / vi, na.rm = TRUE),
    vi_agg = 1 / sum(1 / vi, na.rm = TRUE),
    k_effects = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::left_join(study_labels_mood, by = "study_id") %>%
  dplyr::left_join(mood_N_by_study_controlled_unique, by = "study_id") %>%
  dplyr::mutate(
    N_study = as.integer(N_study),
    study_label_n = paste0(study_label, "  (N=", N_study, ")")
  ) %>%
  dplyr::arrange(study_id)

mood_study_display_all
mood_study_display_controlled

  study_id yi_agg     vi_agg     k_effects study_label             design
1  3       0.10759633 0.04935994 2         Ketelhut et al. 2023    controlled
2  8       0.09042268 0.02429150 5         Huttunen et al. 2004    controlled
3 11       0.23774940 0.03854747 2         Reed et al. 2023        single_group
4 12       1.04213685 0.02340550 2         Yankouskaya et al. 2023 single_group
5 13       0.25587884 0.02926099 2         Epel et al. 2025        controlled
  N_study study_label_n
1 41      Ketelhut et al. 2023  (N=41)
2 36      Huttunen et al. 2004  (N=36)
3 13      Reed et al. 2023  (N=13)
4 32      Yankouskaya et al. 2023  (N=32)
5 70      Epel et al. 2025  (N=70)

  study_id yi_agg     vi_agg     k_effects study_label          design
1  3       0.10759633 0.04935994 2         Ketelhut et al. 2023 controlled
2  8       0.09042268 0.02429150 5         Huttunen et al. 2004 controlled
3 13       0.25587884 0.02926099 2         Epel et al. 2025     controlled
  N_study study_label_n
1 41      Ketelhut et al. 2023  (N=41)
2 36      Huttunen et al. 2004  (N=36)
3 70      Epel et al. 2025  (N=70)

In [76]:
## ============================================================
## MOOD AFFECT
## Plotting and export section aligned with Depression workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [77]:
## ------------------------------------------------------------
## Rounded helper
## ------------------------------------------------------------

round_df_2 <- function(df) {
  df %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )
}

In [78]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_mood <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [79]:
## ============================================================
## DISPLAY DATA FOR FOREST PLOTS
## Important
## The multilevel model remains the inferential model
## Forest plots use aggregated study display effects only
## ============================================================

## ------------------------------------------------------------
## Sample size tables by study
## One N per study without double counting subscales
## ------------------------------------------------------------

mood_N_by_study_unique <- mood_change_wide_study %>%
  dplyr::group_by(study_id, design) %>%
  dplyr::summarise(
    N_study = dplyr::case_when(
      design == "controlled" ~ max(n_change_Intervention + n_change_Control, na.rm = TRUE),
      design == "single_group" ~ max(n_change_SingleGroup, na.rm = TRUE),
      TRUE ~ NA_real_
    ),
    .groups = "drop"
  ) %>%
  dplyr::filter(!is.na(N_study))

Warning message:
“There were 5 warnings in `dplyr::summarise()`.
The first warning was:
ℹ In argument: `N_study = dplyr::case_when(...)`.
ℹ In group 1: `study_id = 3` `design = "controlled"`.
Caused by warning in `max()`:
! no non-missing arguments to max; returning -Inf
ℹ Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.”
Warning message:
“Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.”

In [80]:
## ------------------------------------------------------------
## Aggregate one display effect per study
## Inverse variance aggregation for display only
## ------------------------------------------------------------

mood_study_display_all <- mood_main_dat %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    yi = sum(yi_aligned / vi, na.rm = TRUE) / sum(1 / vi, na.rm = TRUE),
    vi = 1 / sum(1 / vi, na.rm = TRUE),
    k_effects = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::left_join(study_labels_mood, by = "study_id") %>%
  dplyr::left_join(mood_N_by_study_unique, by = "study_id") %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design == "controlled" ~ "Controlled",
      design == "single_group" ~ "Single group",
      TRUE ~ design
    )
  ) %>%
  dplyr::arrange(study_id)

mood_study_display_controlled <- mood_main_dat %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    yi = sum(yi_aligned / vi, na.rm = TRUE) / sum(1 / vi, na.rm = TRUE),
    vi = 1 / sum(1 / vi, na.rm = TRUE),
    k_effects = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::left_join(study_labels_mood, by = "study_id") %>%
  dplyr::left_join(
    mood_N_by_study_unique %>% dplyr::filter(design == "controlled"),
    by = "study_id"
  ) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id)

In [81]:
## ------------------------------------------------------------
## Wrap very long study labels
## ------------------------------------------------------------

mood_study_display_all <- mood_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

mood_study_display_controlled <- mood_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [82]:
## ------------------------------------------------------------
## Plot only random effects models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv models
## ------------------------------------------------------------

res_mood_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = mood_study_display_all
)

res_mood_controlled_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = mood_study_display_controlled
)

mood_study_display_all <- mood_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_mood_all_plot) / sum(weights(res_mood_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

mood_study_display_controlled <- mood_study_display_controlled %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_mood_controlled_plot) / sum(weights(res_mood_controlled_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

In [83]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Mood/Affect"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference aligned to better mood/affect", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours control", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours CWE", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Mood/Affect"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -4.65
  x_keff   <- -3.00
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_keff,   k + 1.15, "Effects", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_keff,   rows, dat$k_effects, cex = 0.88)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference aligned to better mood/affect", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours control", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours CWE", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours control", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours CWE", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [84]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = mood_study_display_all,
  model = res_mood_all_plot,
  file = file.path(graph_path, "forest_mood_affect_all_designs_journal_style.pdf"),
  outcome_title = "Mood/Affect, all designs"
)

save_forest_controlled_journal(
  dat = mood_study_display_controlled,
  model = res_mood_controlled_plot,
  file = file.path(graph_path, "forest_mood_affect_controlled_journal_style.pdf"),
  outcome_title = "Mood/Affect, controlled studies"
)

agg_record_295081300
                   2

agg_record_295081300
                   2

In [85]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

mood_total_N_all <- sum(mood_N_by_study_unique$N_study, na.rm = TRUE)

mood_total_N_controlled <- mood_N_by_study_unique %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

mood_loo_plot_all <- mood_loo_results %>%
  dplyr::left_join(
    mood_N_by_study_unique %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = mood_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot),
    model_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Drop: Petraskova Touskova et al.\n2022",
      model_label
    )
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

mood_loo_plot_controlled <- mood_loo_controlled_results %>%
  dplyr::left_join(
    mood_N_by_study_unique %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = mood_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot),
    model_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Drop: Petraskova Touskova et al.\n2022",
      model_label
    )
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [86]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

mood_tau_plot <- mood_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [87]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = mood_loo_plot_all,
  file = file.path(graph_path, "forest_mood_affect_leave_one_out_all_designs.pdf"),
  title_left = "Mood/Affect, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_mood_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = mood_loo_plot_controlled,
  file = file.path(graph_path, "forest_mood_affect_leave_one_out_controlled_only.pdf"),
  title_left = "Mood/Affect, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = as.numeric(res_mood_controlled_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = mood_tau_plot,
  file = file.path(graph_path, "forest_mood_affect_tau_sensitivity.pdf"),
  title_left = "Mood/Affect, tau sensitivity",
  xlab_text = "Pooled SMD under fixed study level tau^2 assumptions",
  refline_value = as.numeric(res_mood_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1478820846
                    2

agg_record_1478820846
                    2

agg_record_1478820846
                    2

In [88]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table_mood <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      k_effects,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_mood_effects_all <- mood_main_dat %>%
  dplyr::left_join(study_labels_mood, by = "study_id") %>%
  dplyr::transmute(
    study_id,
    study_label,
    instrument,
    subscale,
    design_type,
    valence,
    yi_aligned,
    vi,
    se = sqrt(vi),
    ci_lb = yi_aligned - 1.96 * sqrt(vi),
    ci_ub = yi_aligned + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_mood_study_display_all <- make_study_effect_table_mood(mood_study_display_all)

tab_mood_study_display_controlled <- make_study_effect_table_mood(mood_study_display_controlled)

tab_mood_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(mood_main_dat), nrow(mood_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(mood_main_dat$study_id),
    dplyr::n_distinct(mood_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_mood_main_mv$b),
    as.numeric(res_mood_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_mood_main_mv$se),
    as.numeric(res_mood_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_mood_main_mv$ci.lb),
    as.numeric(res_mood_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_mood_main_mv$ci.ub),
    as.numeric(res_mood_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_mood_main_mv$pval),
    as.numeric(res_mood_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_mood_main_mv$sigma2[1]),
    as.numeric(res_mood_controlled_mv$sigma2[1])
  ),
  tau2_effect = c(
    as.numeric(res_mood_main_mv$sigma2[2]),
    as.numeric(res_mood_controlled_mv$sigma2[2])
  )
) %>%
  round_df_2()

tab_mood_loo_all <- mood_loo_results %>%
  round_df_2()

tab_mood_loo_controlled <- mood_loo_controlled_results %>%
  round_df_2()

tab_mood_tau <- mood_tau_sensitivity %>%
  round_df_2()

tab_mood_N_by_study <- mood_N_by_study_unique %>%
  round_df_2()

tab_mood_N_by_design <- mood_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_mood_effects_all,
  file.path(table_path, "mood_affect_effect_sizes_all.csv")
)

readr::write_csv(
  tab_mood_study_display_all,
  file.path(table_path, "mood_affect_study_display_main.csv")
)

readr::write_csv(
  tab_mood_study_display_controlled,
  file.path(table_path, "mood_affect_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_mood_model_compare,
  file.path(table_path, "mood_affect_model_comparison.csv")
)

readr::write_csv(
  tab_mood_loo_all,
  file.path(table_path, "mood_affect_leave_one_out_all.csv")
)

readr::write_csv(
  tab_mood_loo_controlled,
  file.path(table_path, "mood_affect_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_mood_tau,
  file.path(table_path, "mood_affect_tau_sensitivity.csv")
)

readr::write_csv(
  tab_mood_N_by_study,
  file.path(table_path, "mood_affect_sample_size_by_study.csv")
)

readr::write_csv(
  tab_mood_N_by_design,
  file.path(table_path, "mood_affect_sample_size_by_design.csv")
)

In [89]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved mood/affect PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved mood/affect tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "mood_affect.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "mood_affect.*csv$", full.names = TRUE)

Saved mood/affect PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved mood/affect tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_mood_affect_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_mood_affect_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_mood_affect_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_mood_affect_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_mood_affect_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/mood_affect_tau_sensitivity.csv"

#### **Overall interpretation**
The main multilevel model including all study designs suggested a small-to-moderate improvement in mood and affect associated with CWE (g ≈ 0.36, with positive values indicating better mood or affect after alignment of scale direction), but with wide uncertainty and no statistically reliable effect under Hartung-Knapp-style inference. When the analysis was restricted to controlled studies only, the pooled estimate attenuated to around g ≈ 0.15. This pattern suggests that part of the larger apparent benefit in the full synthesis may be attributable to uncontrolled single-group studies rather than to comparative treatment effects alone.

The leave-one-out results suggest that in both the all-designs analysis and the controlled-only analysis, the pooled estimate remained positive in every single model. That means the overall conclusion was not reversed by omission of any one study. However, the magnitude varied:
* all-designs models ranged from about 0.17 to 0.44
* controlled-only models ranged from about 0.10 to 0.19

This indicates that the mood/affect signal is directionally stable, but its magnitude is sensitive to the inclusion of particular studies, especially the single-group studies. In particular, omitting Yankouskaya et al. (2023) reduced the all-designs estimate most noticeably, from about 0.36 to about 0.17, suggesting that this study contributes importantly to the overall magnitude of the pooled effect. At the same time, the direction of effect remained positive throughout, which argues against the result being driven by a single contradictory study.

The controlled-only leave-one-out results should be interpreted more cautiously because they are based on only three studies. Once one study is removed, inference rests on just two studies and the confidence intervals become extremely wide. Still, the pooled estimate remained positive in all such models, suggesting that the controlled evidence, while sparse, is at least directionally consistent.

The tau sensitivity analysis strengthens that interpretation further. Across a broad range of assumed study-level heterogeneity values, the pooled estimate remained consistently positive, roughly between 0.33 and 0.36, while the uncertainty widened as heterogeneity was increased. Thus, the direction and approximate magnitude of the pooled association were quite robust to alternative heterogeneity assumptions. What changed was primarily the precision, not the substantive conclusion.

All in all, CWE showed a consistent tendency toward improved mood and affect across analyses, but the magnitude of this association was modest and depended partly on study design. Effects were attenuated when analyses were restricted to controlled studies, suggesting that uncontrolled within-person improvement may contribute to the larger effects observed in the overall synthesis. Leave-one-out and heterogeneity sensitivity analyses showed that the direction of effect was stable, although the evidence remains imprecise and based on a small and methodologically mixed literature. Overall, the findings suggest a possible signal toward benefit for mood and affect, but current evidence remains limited, heterogeneous, and partly design-dependent.

## **Anxiety**
[Back to Table of Content](#table-of-content)

In [90]:
## ------------------------------------------------------------
## Filter mental data to anxiety domain
##
## NOTE
## For at least one trial, multiple intervention arms were
## manually pooled into one Intervention group before import.
## Therefore, each study contributes at most one Intervention
## and one Control group per timepoint in this pipeline.
## ------------------------------------------------------------

mental_anx <- mental %>%
  dplyr::filter(instrument_domain == "Anxiety")

## Quick structural check
mental_anx %>%
  dplyr::distinct(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id instrument group_harmonised timepoint_label_harmonised
1  1        GAD-7      Control          Follow-Up
2  1        GAD-7      Control          Post
3  1        GAD-7      Control          Pre
4  1        GAD-7      Intervention     Follow-Up
5  1        GAD-7      Intervention     Post
6  1        GAD-7      Intervention     Pre
7  2        BSI        Control          Follow-Up
8  2        BSI        Control          Pre
9  2        BSI        Intervention     Follow-Up
10 2        BSI        Intervention     Pre
11 4        GAD-7      Control          Post
12 4        GAD-7      Control          Pre
13 4        GAD-7      Intervention     Post
14 4        GAD-7      Intervention     Pre
15 9        PSWQ       Intervention     Post
16 9        GAD-7      Intervention     Post
17 9        PSWQ       Intervention     Post-Immersion
18 9        GAD-7      Intervention     Post-Immersion
19 9        PSWQ       Intervention     Pre
20 9        GAD-7      Intervention     Pre

In [91]:
## ------------------------------------------------------------
## Reconstruct change SD from 95 percent CI if available
## For rows with change_mean + CI but missing change_sd
## ------------------------------------------------------------

mental_anx <- mental_anx %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [92]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## Formulas follow Wan et al. 2014 and Luo et al. 2018
## mean approx equals (Q1 + median + Q3) / 3
## SD   approx equals (Q3 - Q1) / 1.35 for larger samples
## ------------------------------------------------------------

mental_anx <- mental_anx %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [93]:
## ------------------------------------------------------------
## Select Pre and Post data and prefer ITT over PP
## Primary analysis uses Pre versus Post
## Follow-Up is not included in this primary synthesis
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

anx_prepost <- mental_anx %>%
  dplyr::filter(timepoint_label_harmonised %in% c("Pre", "Post")) %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels),
    group_harmonised = dplyr::case_when(
      study_id == 9 & group_harmonised == "Intervention" ~ "SingleGroup",
      TRUE ~ group_harmonised
    )
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
anx_prepost %>%
  dplyr::count(study_id, group_harmonised, timepoint_label_harmonised)

   study_id group_harmonised timepoint_label_harmonised n
1  1        Control          Post                       1
2  1        Control          Pre                        1
3  1        Intervention     Post                       1
4  1        Intervention     Pre                        1
5  2        Control          Pre                        1
6  2        Intervention     Pre                        1
7  4        Control          Post                       1
8  4        Control          Pre                        1
9  4        Intervention     Post                       1
10 4        Intervention     Pre                        1
11 9        SingleGroup      Post                       1
12 9        SingleGroup      Pre                        1

In [94]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## Use reported change_mean and change_sd if present
## Otherwise derive them from Pre and Post means and SDs
## assuming pre post correlation r_change
## ------------------------------------------------------------

r_change <- 0.5

anx_wide <- anx_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

anx_wide %>%
  dplyr::select(
    study_id,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id group_harmonised n_change change_mean_calc change_sd_calc
1 1        Control           41      -2.980            4.200036
2 1        Intervention      37      -1.800            4.390854
3 2        Control          718          NA                  NA
4 2        Intervention     798          NA                  NA
5 4        Control           13       1.462            5.324627
6 4        Intervention      11      -2.455            3.065340
7 9        SingleGroup       13       1.460           15.420788

In [95]:
## ------------------------------------------------------------
## Classify study designs
## controlled    = Intervention plus Control present
## single_group  = one pooled group only
## other         = ignored in primary meta-analysis
## ------------------------------------------------------------

anx_wide <- anx_wide %>%
  dplyr::group_by(study_id) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

anx_wide %>%
  dplyr::distinct(study_id, design)

  study_id design
1 1        controlled
2 2        controlled
3 4        controlled
4 9        single_group

In [96]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

anx_change_groups <- anx_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

anx_change_groups %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id design       group_harmonised change_mean_calc change_sd_calc
1 1        controlled   Control          -2.980            4.200036
2 1        controlled   Intervention     -1.800            4.390854
3 4        controlled   Control           1.462            5.324627
4 4        controlled   Intervention     -2.455            3.065340
5 9        single_group SingleGroup       1.460           15.420788
  n_change
1 41
2 37
3 13
4 11
5 13

In [97]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

anx_change_wide_study <- anx_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [98]:
## ------------------------------------------------------------
## EFFECT SIZES
## Controlled studies
## Standardized mean difference of change scores
## ------------------------------------------------------------

es_anx_controlled <- anx_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .
  ) %>%
  dplyr::mutate(
    outcome_domain = "Anxiety",
    design_type = "controlled"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_anx_controlled

  study_id outcome_domain design_type yi         vi
1 1        Anxiety        controlled   0.2722394 0.05189236
2 4        Anxiety        controlled  -0.8512530 0.18292866

In [99]:
## ------------------------------------------------------------
## EFFECT SIZES
## Single-group pre post studies
## Standardized mean change based on change score SD
## ------------------------------------------------------------

es_anx_single <- anx_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Anxiety",
    design_type = "single_group"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_anx_single

  study_id outcome_domain design_type  yi         vi
1 9        Anxiety        single_group 0.08910813 0.06844487

In [100]:
## ------------------------------------------------------------
## Combine all analyzable anxiety effect sizes
## ------------------------------------------------------------

es_anx_all <- dplyr::bind_rows(
  es_anx_controlled,
  es_anx_single
) %>%
  dplyr::arrange(study_id) %>%
  dplyr::mutate(
    effect_id = paste0("anx_", dplyr::row_number())
  )

es_anx_all

  study_id outcome_domain design_type  yi          vi         effect_id
1 1        Anxiety        controlled    0.27223943 0.05189236 anx_1
2 4        Anxiety        controlled   -0.85125301 0.18292866 anx_2
3 9        Anxiety        single_group  0.08910813 0.06844487 anx_3

In [101]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## This avoids counting studies with unusable anxiety data
## ------------------------------------------------------------

anx_N_by_study_raw <- anx_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled" ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(study_id, design, N_study)

anx_N_by_study <- es_anx_all %>%
  dplyr::distinct(study_id, design_type) %>%
  dplyr::left_join(
    anx_N_by_study_raw,
    by = "study_id"
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled" ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, design, N_study) %>%
  dplyr::distinct()

k_anx <- nrow(anx_N_by_study)
N_anx_total <- sum(anx_N_by_study$N_study, na.rm = TRUE)

anx_N_by_design <- anx_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nAnxiety meta-analysis contributing studies\n")
cat(" k studies =", k_anx, "\n")
cat(" total N   =", N_anx_total, "\n")
print(anx_N_by_design)

Anxiety meta-analysis contributing studies
 k studies = 3
 total N   = 115
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          2      102
2 single_group        1       13

In [102]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_anx <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [103]:
## ------------------------------------------------------------
## Main analysis datasets
## Important
## Main inference stays at the effect size level with rma.mv
## For anxiety each study contributes one effect only
## so the multilevel structure reduces to a study level model
## ------------------------------------------------------------

anx_main_dat <- es_anx_all %>%
  dplyr::arrange(study_id)

anx_controlled_dat <- es_anx_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id)

cat("\nAnxiety main dataset\n")
cat(" k effects =", nrow(anx_main_dat), "\n")
cat(" studies =", paste(sort(unique(anx_main_dat$study_id)), collapse = ", "), "\n")

cat("\nAnxiety controlled only dataset\n")
cat(" k effects =", nrow(anx_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(anx_controlled_dat$study_id)), collapse = ", "), "\n")

Anxiety main dataset
 k effects = 3
 studies = 1, 4, 9

Anxiety controlled only dataset
 k effects = 2
 studies = 1, 4

In [104]:
## ============================================================
## ANXIETY
## MAIN MODEL AND CONTROLLED-ONLY SENSITIVITY
## Multilevel random-effects framework as default
## Hartung-Knapp-like inference via t-distribution
## ============================================================

res_anx_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = anx_main_dat
)

print(res_anx_main_mv)
broom::tidy(res_anx_main_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.1785  0.4225      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 5.4143, p-val = 0.0667

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.0728  0.2994  -0.2433   2  0.8304  -1.3610  1.2153

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate    std.error statistic  p.value
1 overall summary -0.07284823 0.2993823 -0.2433284 0.8304325

In [105]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## ------------------------------------------------------------

res_anx_controlled_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = anx_controlled_dat
)

print(res_anx_controlled_mv)
broom::tidy(res_anx_controlled_mv)

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.5137  0.7167      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 5.3753, p-val = 0.0204

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.2312  0.5587  -0.4138   1  0.7502  -7.3303  6.8679

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic  p.value
1 overall summary -0.2311903 0.558711  -0.4137922 0.750229

In [106]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

anx_model_compare <- dplyr::bind_rows(
  broom::tidy(res_anx_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  broom::tidy(res_anx_controlled_mv) %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

anx_model_compare

  model            term    estimate    std.error statistic  p.value
1 main_all_designs overall -0.07284823 0.2993823 -0.2433284 0.8304325
2 controlled_only  overall -0.23119029 0.5587110 -0.4137922 0.7502290

In [107]:
## ------------------------------------------------------------
## Leave one out by study
## This is the correct sensitivity unit
## ------------------------------------------------------------

anx_loo_results <- purrr::map_dfr(
  sort(unique(anx_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- anx_main_dat %>%
      dplyr::filter(study_id != drop_study)

    loo_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = loo_dat
    )

    tibble::tibble(
      dropped_study = drop_study,
      k_effects_remaining = nrow(loo_dat),
      n_studies_remaining = dplyr::n_distinct(loo_dat$study_id),
      estimate = as.numeric(loo_model$b),
      se = loo_model$se,
      ci_lb = loo_model$ci.lb,
      ci_ub = loo_model$ci.ub,
      p_value = loo_model$pval,
      tau2_study = loo_model$sigma2[1],
      direction = dplyr::case_when(
        estimate < 0 ~ "negative_better_for_cwe",
        estimate > 0 ~ "positive_worse_for_cwe",
        TRUE ~ "null"
      ),
      significant = p_value < 0.05
    )
  }
)

anx_loo_results <- anx_loo_results %>%
  dplyr::left_join(
    study_labels_anx,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

anx_loo_results

  dropped_study study_label             k_effects_remaining n_studies_remaining
1 4             Slezakova et al. 2025   2                   2
2 1             Blades et al. 2024      2                   2
3 9             Knill-Jones et al. 2024 2                   2
  estimate   se        ci_lb     ci_ub    p_value   tau2_study
1  0.1932687 0.1717996 -1.989652 2.376190 0.4626044 6.294821e-12
2 -0.3202001 0.4662233 -6.244129 5.603729 0.6168766 3.164525e-01
3 -0.2311903 0.5587110 -7.330287 6.867906 0.7502290 5.137071e-01
  direction               significant
1 positive_worse_for_cwe  FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE

In [108]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## With only two controlled studies, dropping one study leaves
## only one effect. In that case, meta-analysis is not possible
## and we report the remaining study descriptively.
## ------------------------------------------------------------

anx_loo_controlled_results <- purrr::map_dfr(
  sort(unique(anx_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- anx_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

anx_loo_controlled_results <- anx_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_anx,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

anx_loo_controlled_results

  dropped_study study_label           k_effects_remaining n_studies_remaining
1 1             Blades et al. 2024    1                   1
2 4             Slezakova et al. 2025 1                   1
  result_type            estimate   se        ci_lb      ci_ub       p_value
1 single_study_remaining -0.8512530 0.4277016 -1.6895481 -0.01295786 NA
2 single_study_remaining  0.2722394 0.2277990 -0.1742465  0.71872538 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         positive_worse_for_cwe  NA

In [109]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## For anxiety there is only one heterogeneity component
## because there is one effect per study in this domain
## ------------------------------------------------------------

tau2_grid_anx <- c(0.00, 0.05, 0.10, 0.20, 0.40)

anx_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_anx,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = anx_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

anx_tau_sensitivity <- anx_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

anx_tau_sensitivity

  tau2_study_fixed estimate    se        ci_lb      ci_ub     p_value
1 0.00              0.04815189 0.1594194 -0.6377742 0.7340780 0.7911323
2 0.05             -0.01021785 0.2105838 -0.9162868 0.8958511 0.9657103
3 0.10             -0.04281584 0.2495735 -1.1166440 1.0310123 0.8795744
4 0.20             -0.07861864 0.3114893 -1.4188488 1.2616115 0.8243053
5 0.40             -0.11011496 0.4061179 -1.8574991 1.6372692 0.8117043
  direction               significant
1 positive_worse_for_cwe  FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [110]:
## ============================================================
## ANXIETY
## Plotting and export section aligned with Depression workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [111]:
## Rounded helper
## ------------------------------------------------------------

round_df_2 <- function(df) {
  df %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )
}

In [112]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Anxiety has one effect per study so no within study
## aggregation is needed for the main display forest plot
## ============================================================

anx_study_display_all <- anx_main_dat %>%
  dplyr::left_join(study_labels_anx, by = "study_id") %>%
  dplyr::left_join(anx_N_by_study, by = "study_id") %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled" ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id)

anx_study_display_controlled <- anx_controlled_dat %>%
  dplyr::left_join(study_labels_anx, by = "study_id") %>%
  dplyr::left_join(
    anx_N_by_study %>% dplyr::filter(design == "controlled"),
    by = "study_id"
  ) %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id)

In [113]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

anx_study_display_all <- anx_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

anx_study_display_controlled <- anx_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [114]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_anx_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = anx_study_display_all
)

res_anx_controlled_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = anx_study_display_controlled
)

anx_study_display_all <- anx_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_anx_all_plot) / sum(weights(res_anx_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

anx_study_display_controlled <- anx_study_display_controlled %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_anx_controlled_plot) / sum(weights(res_anx_controlled_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

In [115]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Anxiety"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for anxiety symptoms", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Anxiety"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for anxiety symptoms", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [116]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = anx_study_display_all,
  model = res_anx_all_plot,
  file = file.path(graph_path, "forest_anxiety_all_designs_journal_style.pdf"),
  outcome_title = "Anxiety, all designs"
)

save_forest_controlled_journal(
  dat = anx_study_display_controlled,
  model = res_anx_controlled_plot,
  file = file.path(graph_path, "forest_anxiety_controlled_journal_style.pdf"),
  outcome_title = "Anxiety, controlled studies"
)

agg_record_2058614161
                    2

agg_record_2058614161
                    2

In [117]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

anx_total_N_all <- sum(anx_N_by_study$N_study, na.rm = TRUE)

anx_total_N_controlled <- anx_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

anx_loo_plot_all <- anx_loo_results %>%
  dplyr::left_join(
    anx_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = anx_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

anx_loo_plot_controlled <- anx_loo_controlled_results %>%
  dplyr::left_join(
    anx_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = anx_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(seTE),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [118]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

anx_tau_plot <- anx_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [119]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = anx_loo_plot_all,
  file = file.path(graph_path, "forest_anxiety_leave_one_out_all_designs.pdf"),
  title_left = "Anxiety, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_anx_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = anx_loo_plot_controlled,
  file = file.path(graph_path, "forest_anxiety_leave_one_out_controlled_only.pdf"),
  title_left = "Anxiety, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = as.numeric(res_anx_controlled_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = anx_tau_plot,
  file = file.path(graph_path, "forest_anxiety_tau_sensitivity.pdf"),
  title_left = "Anxiety, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_anx_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1390292954
                    2

agg_record_1390292954
                    2

agg_record_1390292954
                    2

In [120]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_anx_study_display_all <- make_study_effect_table(anx_study_display_all)

tab_anx_study_display_controlled <- make_study_effect_table(anx_study_display_controlled)

tab_anx_effect_sizes_all <- es_anx_all %>%
  dplyr::left_join(study_labels_anx, by = "study_id") %>%
  dplyr::left_join(anx_N_by_study, by = "study_id") %>%
  dplyr::transmute(
    study_id,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_anx_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(anx_main_dat), nrow(anx_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(anx_main_dat$study_id),
    dplyr::n_distinct(anx_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_anx_main_mv$b),
    as.numeric(res_anx_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_anx_main_mv$se),
    as.numeric(res_anx_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_anx_main_mv$ci.lb),
    as.numeric(res_anx_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_anx_main_mv$ci.ub),
    as.numeric(res_anx_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_anx_main_mv$pval),
    as.numeric(res_anx_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_anx_main_mv$sigma2),
    as.numeric(res_anx_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_anx_loo_all <- anx_loo_results %>%
  round_df_2()

tab_anx_loo_controlled <- anx_loo_controlled_results %>%
  round_df_2()

tab_anx_tau <- anx_tau_sensitivity %>%
  round_df_2()

tab_anx_N_by_study <- anx_N_by_study %>%
  round_df_2()

tab_anx_N_by_design <- anx_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_anx_effect_sizes_all,
  file.path(table_path, "anxiety_effect_sizes_all.csv")
)

readr::write_csv(
  tab_anx_study_display_all,
  file.path(table_path, "anxiety_study_display_main.csv")
)

readr::write_csv(
  tab_anx_study_display_controlled,
  file.path(table_path, "anxiety_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_anx_model_compare,
  file.path(table_path, "anxiety_model_comparison.csv")
)

readr::write_csv(
  tab_anx_loo_all,
  file.path(table_path, "anxiety_leave_one_out_all.csv")
)

readr::write_csv(
  tab_anx_loo_controlled,
  file.path(table_path, "anxiety_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_anx_tau,
  file.path(table_path, "anxiety_tau_sensitivity.csv")
)

readr::write_csv(
  tab_anx_N_by_study,
  file.path(table_path, "anxiety_sample_size_by_study.csv")
)

readr::write_csv(
  tab_anx_N_by_design,
  file.path(table_path, "anxiety_sample_size_by_design.csv")
)

In [121]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved anxiety PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved anxiety tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "anxiety.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "anxiety.*csv$", full.names = TRUE)

Saved anxiety PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved anxiety tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_controlled_only.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_leave_one_out_all_designs.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_leave_one_out_controlled_only.pdf"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_main_all_designs.pdf"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_anxiety_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/anxiety_tau_sensitivity.csv"

#### **Overall interpretation** 
The main multilevel model including all study designs suggested essentially no clear overall association between CWE and anxiety symptoms (g ≈ −0.07, with negative values indicating greater anxiety reduction and positive values indicating less reduction or worsening), and the estimate was highly imprecise under Hartung-Knapp-style inference. When the analysis was restricted to controlled studies only, the pooled estimate shifted somewhat further in the beneficial direction to around g ≈ −0.23, but uncertainty became extremely large. This pattern does not suggest a robust anxiety benefit. Instead, it indicates that the available evidence is sparse, internally inconsistent, and too imprecise to support a stable conclusion.

The leave-one-out results reinforce that interpretation. In the all-designs analysis, omitting one study at a time did not merely change the magnitude of the pooled estimate, but in one case also reversed its direction:
* all-designs models ranged from about −0.32 to 0.19

More specifically, dropping Slezakova et al. (2025) shifted the pooled estimate to about g ≈ 0.19, whereas dropping Blades et al. (2024) or Knill-Jones et al. (2024) yielded negative pooled estimates of about g ≈ −0.32 and g ≈ −0.23, respectively. This means the anxiety result is not directionally stable. The pooled conclusion depends materially on which study is included, which is a strong sign of fragility rather than robustness.

The controlled-only leave-one-out results are even more limited, because only two controlled studies contributed to that analysis. Once one study is removed, no meta-analytic synthesis is possible and the result reduces to the remaining single study. Those two remaining single-study estimates pointed in opposite directions:
* Blades et al. (2024) alone suggested a small adverse or null-leaning effect (g ≈ 0.27)
* Slezakova et al. (2025) alone suggested a larger beneficial effect (g ≈ −0.85)

That is important because it shows that the controlled evidence is not only sparse, but also conflicting at the study level. So unlike mood and affect, there is no clear directional consistency even within the stronger-design subset.

The tau sensitivity analysis points in the same direction. Across the range of fixed study-level heterogeneity assumptions, the pooled estimate remained close to zero overall, ranging roughly from g ≈ 0.05 at tau² = 0 to g ≈ −0.11 at tau² = 0.40. As heterogeneity assumptions increased, uncertainty widened further, but the substantive pattern did not resolve into a consistent signal. In other words, the conclusion was not that CWE reliably reduced anxiety under alternative heterogeneity assumptions, but rather that the pooled estimate stayed small, unstable, and compatible with benefit, no effect, or harm.

All in all, the anxiety findings do not show a consistent signal toward benefit. The main pooled estimate was close to null, the controlled-only estimate was somewhat more negative but extremely imprecise, the leave-one-out analyses showed directional instability, and the controlled evidence reduced to two contradictory single-study results when examined closely. Taken together, this suggests that the current evidence base for anxiety is too sparse and inconsistent to support a reliable conclusion about whether CWE reduces anxiety symptoms. At present, the most defensible interpretation is that evidence for an anxiety effect is limited, unstable, and strongly dependent on study inclusion and design.

## **Perceived Stress**
[Back to Table of Content](#table-of-content)

In [122]:
## ------------------------------------------------------------
## Filter mental data to perceived stress domain
## ------------------------------------------------------------

mental_stress <- mental %>%
  dplyr::filter(instrument_domain == "Perceived Stress")

## Quick structural check
mental_stress %>%
  dplyr::distinct(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id instrument group_harmonised timepoint_label_harmonised
1   1       PSS        Control          Follow-Up
2   1       PSS        Control          Post
3   1       PSS        Control          Pre
4   1       PSS        Intervention     Follow-Up
5   1       PSS        Intervention     Post
6   1       PSS        Intervention     Pre
7   3       PSS        Control          Post
8   3       PSS        Control          Pre
9   3       PSS        Intervention     Post
10  3       PSS        Intervention     Pre
11  5       PSS        SingleGroup      Post
12  5       PSS        SingleGroup      Pre
13 13       PSS        Control          Follow-Up
14 13       PSS        Control          Post
15 13       PSS        Control          Pre
16 13       PSS        Intervention     Follow-Up
17 13       PSS        Intervention     Post
18 13       PSS        Intervention     Pre

In [123]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_stress <- mental_stress %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [124]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_stress <- mental_stress %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [125]:
## ------------------------------------------------------------
## Select Pre and Post data and prefer ITT over PP
## Follow up is not part of the primary synthesis
##
## If a perceived stress study is single group only
## recode it below in the same way as for anxiety
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

stress_prepost <- mental_stress %>%
  dplyr::filter(timepoint_label_harmonised %in% c("Pre", "Post")) %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels),

    group_harmonised = dplyr::case_when(
      ## Example for a single group study
      ## study_id == XX & group_harmonised == "Intervention" ~ "SingleGroup",
      TRUE ~ group_harmonised
    )
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
stress_prepost %>%
  dplyr::count(study_id, group_harmonised, timepoint_label_harmonised)

   study_id group_harmonised timepoint_label_harmonised n
1   1       Control          Post                       1
2   1       Control          Pre                        1
3   1       Intervention     Post                       1
4   1       Intervention     Pre                        1
5   3       Control          Post                       1
6   3       Control          Pre                        1
7   3       Intervention     Post                       1
8   3       Intervention     Pre                        1
9   5       SingleGroup      Post                       1
10  5       SingleGroup      Pre                        1
11 13       Control          Post                       1
12 13       Control          Pre                        1
13 13       Intervention     Post                       1
14 13       Intervention     Pre                        1

In [126]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

stress_wide <- stress_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

stress_wide %>%
  dplyr::select(
    study_id,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id group_harmonised n_change change_mean_calc change_sd_calc
1  1       Control          41       -5.10            5.720568
2  1       Intervention     37       -3.88            5.499282
3  3       Control          20       -2.90            4.651881
4  3       Intervention     21       -1.70            4.331282
5  5       SingleGroup      29       -6.79            4.952131
6 13       Control          36       -2.83            4.420441
7 13       Intervention     34       -4.55            5.816451

In [127]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

stress_wide <- stress_wide %>%
  dplyr::group_by(study_id) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

stress_wide %>%
  dplyr::distinct(study_id, design)

  study_id design
1  1       controlled
2  3       controlled
3  5       single_group
4 13       controlled

In [128]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

stress_change_groups <- stress_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

stress_change_groups %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id design       group_harmonised change_mean_calc change_sd_calc
1  1       controlled   Control          -5.10            5.720568
2  1       controlled   Intervention     -3.88            5.499282
3  3       controlled   Control          -2.90            4.651881
4  3       controlled   Intervention     -1.70            4.331282
5  5       single_group SingleGroup      -6.79            4.952131
6 13       controlled   Control          -2.83            4.420441
7 13       controlled   Intervention     -4.55            5.816451
  n_change
1 41
2 37
3 20
4 21
5 29
6 36
7 34

In [129]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

stress_change_wide_study <- stress_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [130]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
## ------------------------------------------------------------

es_stress_controlled <- stress_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .
  ) %>%
  dplyr::mutate(
    outcome_domain = "Perceived Stress",
    design_type = "controlled"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_stress_controlled

  study_id outcome_domain   design_type yi         vi
1  1       Perceived Stress controlled   0.2150524 0.05171373
2  3       Perceived Stress controlled   0.2620629 0.09845657
3 13       Perceived Stress controlled  -0.3305739 0.05797011

In [131]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_stress_single <- stress_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Perceived Stress",
    design_type = "single_group"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_stress_single

  study_id outcome_domain   design_type  yi        vi
1 5        Perceived Stress single_group -1.335358 0.06345164

In [132]:
## ------------------------------------------------------------
## Combine all analyzable perceived stress effect sizes
## ------------------------------------------------------------

es_stress_all <- dplyr::bind_rows(
  es_stress_controlled,
  es_stress_single
) %>%
  dplyr::arrange(study_id) %>%
  dplyr::mutate(
    effect_id = paste0("stress_", dplyr::row_number())
  )

es_stress_all

  study_id outcome_domain   design_type  yi         vi         effect_id
1  1       Perceived Stress controlled    0.2150524 0.05171373 stress_1
2  3       Perceived Stress controlled    0.2620629 0.09845657 stress_2
3  5       Perceived Stress single_group -1.3353584 0.06345164 stress_3
4 13       Perceived Stress controlled   -0.3305739 0.05797011 stress_4

In [133]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

stress_N_by_study_raw <- stress_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled" ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(study_id, design, N_study)

stress_N_by_study <- es_stress_all %>%
  dplyr::distinct(study_id, design_type) %>%
  dplyr::left_join(
    stress_N_by_study_raw,
    by = "study_id"
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled" ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, design, N_study) %>%
  dplyr::distinct()

k_stress <- nrow(stress_N_by_study)
N_stress_total <- sum(stress_N_by_study$N_study, na.rm = TRUE)

stress_N_by_design <- stress_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nPerceived stress meta analysis contributing studies\n")
cat(" k studies =", k_stress, "\n")
cat(" total N   =", N_stress_total, "\n")
print(stress_N_by_design)

Perceived stress meta analysis contributing studies
 k studies = 4
 total N   = 218
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          3      189
2 single_group        1       29

In [134]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_stress <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [135]:
## ------------------------------------------------------------
## Main analysis datasets
## For perceived stress I keep the same framework as anxiety
## If each study contributes one effect only
## the model reduces to a study level random effects model
## ------------------------------------------------------------

stress_main_dat <- es_stress_all %>%
  dplyr::arrange(study_id)

stress_controlled_dat <- es_stress_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id)

cat("\nPerceived stress main dataset\n")
cat(" k effects =", nrow(stress_main_dat), "\n")
cat(" studies =", paste(sort(unique(stress_main_dat$study_id)), collapse = ", "), "\n")

cat("\nPerceived stress controlled only dataset\n")
cat(" k effects =", nrow(stress_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(stress_controlled_dat$study_id)), collapse = ", "), "\n")

Perceived stress main dataset
 k effects = 4
 studies = 1, 3, 5, 13

Perceived stress controlled only dataset
 k effects = 3
 studies = 1, 3, 13

In [136]:
## ============================================================
## PERCEIVED STRESS
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================
res_stress_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = stress_main_dat
)

print(res_stress_main_mv)
broom::tidy(res_stress_main_mv)

Multivariate Meta-Analysis Model (k = 4; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.4835  0.6954      4     no  study_id

Test for Heterogeneity:
Q(df = 3) = 25.2267, p-val < .0001

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.3029  0.3711  -0.8163   3  0.4741  -1.4839  0.8781

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic  p.value
1 overall summary -0.3029301 0.3710959 -0.8163121 0.4741122

In [137]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## ------------------------------------------------------------

res_stress_controlled_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = stress_controlled_dat
)

print(res_stress_controlled_mv)
broom::tidy(res_stress_controlled_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0494  0.2223      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 3.4502, p-val = 0.1782

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.0316  0.1962  0.1610   2  0.8869  -0.8128  0.8760

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary 0.03159613 0.196249  0.1610002 0.8868863

In [138]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

stress_model_compare <- dplyr::bind_rows(
  broom::tidy(res_stress_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  broom::tidy(res_stress_controlled_mv) %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

stress_model_compare

  model            term    estimate    std.error statistic  p.value
1 main_all_designs overall -0.30293008 0.3710959 -0.8163121 0.4741122
2 controlled_only  overall  0.03159613 0.1962490  0.1610002 0.8868863

In [139]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

stress_loo_results <- purrr::map_dfr(
  sort(unique(stress_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- stress_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

stress_loo_results <- stress_loo_results %>%
  dplyr::left_join(
    study_labels_stress,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

stress_loo_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1  3            Ketelhut et al. 2023 3                   3
2  1            Blades et al. 2024   3                   3
3 13            Epel et al. 2025     3                   3
4  5            Faid et al 2022      3                   3
  result_type   estimate    se        ci_lb      ci_ub     p_value   tau2_study
1 meta_analytic -0.47874149 0.4533203 -2.4292213 1.4717383 0.4016629 0.55882336
2 meta_analytic -0.48047384 0.4630425 -2.4727851 1.5118374 0.4084305 0.57042305
3 meta_analytic -0.29114977 0.5268120 -2.5578390 1.9755395 0.6360145 0.76185286
4 meta_analytic  0.03159613 0.1962490 -0.8127952 0.8759875 0.8868863 0.04940843
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 positive_worse_for_cwe  FALSE

In [140]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

stress_loo_controlled_results <- purrr::map_dfr(
  sort(unique(stress_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- stress_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

stress_loo_controlled_results <- stress_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_stress,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

stress_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1  1            Blades et al. 2024   2                   2
2  3            Ketelhut et al. 2023 2                   2
3 13            Epel et al. 2025     2                   2
  result_type   estimate    se        ci_lb     ci_ub    p_value   tau2_study
1 meta_analytic -0.06841342 0.2943430 -3.808396 3.671569 0.8546134 9.739581e-02
2 meta_analytic -0.05202751 0.2727529 -3.517682 3.413627 0.8800065 9.401212e-02
3 meta_analytic  0.23124129 0.1841337 -2.108399 2.570882 0.4281082 5.003984e-12
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 positive_worse_for_cwe  FALSE

In [141]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_stress <- c(0.00, 0.05, 0.10, 0.20, 0.40)

stress_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_stress,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = stress_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

stress_tau_sensitivity <- stress_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

stress_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb      ci_ub      p_value
1 0.00             -0.3188190 0.1264868 -0.7213563 0.08371836 0.08613351
2 0.05             -0.3161464 0.1698980 -0.8568376 0.22454480 0.15970294
3 0.10             -0.3124931 0.2037908 -0.9610464 0.33606023 0.22271767
4 0.20             -0.3079409 0.2582375 -1.1297677 0.51388600 0.31879895
5 0.40             -0.3038488 0.3417679 -1.3915068 0.78380922 0.43946748
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [142]:
## ============================================================
## PERCEIVED STRESS
## Plotting and export section aligned with Depression workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [143]:
## Rounded helper
## ------------------------------------------------------------

round_df_2 <- function(df) {
  df %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )
}

In [144]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Perceived stress has one effect per study in the current
## analyzable dataset so no within study aggregation is needed
## ============================================================

stress_study_display_all <- stress_main_dat %>%
  dplyr::left_join(study_labels_stress, by = "study_id") %>%
  dplyr::left_join(stress_N_by_study, by = "study_id") %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled" ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id)

stress_study_display_controlled <- stress_controlled_dat %>%
  dplyr::left_join(study_labels_stress, by = "study_id") %>%
  dplyr::left_join(
    stress_N_by_study %>% dplyr::filter(design == "controlled"),
    by = "study_id"
  ) %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id)

In [145]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

stress_study_display_all <- stress_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

stress_study_display_controlled <- stress_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [146]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_stress_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = stress_study_display_all
)

res_stress_controlled_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = stress_study_display_controlled
)

stress_study_display_all <- stress_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_stress_all_plot) / sum(weights(res_stress_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

stress_study_display_controlled <- stress_study_display_controlled %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_stress_controlled_plot) / sum(weights(res_stress_controlled_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

In [147]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Perceived Stress"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for perceived stress", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Perceived Stress"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for perceived stress", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [148]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = stress_study_display_all,
  model = res_stress_all_plot,
  file = file.path(graph_path, "forest_perceived_stress_all_designs_journal_style.pdf"),
  outcome_title = "Perceived stress, all designs"
)

save_forest_controlled_journal(
  dat = stress_study_display_controlled,
  model = res_stress_controlled_plot,
  file = file.path(graph_path, "forest_perceived_stress_controlled_journal_style.pdf"),
  outcome_title = "Perceived stress, controlled studies"
)

agg_record_502682422
                   2

agg_record_502682422
                   2

In [149]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

stress_total_N_all <- sum(stress_N_by_study$N_study, na.rm = TRUE)

stress_total_N_controlled <- stress_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

stress_loo_plot_all <- stress_loo_results %>%
  dplyr::left_join(
    stress_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = stress_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(seTE),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

stress_loo_plot_controlled <- stress_loo_controlled_results %>%
  dplyr::left_join(
    stress_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = stress_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(seTE),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [150]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

stress_tau_plot <- stress_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [151]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = stress_loo_plot_all,
  file = file.path(graph_path, "forest_perceived_stress_leave_one_out_all_designs.pdf"),
  title_left = "Perceived stress, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_stress_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = stress_loo_plot_controlled,
  file = file.path(graph_path, "forest_perceived_stress_leave_one_out_controlled_only.pdf"),
  title_left = "Perceived stress, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = as.numeric(res_stress_controlled_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = stress_tau_plot,
  file = file.path(graph_path, "forest_perceived_stress_tau_sensitivity.pdf"),
  title_left = "Perceived stress, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_stress_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_233268313
                   2

agg_record_233268313
                   2

agg_record_233268313
                   2

In [152]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_stress_study_display_all <- make_study_effect_table(stress_study_display_all)

tab_stress_study_display_controlled <- make_study_effect_table(stress_study_display_controlled)

tab_stress_effect_sizes_all <- es_stress_all %>%
  dplyr::left_join(study_labels_stress, by = "study_id") %>%
  dplyr::left_join(stress_N_by_study, by = "study_id") %>%
  dplyr::transmute(
    study_id,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_stress_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(stress_main_dat), nrow(stress_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(stress_main_dat$study_id),
    dplyr::n_distinct(stress_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_stress_main_mv$b),
    as.numeric(res_stress_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_stress_main_mv$se),
    as.numeric(res_stress_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_stress_main_mv$ci.lb),
    as.numeric(res_stress_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_stress_main_mv$ci.ub),
    as.numeric(res_stress_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_stress_main_mv$pval),
    as.numeric(res_stress_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_stress_main_mv$sigma2),
    as.numeric(res_stress_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_stress_loo_all <- stress_loo_results %>%
  round_df_2()

tab_stress_loo_controlled <- stress_loo_controlled_results %>%
  round_df_2()

tab_stress_tau <- stress_tau_sensitivity %>%
  round_df_2()

tab_stress_N_by_study <- stress_N_by_study %>%
  round_df_2()

tab_stress_N_by_design <- stress_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_stress_effect_sizes_all,
  file.path(table_path, "perceived_stress_effect_sizes_all.csv")
)

readr::write_csv(
  tab_stress_study_display_all,
  file.path(table_path, "perceived_stress_study_display_main.csv")
)

readr::write_csv(
  tab_stress_study_display_controlled,
  file.path(table_path, "perceived_stress_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_stress_model_compare,
  file.path(table_path, "perceived_stress_model_comparison.csv")
)

readr::write_csv(
  tab_stress_loo_all,
  file.path(table_path, "perceived_stress_leave_one_out_all.csv")
)

readr::write_csv(
  tab_stress_loo_controlled,
  file.path(table_path, "perceived_stress_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_stress_tau,
  file.path(table_path, "perceived_stress_tau_sensitivity.csv")
)

readr::write_csv(
  tab_stress_N_by_study,
  file.path(table_path, "perceived_stress_sample_size_by_study.csv")
)

readr::write_csv(
  tab_stress_N_by_design,
  file.path(table_path, "perceived_stress_sample_size_by_design.csv")
)

In [153]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved perceived stress PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved perceived stress tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "perceived_stress.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "perceived_stress.*csv$", full.names = TRUE)

Saved perceived stress PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved perceived stress tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_controlled_only.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_leave_one_out_all_designs.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_leave_one_out_controlled_only.pdf"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_main_all_designs.pdf"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_perceived_stress_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/perceived_stress_tau_sensitivity.csv"

#### **Overall interpretation** 
The main multilevel model including all study designs suggested a small reduction in perceived stress associated with CWE (g ≈ −0.30, with negative values indicating greater stress reduction), but with wide uncertainty and no statistically reliable effect under Hartung-Knapp-style inference. When the analysis was restricted to controlled studies only, the pooled estimate attenuated markedly toward the null and shifted slightly in the opposite direction to around g ≈ 0.03. This pattern suggests that the more favorable estimate in the full synthesis may be driven largely by the uncontrolled single-group study rather than by comparative treatment effects in controlled designs.

The leave-one-out results support that interpretation. In the all-designs analysis, the pooled estimate was negative in three of the four leave-one-out models, but became slightly positive when Faid et al. (2022) was omitted. The magnitude varied as follows:
* all-designs models ranged from about −0.48 to 0.03
* controlled-only models ranged from about −0.07 to 0.23

This indicates that the perceived stress signal is not directionally stable. In particular, omitting Faid et al. (2022) changed the pooled estimate from about g ≈ −0.30 to about g ≈ 0.03, effectively removing the apparent benefit altogether. That suggests this single-group study contributes substantially to the overall negative pooled estimate. By contrast, omitting any one of the controlled studies still left the all-designs estimate in the negative direction, although with wide confidence intervals and no statistical reliability.

The controlled-only leave-one-out results should be interpreted cautiously because they are based on only three studies. Once one study is removed, inference rests on just two studies and the confidence intervals become very wide. Even so, these analyses are informative because they show that the controlled evidence itself is mixed. Omitting Blades et al. (2024) or Ketelhut et al. (2023) yielded slightly negative pooled estimates, whereas omitting Epel et al. (2025) yielded a positive pooled estimate. So unlike the mood/affect findings, the controlled perceived stress evidence is not even directionally consistent.

The tau sensitivity analysis adds an important nuance. Across a broad range of assumed study-level heterogeneity values, the pooled estimate remained consistently negative, roughly between g ≈ −0.32 and g ≈ −0.30. Thus, the direction and approximate magnitude of the full pooled association were fairly robust to alternative heterogeneity assumptions. What changed as heterogeneity increased was mainly precision, not the point estimate itself. However, this robustness to tau assumptions should not be overinterpreted, because the leave-one-out analyses show that the overall negative estimate depends importantly on inclusion of the uncontrolled single-group study.

All in all, CWE showed a possible tendency toward reduced perceived stress in the full synthesis, but that pattern appears strongly design-dependent. The apparent benefit was attenuated to essentially null when analyses were restricted to controlled studies, suggesting that uncontrolled within-person improvement may account for much of the favorable signal in the overall model. Leave-one-out analyses further showed that the result is fragile, especially with respect to the inclusion of Faid et al. (2022), and that the controlled evidence is mixed rather than directionally consistent. Overall, the findings suggest that evidence for a stress-reducing effect of CWE remains limited, heterogeneous, and highly sensitive to study design.

## **Wellbeing**
[Back to Table of Content](#table-of-content)

In [154]:
## ============================================================
## Filter to wellbeing domain
##    I keep all Pre
##    I keep Post only at day 7 for study 9
## ============================================================

mental_well <- mental %>%
  dplyr::filter(
    instrument_domain == "Wellbeing",
    timepoint_label_harmonised %in% c("Pre", "Post")
  ) %>%
  dplyr::filter(
    !(study_id == 9 &
        timepoint_label_harmonised == "Post" &
        !is.na(timepoint_days_num) &
        timepoint_days_num != 7)
  ) %>%
  dplyr::mutate(
    group_harmonised = dplyr::if_else(
      study_id == 9,
      "SingleGroup",
      group_harmonised
    )
  )

mental_well %>%
  dplyr::distinct(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id instrument group_harmonised timepoint_label_harmonised
1 5        WEMWBS     SingleGroup      Post
2 5        WEMWBS     SingleGroup      Pre
3 9        SHS        SingleGroup      Post
4 9        SHS        SingleGroup      Pre
5 9        WEMWBS     SingleGroup      Post
6 9        WEMWBS     SingleGroup      Pre
  timepoint_days_num
1 NA
2 NA
3  7
4  0
5  7
6  0

In [155]:
## ============================================================
## Reconstruct change SD from 95 percent CI if available
## ============================================================

mental_well <- mental_well %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [156]:
## ============================================================
## Estimate mean and SD from median and IQR where needed
## ============================================================

mental_well <- mental_well %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [157]:
## ============================================================
## Estimate mean and SD from median and IQR where needed
## ============================================================

mental_well <- mental_well %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [158]:
## ============================================================
## Keep one row per study instrument group timepoint
##    I prefer ITT over PP if duplicates exist
## ============================================================

analysis_set_levels <- c("ITT", "PP")

well_prepost <- mental_well %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

well_prepost %>%
  dplyr::count(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id instrument group_harmonised timepoint_label_harmonised n
1 5        WEMWBS     SingleGroup      Post                       1
2 5        WEMWBS     SingleGroup      Pre                        1
3 9        SHS        SingleGroup      Post                       1
4 9        SHS        SingleGroup      Pre                        1
5 9        WEMWBS     SingleGroup      Post                       1
6 9        WEMWBS     SingleGroup      Pre                        1

In [159]:
## ============================================================
## Compute pre post change scores
## ============================================================

r_change <- 0.5

well_wide <- well_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, instrument, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

well_wide %>%
  dplyr::select(
    study_id,
    instrument,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, instrument)

  study_id instrument group_harmonised n_change change_mean_calc change_sd_calc
1 5        WEMWBS     SingleGroup      29       8.14             7.628447
2 9        SHS        SingleGroup      13       0.37             0.671044
3 9        WEMWBS     SingleGroup      13       2.00             9.388418

In [160]:
## ============================================================
## Classify design
##    In this wellbeing set all effects are single group
##    I still keep the design logic explicit
## ============================================================

well_wide <- well_wide %>%
  dplyr::group_by(study_id, instrument) %>%
  dplyr::mutate(
    n_groups = dplyr::n(),
    has_single = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      n_groups == 1 & has_single ~ "single_group",
      TRUE ~ "other"
    )
  ) %>%
  dplyr::ungroup()

well_wide %>%
  dplyr::distinct(study_id, instrument, design)

  study_id instrument design
1 5        WEMWBS     single_group
2 9        SHS        single_group
3 9        WEMWBS     single_group

In [161]:
## ============================================================
## Effect sizes
##    Higher score means better wellbeing
##    Positive yi means improvement
## ============================================================

es_well_all <- well_wide %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::mutate(
    d = change_mean_calc / change_sd_calc,
    J = 1 - 3 / (4 * n_change - 1),
    yi = J * d,
    v_d = 1 / n_change + (d^2) / (2 * n_change),
    vi = J^2 * v_d,
    outcome_domain = "Wellbeing",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    instrument,
    outcome_domain,
    design_type,
    n_change,
    yi,
    vi
  ) %>%
  dplyr::arrange(study_id, instrument)

es_well_all

  study_id instrument outcome_domain design_type  n_change yi        vi
1 5        WEMWBS     Wellbeing      single_group 29       1.0392223 0.05132752
2 9        SHS        Wellbeing      single_group 13       0.5189456 0.07849734
3 9        WEMWBS     Wellbeing      single_group 13       0.2004973 0.06968560

In [162]:
## ============================================================
## Sample size summary
##    One N per study so I do not double count instruments
## ============================================================

well_N_by_study <- well_wide %>%
  dplyr::group_by(study_id, design) %>%
  dplyr::summarise(
    N_study = max(n_change, na.rm = TRUE),
    .groups = "drop"
  )

k_well <- nrow(well_N_by_study)
N_well_total <- sum(well_N_by_study$N_study, na.rm = TRUE)

well_N_by_design <- well_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nWellbeing meta analysis\n")
cat(" Number of studies k = ", k_well, "\n", sep = "")
cat(" Total participants N = ", N_well_total, "\n", sep = "")

cat("\nBreakdown by design\n")
print(well_N_by_design)

Wellbeing meta analysis
 Number of studies k = 2
 Total participants N = 42

Breakdown by design
# A tibble: 1 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 single_group        2       42

In [163]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_well <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [164]:
## ------------------------------------------------------------
## Main analysis datasets
## For wellbeing I keep the same multilevel framework
## as for the other outcomes
## Here one study contributes multiple effects
## ------------------------------------------------------------

well_main_dat <- es_well_all %>%
  dplyr::arrange(study_id, instrument)

well_controlled_dat <- es_well_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, instrument)

cat("\nWellbeing main dataset\n")
cat(" k effects =", nrow(well_main_dat), "\n")
cat(" studies =", paste(sort(unique(well_main_dat$study_id)), collapse = ", "), "\n")

cat("\nWellbeing controlled only dataset\n")
cat(" k effects =", nrow(well_controlled_dat), "\n")
if (nrow(well_controlled_dat) > 0) {
  cat(" studies =", paste(sort(unique(well_controlled_dat$study_id)), collapse = ", "), "\n")
} else {
  cat(" studies = none\n")
}

Wellbeing main dataset
 k effects = 3
 studies = 5, 9

Wellbeing controlled only dataset
 k effects = 0
 studies = none

In [165]:
## ============================================================
## WELLBEING
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_well_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = well_main_dat
)

print(res_well_main_mv)
broom::tidy(res_well_main_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.1932  0.4396      2     no  study_id

Test for Heterogeneity:
Q(df = 2) = 6.0636, p-val = 0.0482

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.6843  0.3443  1.9873   1  0.2968  -3.6908  5.0594

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.6842781 0.3443259 1.987298  0.2967928

In [166]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## No controlled wellbeing studies are available
## ------------------------------------------------------------

well_controlled_result_placeholder <- tibble::tibble(
  term = "overall",
  type = "summary",
  estimate = NA_real_,
  std.error = NA_real_,
  statistic = NA_real_,
  p.value = NA_real_
)

well_controlled_result_placeholder

  term    type    estimate std.error statistic p.value
1 overall summary NA       NA        NA        NA

In [167]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

well_model_compare <- dplyr::bind_rows(
  broom::tidy(res_well_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  well_controlled_result_placeholder %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

well_model_compare

  model            term    estimate  std.error statistic p.value
1 main_all_designs overall 0.6842781 0.3443259 1.987298  0.2967928
2 controlled_only  overall        NA        NA       NA         NA

In [168]:
## ------------------------------------------------------------
## Leave one out by study
## If only one study remains I return a fixed effect summary
## of the remaining effect sizes for display purposes only
## ------------------------------------------------------------

well_loo_results <- purrr::map_dfr(
  sort(unique(well_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- well_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate > 0 ~ "positive_better_for_cwe",
          estimate < 0 ~ "negative_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1 && nrow(loo_dat) >= 1) {

      single_model <- metafor::rma(
        yi = yi,
        vi = vi,
        method = "FE",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(single_model$b),
        se = single_model$se,
        ci_lb = single_model$ci.lb,
        ci_ub = single_model$ci.ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining_fixed_effect_summary",
        direction = dplyr::case_when(
          estimate > 0 ~ "positive_better_for_cwe",
          estimate < 0 ~ "negative_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

well_loo_results <- well_loo_results %>%
  dplyr::left_join(
    study_labels_well,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

well_loo_results

  dropped_study study_label             k_effects_remaining n_studies_remaining
1 5             Faid et al 2022         2                   1
2 9             Knill-Jones et al. 2024 1                   1
  result_type                                 estimate  se        ci_lb
1 single_study_remaining_fixed_effect_summary 0.3502531 0.1921321 -0.0263188
2 single_study_remaining_fixed_effect_summary 1.0392223 0.2265558  0.5951812
  ci_ub     p_value tau2_study direction               significant
1 0.7268251 NA      NA         positive_better_for_cwe NA
2 1.4832635 NA      NA         positive_better_for_cwe NA

In [169]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## No controlled wellbeing studies are available
## ------------------------------------------------------------

well_loo_controlled_results <- tibble::tibble(
  dropped_study = NA_real_,
  study_label = NA_character_,
  k_effects_remaining = NA_integer_,
  n_studies_remaining = NA_integer_,
  result_type = "no_controlled_wellbeing_studies",
  estimate = NA_real_,
  se = NA_real_,
  ci_lb = NA_real_,
  ci_ub = NA_real_,
  p_value = NA_real_,
  tau2_study = NA_real_,
  direction = NA_character_,
  significant = NA
)

well_loo_controlled_results

  dropped_study study_label k_effects_remaining n_studies_remaining
1 NA            NA          NA                  NA
  result_type                     estimate se ci_lb ci_ub p_value tau2_study
1 no_controlled_wellbeing_studies NA       NA NA    NA    NA      NA
  direction significant
1 NA        NA

In [170]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## I vary the study level heterogeneity component
## ------------------------------------------------------------

tau2_grid_well <- c(0.00, 0.05, 0.10, 0.20, 0.40)

well_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_well,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = well_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

well_tau_sensitivity <- well_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate > 0 ~ "positive_better_for_cwe",
      estimate < 0 ~ "negative_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

well_tau_sensitivity

  tau2_study_fixed estimate  se        ci_lb     ci_ub    p_value
1 0.00             0.6384724 0.1465334 -1.223411 2.500356 0.1436211
2 0.05             0.6683622 0.2162977 -2.079960 3.416685 0.1992533
3 0.10             0.6775127 0.2681052 -2.729087 4.084112 0.2398854
4 0.20             0.6845686 0.3492194 -3.752685 5.121822 0.3003058
5 0.40             0.6891481 0.4711710 -5.297647 6.675943 0.3817827
  direction               significant
1 positive_better_for_cwe FALSE
2 positive_better_for_cwe FALSE
3 positive_better_for_cwe FALSE
4 positive_better_for_cwe FALSE
5 positive_better_for_cwe FALSE

In [171]:
## ------------------------------------------------------------
## Create display data for forest plots
## For wellbeing I keep the individual effect sizes for display
## because one study contributes two instrument specific effects
## The inferential model remains rma.mv
## ------------------------------------------------------------

well_study_display_all <- well_main_dat %>%
  dplyr::left_join(study_labels_well, by = "study_id") %>%
  dplyr::left_join(well_N_by_study, by = "study_id") %>%
  dplyr::mutate(
    N_study = as.integer(N_study),
    study_label_n = paste0(
      study_label,
      " (",
      instrument,
      ", N=",
      N_study,
      ")"
    )
  ) %>%
  dplyr::arrange(study_id, instrument)

well_study_display_controlled <- tibble::tibble(
  study_id = numeric(0),
  instrument = character(0),
  outcome_domain = character(0),
  design_type = character(0),
  n_change = numeric(0),
  yi = numeric(0),
  vi = numeric(0),
  study_label = character(0),
  design = character(0),
  N_study = integer(0),
  study_label_n = character(0)
)

well_study_display_all
well_study_display_controlled

  study_id instrument outcome_domain design_type  n_change yi        vi
1 5        WEMWBS     Wellbeing      single_group 29       1.0392223 0.05132752
2 9        SHS        Wellbeing      single_group 13       0.5189456 0.07849734
3 9        WEMWBS     Wellbeing      single_group 13       0.2004973 0.06968560
  study_label             design       N_study
1 Faid et al 2022         single_group 29
2 Knill-Jones et al. 2024 single_group 13
3 Knill-Jones et al. 2024 single_group 13
  study_label_n
1 Faid et al 2022 (WEMWBS, N=29)
2 Knill-Jones et al. 2024 (SHS, N=13)
3 Knill-Jones et al. 2024 (WEMWBS, N=13)

     study_id instrument outcome_domain design_type n_change yi vi study_label
     design N_study study_label_n

In [172]:
## ============================================================
## WELLBEING
## Plotting and export section aligned with corrected workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [173]:
## ============================================================
## DISPLAY DATA FOR FOREST PLOTS
## Important
## Main inference remains based on rma.mv
## For the main forest plot I aggregate to one display effect
## per study because study 9 contributes two instruments
## ============================================================

## ------------------------------------------------------------
## Aggregate one display effect per study for main plot
## This is for display only
## ------------------------------------------------------------

well_study_display_all <- well_main_dat %>%
  dplyr::group_by(study_id) %>%
  dplyr::summarise(
    yi = sum(yi / vi, na.rm = TRUE) / sum(1 / vi, na.rm = TRUE),
    vi = 1 / sum(1 / vi, na.rm = TRUE),
    k_effects = dplyr::n(),
    .groups = "drop"
  ) %>%
  dplyr::left_join(study_labels_well, by = "study_id") %>%
  dplyr::left_join(well_N_by_study, by = "study_id") %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Single group"
  ) %>%
  dplyr::arrange(study_id)

In [174]:
## No controlled studies available
well_study_display_controlled <- tibble::tibble(
  study_id = numeric(0),
  study_label = character(0),
  design = character(0),
  N_study = numeric(0),
  yi = numeric(0),
  vi = numeric(0),
  sei = numeric(0),
  ci_lb_plot = numeric(0),
  ci_ub_plot = numeric(0),
  effect_ci = character(0),
  N_lab = character(0),
  design_label = character(0),
  k_effects = integer(0)
)

In [175]:
## ------------------------------------------------------------
## Effect level display table
## This is useful for exports because the main display plot
## aggregates study 9 across instruments
## ------------------------------------------------------------

well_effect_display_all <- well_main_dat %>%
  dplyr::left_join(study_labels_well, by = "study_id") %>%
  dplyr::left_join(well_N_by_study, by = "study_id") %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Single group"
  ) %>%
  dplyr::arrange(study_id, instrument)

In [176]:
## ------------------------------------------------------------
## Wrap very long labels
## ------------------------------------------------------------

well_study_display_all <- well_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [177]:
## ------------------------------------------------------------
## Plot only model for pooled diamond
## This is for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_well_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = well_study_display_all
)

well_study_display_all <- well_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_well_all_plot) / sum(weights(res_well_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

In [178]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Wellbeing"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for wellbeing", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours control", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours CWE", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours control", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours CWE", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [179]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = well_study_display_all,
  model = res_well_all_plot,
  file = file.path(graph_path, "forest_wellbeing_all_designs_journal_style.pdf"),
  outcome_title = "Wellbeing, all designs"
)

agg_record_813394126
                   2

In [180]:
## ------------------------------------------------------------
## Controlled only forest plot
## Placeholder because no controlled wellbeing studies exist
## ------------------------------------------------------------

pdf(
  file = file.path(graph_path, "forest_wellbeing_controlled_only.pdf"),
  width = 10,
  height = 7
)

plot.new()
text(
  x = 0.5,
  y = 0.55,
  labels = "Wellbeing controlled only analysis not possible",
  cex = 1.2
)
text(
  x = 0.5,
  y = 0.45,
  labels = "No controlled wellbeing studies were available",
  cex = 1.0
)

dev.off()

agg_record_313965195
                   2

In [181]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

well_total_N_all <- sum(well_N_by_study$N_study, na.rm = TRUE)

well_loo_plot_all <- well_loo_results %>%
  dplyr::left_join(
    well_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = well_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(seTE),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [182]:
## ------------------------------------------------------------
## Controlled only leave one out placeholder
## ------------------------------------------------------------

pdf(
  file = file.path(graph_path, "forest_wellbeing_leave_one_out_controlled_only.pdf"),
  width = 10,
  height = 7
)

plot.new()
text(
  x = 0.5,
  y = 0.55,
  labels = "Wellbeing controlled only leave one out not possible",
  cex = 1.2
)
text(
  x = 0.5,
  y = 0.45,
  labels = "No controlled wellbeing studies were available",
  cex = 1.0
)

dev.off()

agg_record_581850871
                   2

In [183]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

well_tau_plot <- well_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    TE = estimate,
    seTE = se,
    ci_lb_plot = estimate - 1.96 * se,
    ci_ub_plot = estimate + 1.96 * se,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [184]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = well_loo_plot_all,
  file = file.path(graph_path, "forest_wellbeing_leave_one_out_all_designs.pdf"),
  title_left = "Wellbeing, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_well_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = well_tau_plot,
  file = file.path(graph_path, "forest_wellbeing_tau_sensitivity.pdf"),
  title_left = "Wellbeing, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_well_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1490917408
                    2

agg_record_1490917408
                    2

In [185]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_well_study_display_all <- make_study_effect_table(well_study_display_all)

tab_well_effect_sizes_all <- well_effect_display_all %>%
  dplyr::transmute(
    study_id,
    study_label,
    instrument,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_well_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(well_main_dat), nrow(well_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(well_main_dat$study_id),
    dplyr::n_distinct(well_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_well_main_mv$b),
    NA_real_
  ),
  se = c(
    as.numeric(res_well_main_mv$se),
    NA_real_
  ),
  ci_lb = c(
    as.numeric(res_well_main_mv$ci.lb),
    NA_real_
  ),
  ci_ub = c(
    as.numeric(res_well_main_mv$ci.ub),
    NA_real_
  ),
  p_value = c(
    as.numeric(res_well_main_mv$pval),
    NA_real_
  ),
  tau2_study = c(
    as.numeric(res_well_main_mv$sigma2),
    NA_real_
  )
) %>%
  round_df_2()

tab_well_loo_all <- well_loo_results %>%
  round_df_2()

tab_well_loo_controlled <- well_loo_controlled_results %>%
  round_df_2()

tab_well_tau <- well_tau_sensitivity %>%
  round_df_2()

tab_well_N_by_study <- well_N_by_study %>%
  round_df_2()

tab_well_N_by_design <- well_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_well_effect_sizes_all,
  file.path(table_path, "wellbeing_effect_sizes_all.csv")
)

readr::write_csv(
  tab_well_study_display_all,
  file.path(table_path, "wellbeing_study_display_main.csv")
)

readr::write_csv(
  tab_well_model_compare,
  file.path(table_path, "wellbeing_model_comparison.csv")
)

readr::write_csv(
  tab_well_loo_all,
  file.path(table_path, "wellbeing_leave_one_out_all.csv")
)

readr::write_csv(
  tab_well_loo_controlled,
  file.path(table_path, "wellbeing_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_well_tau,
  file.path(table_path, "wellbeing_tau_sensitivity.csv")
)

readr::write_csv(
  tab_well_N_by_study,
  file.path(table_path, "wellbeing_sample_size_by_study.csv")
)

readr::write_csv(
  tab_well_N_by_design,
  file.path(table_path, "wellbeing_sample_size_by_design.csv")
)

In [186]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved wellbeing PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved wellbeing tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "wellbeing.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "wellbeing.*csv$", full.names = TRUE)

Saved wellbeing PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved wellbeing tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_controlled_only.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_main_all_designs.pdf"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_wellbeing_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/wellbeing_tau_sensitivity.csv"

#### **Overall interpretation** 
The main multilevel model including all available wellbeing data suggested a moderate positive association between CWE and wellbeing (g ≈ 0.68, with positive values indicating greater improvement in wellbeing), but the uncertainty was extremely wide and the effect was not statistically reliable under Hartung-Knapp-style inference. Importantly, this synthesis was based on only two studies contributing three single-group pre post effects, with no controlled wellbeing studies available at all. That means the pooled estimate does not reflect comparative treatment effects versus a control condition, but only within-person improvement over time after CWE exposure. As a result, the apparent positive signal for wellbeing should be interpreted as exploratory and highly provisional rather than as evidence for a causal benefit of CWE.

The leave-one-out results reinforce this interpretation. Because only two studies were available, dropping either one left just a single study remaining, so the leave-one-out analyses no longer represent true meta-analytic syntheses but rather fixed effect summaries of the remaining study data. Even so, they are informative for judging fragility. The pooled estimate remained positive in both leave-one-out scenarios:
* leave-one-out estimates ranged from about 0.35 to 1.04

This indicates that the direction of the wellbeing signal was at least consistent across the two available studies. However, the magnitude changed notably depending on which study remained. Omitting Faid et al. (2022) left only the two Knill-Jones et al. (2024) instrument-specific effects and reduced the estimate to about g ≈ 0.35. In contrast, omitting Knill-Jones et al. (2024) left only Faid et al. (2022), increasing the estimate to about g ≈ 1.04. So while the direction stayed positive, the size of the apparent effect was clearly study-dependent.

Unlike depression, mood/affect, or perceived stress, there was no controlled-only sensitivity analysis possible for wellbeing because all included wellbeing effects came from single-group studies. This is a major limitation. It means there is no way within the current evidence base to test whether the apparent improvement in wellbeing persists when attention is restricted to designs that support stronger causal inference. Accordingly, the wellbeing findings are especially vulnerable to alternative explanations such as regression to the mean, expectancy effects, natural improvement over time, or nonspecific intervention context.

The tau sensitivity analysis adds a useful nuance. Across a broad range of assumed study-level heterogeneity values, the pooled estimate remained consistently positive, ranging only from about g ≈ 0.64 to g ≈ 0.69. Thus, the direction and approximate magnitude of the pooled association were relatively stable to alternative heterogeneity assumptions. What changed with increasing tau² was mainly the precision, not the point estimate itself. However, that apparent robustness should not be overinterpreted, because with only two studies and no controlled comparisons, the main uncertainty is not just heterogeneity estimation but the very limited and design-restricted evidence base itself.

Taken together, the wellbeing results suggest a possible positive signal for improved wellbeing after CWE, but this evidence is extremely limited and methodologically fragile. The full synthesis points in a favorable direction, and that direction remains positive across leave-one-out and tau sensitivity analyses. However, the evidence comes entirely from uncontrolled single-group data, the pooled estimate is based on only two studies, and the confidence interval is extremely wide. Overall, the current results are better interpreted as preliminary and hypothesis-generating rather than as convincing evidence that CWE improves wellbeing relative to an appropriate comparison condition.

## **Sleep**
[Back to Table of Content](#table-of-content)

In [187]:
## ------------------------------------------------------------
## Filter mental data to Sleep domain
## Recode study 9 as single group
## Keep only primary Pre and Post for main synthesis
## ------------------------------------------------------------

mental_sleep <- mental %>%
  dplyr::filter(instrument_domain == "Sleep") %>%
  dplyr::mutate(
    group_harmonised = dplyr::case_when(
      study_id == 9 ~ "SingleGroup",
      TRUE ~ group_harmonised
    )
  )

## Quick structural check
mental_sleep %>%
  dplyr::distinct(
    study_id,
    instrument,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id instrument group_harmonised timepoint_label_harmonised
1 6        VAS        Control          Post
2 6        VAS        Control          Pre
3 6        VAS        Intervention     Post
4 6        VAS        Intervention     Pre
5 9        PSQI       SingleGroup      Post
6 9        PSQI       SingleGroup      Post-Immersion
7 9        PSQI       SingleGroup      Pre

In [188]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_sleep <- mental_sleep %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [189]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_sleep <- mental_sleep %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [190]:
## ------------------------------------------------------------
## Select Pre and Post data and prefer ITT over PP
## Post immersion is not part of the primary synthesis
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

sleep_prepost <- mental_sleep %>%
  dplyr::filter(timepoint_label_harmonised %in% c("Pre", "Post")) %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
sleep_prepost %>%
  dplyr::count(study_id, group_harmonised, timepoint_label_harmonised)

  study_id group_harmonised timepoint_label_harmonised n
1 6        Control          Post                       1
2 6        Control          Pre                        1
3 6        Intervention     Post                       1
4 6        Intervention     Pre                        1
5 9        SingleGroup      Post                       1
6 9        SingleGroup      Pre                        1

In [191]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

sleep_wide <- sleep_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

sleep_wide %>%
  dplyr::select(
    study_id,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id group_harmonised n_change change_mean_calc change_sd_calc
1 6        Control          121      -1.0             2.424871
2 6        Intervention     121      -1.4             2.291288
3 9        SingleGroup       13      -0.7             3.400706

In [192]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

sleep_wide <- sleep_wide %>%
  dplyr::group_by(study_id) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

sleep_wide %>%
  dplyr::distinct(study_id, design)

  study_id design
1 6        controlled
2 9        single_group

In [193]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

sleep_change_groups <- sleep_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

sleep_change_groups %>%
  dplyr::arrange(study_id, group_harmonised)

  study_id design       group_harmonised change_mean_calc change_sd_calc
1 6        controlled   Control          -1.0             2.424871
2 6        controlled   Intervention     -1.4             2.291288
3 9        single_group SingleGroup      -0.7             3.400706
  n_change
1 121
2 121
3  13

In [194]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

sleep_change_wide_study <- sleep_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [195]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## More negative yi means greater improvement under CWE
## More positive yi means worse outcome under CWE
## ------------------------------------------------------------

es_sleep_controlled <- sleep_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .
  ) %>%
  dplyr::mutate(
    outcome_domain = "Sleep",
    design_type = "controlled"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_sleep_controlled

  study_id outcome_domain design_type yi        vi
1 6        Sleep          controlled  -0.169031 0.01658796

In [196]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_sleep_single <- sleep_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Sleep",
    design_type = "single_group"
  ) %>%
  dplyr::select(study_id, outcome_domain, design_type, yi, vi)

es_sleep_single

  study_id outcome_domain design_type  yi         vi
1 9        Sleep          single_group -0.1937314 0.06958301

In [197]:
## ------------------------------------------------------------
## Combine all analyzable sleep effect sizes
## ------------------------------------------------------------

es_sleep_all <- dplyr::bind_rows(
  es_sleep_controlled,
  es_sleep_single
) %>%
  dplyr::arrange(study_id) %>%
  dplyr::mutate(
    effect_id = paste0("sleep_", dplyr::row_number())
  )

es_sleep_all

  study_id outcome_domain design_type  yi         vi         effect_id
1 6        Sleep          controlled   -0.1690310 0.01658796 sleep_1
2 9        Sleep          single_group -0.1937314 0.06958301 sleep_2

In [198]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

sleep_N_by_study_raw <- sleep_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(study_id, design, N_study)

sleep_N_by_study <- es_sleep_all %>%
  dplyr::distinct(study_id, design_type) %>%
  dplyr::left_join(
    sleep_N_by_study_raw,
    by = "study_id"
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, design, N_study) %>%
  dplyr::distinct()

k_sleep <- nrow(sleep_N_by_study)
N_sleep_total <- sum(sleep_N_by_study$N_study, na.rm = TRUE)

sleep_N_by_design <- sleep_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nSleep meta analysis contributing studies\n")
cat(" k studies =", k_sleep, "\n")
cat(" total N   =", N_sleep_total, "\n")
print(sleep_N_by_design)

Sleep meta analysis contributing studies
 k studies = 2
 total N   = 255
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          1      242
2 single_group        1       13

In [199]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_sleep <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [200]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

sleep_main_dat <- es_sleep_all %>%
  dplyr::arrange(study_id)

sleep_controlled_dat <- es_sleep_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id)

cat("\nSleep main dataset\n")
cat(" k effects =", nrow(sleep_main_dat), "\n")
cat(" studies =", paste(sort(unique(sleep_main_dat$study_id)), collapse = ", "), "\n")

cat("\nSleep controlled only dataset\n")
cat(" k effects =", nrow(sleep_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(sleep_controlled_dat$study_id)), collapse = ", "), "\n")

Sleep main dataset
 k effects = 2
 studies = 6, 9

Sleep controlled only dataset
 k effects = 1
 studies = 6

In [201]:
## ============================================================
## SLEEP
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_sleep_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = sleep_main_dat
)

print(res_sleep_main_mv)
broom::tidy(res_sleep_main_mv)

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.0071, p-val = 0.9329

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.1738  0.1157  -1.5016   1  0.3740  -1.6443  1.2968

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.1737859 0.1157358 -1.501575 0.3740259

In [202]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## With only one controlled study this becomes a descriptive
## single study result instead of a meta analytic model
## ------------------------------------------------------------

if (nrow(sleep_controlled_dat) >= 2) {

  res_sleep_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = sleep_controlled_dat
  )

  print(res_sleep_controlled_mv)

  sleep_controlled_tidy <- broom::tidy(res_sleep_controlled_mv)

} else if (nrow(sleep_controlled_dat) == 1) {

  res_sleep_controlled_mv <- NULL

  sleep_controlled_tidy <- sleep_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(sleep_controlled_tidy)

} else {

  res_sleep_controlled_mv <- NULL

  sleep_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(sleep_controlled_tidy)
}

     term    type  estimate std.error statistic p.value
1 overall summary -0.169031 0.1287942        NA      NA

In [203]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

sleep_model_compare <- dplyr::bind_rows(
  broom::tidy(res_sleep_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  sleep_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

sleep_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall -0.1737859 0.1157358 -1.501575 0.3740259
2 controlled_only  overall -0.1690310 0.1287942        NA        NA

In [205]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

sleep_loo_results <- purrr::map_dfr(
  sort(unique(sleep_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- sleep_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

sleep_loo_results <- sleep_loo_results %>%
  dplyr::left_join(
    study_labels_sleep,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

sleep_loo_results

  dropped_study study_label             k_effects_remaining n_studies_remaining
1 6             Hinkka et al 2016       1                   1
2 9             Knill-Jones et al. 2024 1                   1
  result_type            estimate   se        ci_lb      ci_ub      p_value
1 single_study_remaining -0.1937314 0.2637859 -0.7107518 0.32328897 NA
2 single_study_remaining -0.1690310 0.1287942 -0.4214678 0.08340568 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         negative_better_for_cwe NA

In [206]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

sleep_loo_controlled_results <- purrr::map_dfr(
  sort(unique(sleep_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- sleep_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

sleep_loo_controlled_results <- sleep_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_sleep,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

sleep_loo_controlled_results

  dropped_study study_label       k_effects_remaining n_studies_remaining
1 6             Hinkka et al 2016 0                   0
  result_type       estimate se ci_lb ci_ub p_value tau2_study direction
1 no_data_remaining NA       NA NA    NA    NA      NA         NA
  significant
1 NA

In [207]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_sleep <- c(0.00, 0.05, 0.10, 0.20, 0.40)

sleep_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_sleep,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = sleep_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

sleep_tau_sensitivity <- sleep_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

sleep_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb     ci_ub    p_value
1 0.00             -0.1737859 0.1157358 -1.644348 1.296776 0.3740259
2 0.05             -0.1778656 0.2068124 -2.805667 2.449935 0.5478151
3 0.10             -0.1790941 0.2628483 -3.518899 3.160711 0.6192342
4 0.20             -0.1800350 0.3465524 -4.583401 4.223331 0.6949777
5 0.40             -0.1806427 0.4698409 -6.150537 5.789252 0.7663270
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [208]:
## ============================================================
## SLEEP
## Plotting and export section aligned with Stress workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [209]:
## Rounded helper
## ------------------------------------------------------------

round_df_2 <- function(df) {
  df %>%
    dplyr::mutate(
      dplyr::across(
        where(is.numeric),
        ~ round(.x, 2)
      )
    )
}

In [210]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Sleep has one effect per study in the current dataset
## ============================================================

sleep_study_display_all <- sleep_main_dat %>%
  dplyr::left_join(study_labels_sleep, by = "study_id") %>%
  dplyr::left_join(sleep_N_by_study, by = "study_id") %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id)

sleep_study_display_controlled <- sleep_controlled_dat %>%
  dplyr::left_join(study_labels_sleep, by = "study_id") %>%
  dplyr::left_join(
    sleep_N_by_study %>% dplyr::filter(design == "controlled"),
    by = "study_id"
  ) %>%
  dplyr::distinct(study_id, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id)

In [211]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

sleep_study_display_all <- sleep_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

sleep_study_display_controlled <- sleep_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [212]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_sleep_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = sleep_study_display_all
)

if (nrow(sleep_study_display_controlled) >= 2) {
  res_sleep_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = sleep_study_display_controlled
  )
} else {
  res_sleep_controlled_plot <- NULL
}

sleep_study_display_all <- sleep_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_sleep_all_plot) / sum(weights(res_sleep_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_sleep_controlled_plot)) {
  sleep_study_display_controlled <- sleep_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_sleep_controlled_plot) / sum(weights(res_sleep_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  sleep_study_display_controlled <- sleep_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [217]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## Sleep specific robust versions
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Sleep"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for sleep", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Sleep"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled sleep study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for sleep", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [218]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = sleep_study_display_all,
  model = res_sleep_all_plot,
  file = file.path(graph_path, "forest_sleep_all_designs_journal_style.pdf"),
  outcome_title = "Sleep, all designs"
)

save_forest_controlled_journal(
  dat = sleep_study_display_controlled,
  model = res_sleep_controlled_plot,
  file = file.path(graph_path, "forest_sleep_controlled_journal_style.pdf"),
  outcome_title = "Sleep, controlled studies"
)

agg_record_2099245979
                    2

agg_record_2099245979
                    2

In [219]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

sleep_total_N_all <- sum(sleep_N_by_study$N_study, na.rm = TRUE)

sleep_total_N_controlled <- sleep_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

sleep_loo_plot_all <- sleep_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    sleep_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = sleep_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

sleep_loo_plot_controlled <- sleep_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    sleep_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = sleep_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [220]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

sleep_tau_plot <- sleep_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [221]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = sleep_loo_plot_all,
  file = file.path(graph_path, "forest_sleep_leave_one_out_all_designs.pdf"),
  title_left = "Sleep, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_sleep_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = sleep_loo_plot_controlled,
  file = file.path(graph_path, "forest_sleep_leave_one_out_controlled_only.pdf"),
  title_left = "Sleep, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_sleep_controlled_mv)) as.numeric(res_sleep_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = sleep_tau_plot,
  file = file.path(graph_path, "forest_sleep_tau_sensitivity.pdf"),
  title_left = "Sleep, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_sleep_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_407265484
                   2

agg_record_407265484
                   2

In [222]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_sleep_study_display_all <- make_study_effect_table(sleep_study_display_all)

tab_sleep_study_display_controlled <- make_study_effect_table(sleep_study_display_controlled)

tab_sleep_effect_sizes_all <- es_sleep_all %>%
  dplyr::left_join(study_labels_sleep, by = "study_id") %>%
  dplyr::left_join(sleep_N_by_study, by = "study_id") %>%
  dplyr::transmute(
    study_id,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_sleep_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(sleep_main_dat), nrow(sleep_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(sleep_main_dat$study_id),
    dplyr::n_distinct(sleep_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_sleep_main_mv$b),
    if (nrow(sleep_controlled_dat) == 1) sleep_controlled_dat$yi[1] else as.numeric(res_sleep_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_sleep_main_mv$se),
    if (nrow(sleep_controlled_dat) == 1) sqrt(sleep_controlled_dat$vi[1]) else as.numeric(res_sleep_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_sleep_main_mv$ci.lb),
    if (nrow(sleep_controlled_dat) == 1) sleep_controlled_dat$yi[1] - 1.96 * sqrt(sleep_controlled_dat$vi[1]) else as.numeric(res_sleep_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_sleep_main_mv$ci.ub),
    if (nrow(sleep_controlled_dat) == 1) sleep_controlled_dat$yi[1] + 1.96 * sqrt(sleep_controlled_dat$vi[1]) else as.numeric(res_sleep_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_sleep_main_mv$pval),
    if (nrow(sleep_controlled_dat) == 1) NA_real_ else as.numeric(res_sleep_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_sleep_main_mv$sigma2),
    if (nrow(sleep_controlled_dat) == 1) NA_real_ else as.numeric(res_sleep_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_sleep_loo_all <- sleep_loo_results %>%
  round_df_2()

tab_sleep_loo_controlled <- sleep_loo_controlled_results %>%
  round_df_2()

tab_sleep_tau <- sleep_tau_sensitivity %>%
  round_df_2()

tab_sleep_N_by_study <- sleep_N_by_study %>%
  round_df_2()

tab_sleep_N_by_design <- sleep_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_sleep_effect_sizes_all,
  file.path(table_path, "sleep_effect_sizes_all.csv")
)

readr::write_csv(
  tab_sleep_study_display_all,
  file.path(table_path, "sleep_study_display_main.csv")
)

readr::write_csv(
  tab_sleep_study_display_controlled,
  file.path(table_path, "sleep_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_sleep_model_compare,
  file.path(table_path, "sleep_model_comparison.csv")
)

readr::write_csv(
  tab_sleep_loo_all,
  file.path(table_path, "sleep_leave_one_out_all.csv")
)

readr::write_csv(
  tab_sleep_loo_controlled,
  file.path(table_path, "sleep_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_sleep_tau,
  file.path(table_path, "sleep_tau_sensitivity.csv")
)

readr::write_csv(
  tab_sleep_N_by_study,
  file.path(table_path, "sleep_sample_size_by_study.csv")
)

readr::write_csv(
  tab_sleep_N_by_design,
  file.path(table_path, "sleep_sample_size_by_design.csv")
)

In [223]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved sleep PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved sleep tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "sleep.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "sleep.*csv$", full.names = TRUE)

Saved sleep PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved sleep tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_controlled_only.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_leave_one_out_all_designs.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_leave_one_out_controlled_only.pdf"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_main_all_designs.pdf"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_sleep_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/sleep_tau_sensitivity.csv"

# **Objective 2: Physiological/Biological Outcomes**
[Back to Table of Content](#table-of-content)

#### Examine effects of CWE on broader psychological and physiological variables associated with mental health, including sleep quality, thermoregulatory responses (core and skin temperature), metabolic outcomes, and neurobiological markers (cortisol, norepinephrine, inflammatory cytokines such as IL-6, TNF-α, and CRP).

**_Availability of Secondary Physiological Outcomes_**
_For the secondary objective examining broader physiological and neurobiological correlates of cold-water exposure, we applied the criterion that outcomes must be reported by at least two independent studies to be eligible for quantitative synthesis Across all non-mental health data, only two biomarker classes met this threshold (i) cortisol (studies 1, 10, 11) and (ii) β-endorphin (Studies 7, 11) All other physiological, hormonal, metabolic, thermoregulatory, or neurobiological outcomes (e.g., norepinephrine, adrenaline, serotonin, 5-HIAA, HVA, melatonin, core/skin/rectal temperature, metabolic markers, inflammatory cytokines) were reported by only one study each, and therefore do not qualify for meta-analysis. These remaining outcomes will be summarised narratively rather than pooled quantitatively._

## **Cortisol**
[Back to Table of Content](#table-of-content)

_**Choice of Primary Cortisol Metric (AUC<sub>i</sub>):** For Study 1, three cortisol indices were available: (a) mean cortisol values at individual TSST time points, (b) total cortisol output across the TSST window (AUC<sub>g</sub>), and (c) reactive cortisol relative to baseline (AUC<sub>i</sub>). For the present synthesis, we selected AUC<sub>i</sub> as the primary endpoint.AUC<sub>i</sub> quantifies the incremental change in cortisol above baseline and therefore isolates the reactive component of the HPA-axis response to the TSST. This makes it a direct measure of stress reactivity, which is the physiologically relevant construct when evaluating whether repeated cold-water exposure alters the organism’s responsiveness to acute psychosocial challenge._
_In contrast:_
_a) AUC<sub>g</sub> (“ground”) reflects total cortisol exposure, combining basal secretion with the stress-induced increase. It is therefore less specific to reactivity._
_b) Mean cortisol levels at single time points are more prone to measurement noise and do not capture the integrated dynamic response._

_Given the mechanistic focus of this secondary analysis, whether CWE modifies HPA-axis reactivity rather than overall exposure, AUC<sub>i</sub> provides the most interpretable and construct-valid summary measure. AUC<sub>g</sub> and mean cortisol values are retained and may be used in sensitivity or exploratory analyses._

In [237]:
## ------------------------------------------------------------
## Filter to cortisol outcomes
## Primary metric selection by study
## Study 11 uses Post at 30 min only
## ------------------------------------------------------------

mental_cortisol <- nonmental %>%
  dplyr::filter(stringr::str_detect(
    stringr::str_to_lower(outcome_name), "cortisol"
  )) %>%
  dplyr::filter(
    (study_id == 1  & outcome_name == "Reactive Cortisol (AUCi)") |
      (study_id == 10 & outcome_name == "Cortisol") |
      (study_id == 11 & outcome_name == "serum cortisol")
  ) %>%
  dplyr::filter(
    (study_id %in% c(1, 10) &
       timepoint_label_harmonised %in% c("Pre", "Post")) |
      (study_id == 11 &
         (timepoint_label_harmonised == "Pre" |
            (timepoint_label_harmonised == "Post" &
               abs(timepoint_days_num - 0.020833333) < 1e-8)))
  )

## Quick structural check
mental_cortisol %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id outcome_name             group_harmonised
1   1       Reactive Cortisol (AUCi) Control
2   1       Reactive Cortisol (AUCi) Control
3   1       Reactive Cortisol (AUCi) Intervention
4   1       Reactive Cortisol (AUCi) Intervention
5  10       Cortisol                 Control
6  10       Cortisol                 Control
7  10       Cortisol                 Intervention
8  10       Cortisol                 Intervention
9  11       serum cortisol           SingleGroup
10 11       serum cortisol           SingleGroup
   timepoint_label_harmonised timepoint_days_num
1  Post                       21.00000000
2  Pre                         0.00000000
3  Post                       21.00000000
4  Pre                         0.00000000
5  Post                       56.00000000
6  Pre                         0.00000000
7  Post                       56.00000000
8  Pre                         0.00000000
9  Post                        0.02083333
10 Pre                         0.00000000

In [238]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_cortisol <- mental_cortisol %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [239]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_cortisol <- mental_cortisol %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [240]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

cortisol_prepost <- mental_cortisol %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
cortisol_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id outcome_name             group_harmonised
1   1       Reactive Cortisol (AUCi) Control
2   1       Reactive Cortisol (AUCi) Control
3   1       Reactive Cortisol (AUCi) Intervention
4   1       Reactive Cortisol (AUCi) Intervention
5  10       Cortisol                 Control
6  10       Cortisol                 Control
7  10       Cortisol                 Intervention
8  10       Cortisol                 Intervention
9  11       serum cortisol           SingleGroup
10 11       serum cortisol           SingleGroup
   timepoint_label_harmonised n
1  Post                       1
2  Pre                        1
3  Post                       1
4  Pre                        1
5  Post                       1
6  Pre                        1
7  Post                       1
8  Pre                        1
9  Post                       1
10 Pre                        1

In [241]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

cortisol_wide <- cortisol_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

cortisol_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name             group_harmonised n_change change_mean_calc
1  1       Reactive Cortisol (AUCi) Control          40         -0.09
2  1       Reactive Cortisol (AUCi) Intervention     34         -0.17
3 10       Cortisol                 Control           7        122.05
4 10       Cortisol                 Intervention      5         27.56
5 11       serum cortisol           SingleGroup       8       -160.00
  change_sd_calc
1   0.1300000
2   0.2944486
3 133.0600000
4  65.0600000
5 716.7433292

In [242]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

cortisol_wide <- cortisol_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

cortisol_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name             design
1  1       Reactive Cortisol (AUCi) controlled
2 10       Cortisol                 controlled
3 11       serum cortisol           single_group

In [243]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

cortisol_change_groups <- cortisol_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

cortisol_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name             design       group_harmonised
1  1       Reactive Cortisol (AUCi) controlled   Control
2  1       Reactive Cortisol (AUCi) controlled   Intervention
3 10       Cortisol                 controlled   Control
4 10       Cortisol                 controlled   Intervention
5 11       serum cortisol           single_group SingleGroup
  change_mean_calc change_sd_calc n_change
1   -0.09            0.1300000    40
2   -0.17            0.2944486    34
3  122.05          133.0600000     7
4   27.56           65.0600000     5
5 -160.00          716.7433292     8

In [244]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

cortisol_change_wide_study <- cortisol_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [245]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## More negative yi means greater cortisol reduction under CWE
## More positive yi means less reduction or worse change under CWE
## ------------------------------------------------------------

es_cortisol_controlled <- cortisol_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Cortisol",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_cortisol_controlled

  study_id outcome_name             outcome_domain design_type yi
1  1       Reactive Cortisol (AUCi) Cortisol       controlled  -0.3580192
2 10       Cortisol                 Cortisol       controlled  -0.7856538
  vi
1 0.05532403
2 0.38016186

In [246]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_cortisol_single <- cortisol_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Cortisol",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_cortisol_single

  study_id outcome_name   outcome_domain design_type  yi         vi
1 11       serum cortisol Cortisol       single_group -0.2016288 0.104518

In [247]:
## ------------------------------------------------------------
## Combine all analyzable cortisol effect sizes
## ------------------------------------------------------------

es_cortisol_all <- dplyr::bind_rows(
  es_cortisol_controlled,
  es_cortisol_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("cortisol_", dplyr::row_number())
  )

es_cortisol_all

  study_id outcome_name             outcome_domain design_type  yi
1  1       Reactive Cortisol (AUCi) Cortisol       controlled   -0.3580192
2 10       Cortisol                 Cortisol       controlled   -0.7856538
3 11       serum cortisol           Cortisol       single_group -0.2016288
  vi         effect_id
1 0.05532403 cortisol_1
2 0.38016186 cortisol_2
3 0.10451799 cortisol_3

In [248]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

cortisol_N_by_study_raw <- cortisol_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    N_study
  )

cortisol_N_by_study <- es_cortisol_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    cortisol_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_cortisol <- nrow(cortisol_N_by_study)
N_cortisol_total <- sum(cortisol_N_by_study$N_study, na.rm = TRUE)

cortisol_N_by_design <- cortisol_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nCortisol meta analysis contributing studies\n")
cat(" k studies =", k_cortisol, "\n")
cat(" total N   =", N_cortisol_total, "\n")
print(cortisol_N_by_design)

Cortisol meta analysis contributing studies
 k studies = 3
 total N   = 94
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          2       86
2 single_group        1        8

In [249]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_cortisol <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [250]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

cortisol_main_dat <- es_cortisol_all %>%
  dplyr::arrange(study_id, outcome_name)

cortisol_controlled_dat <- es_cortisol_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nCortisol main dataset\n")
cat(" k effects =", nrow(cortisol_main_dat), "\n")
cat(" studies =", paste(sort(unique(cortisol_main_dat$study_id)), collapse = ", "), "\n")

cat("\nCortisol controlled only dataset\n")
cat(" k effects =", nrow(cortisol_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(cortisol_controlled_dat$study_id)), collapse = ", "), "\n")

Cortisol main dataset
 k effects = 3
 studies = 1, 10, 11

Cortisol controlled only dataset
 k effects = 2
 studies = 1, 10

In [251]:
## ============================================================
## CORTISOL
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_cortisol_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = cortisol_main_dat
)

print(res_cortisol_main_mv)
broom::tidy(res_cortisol_main_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 0.7105, p-val = 0.7010

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.3458  0.1817  -1.9024   2  0.1975  -1.1277  0.4362

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.3457502 0.1817475 -1.902365 0.1974638

In [252]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## ------------------------------------------------------------

res_cortisol_controlled_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = cortisol_controlled_dat
)

print(res_cortisol_controlled_mv)
broom::tidy(res_cortisol_controlled_mv)

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.4199, p-val = 0.5170

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.4123  0.2198  -1.8763   1  0.3117  -3.2047  2.3800

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.4123458 0.2197628 -1.876322 0.3117302

In [253]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

cortisol_model_compare <- dplyr::bind_rows(
  broom::tidy(res_cortisol_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  broom::tidy(res_cortisol_controlled_mv) %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

cortisol_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall -0.3457502 0.1817475 -1.902365 0.1974638
2 controlled_only  overall -0.4123458 0.2197628 -1.876322 0.3117302

In [254]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

cortisol_loo_results <- purrr::map_dfr(
  sort(unique(cortisol_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- cortisol_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

cortisol_loo_results <- cortisol_loo_results %>%
  dplyr::left_join(
    study_labels_cortisol,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

cortisol_loo_results

  dropped_study study_label                     k_effects_remaining
1 11            Reed et al. 2023                2
2 10            Petraskova Touskova et al. 2022 2
3  1            Blades et al. 2024              2
  n_studies_remaining result_type   estimate   se        ci_lb     ci_ub
1 2                   meta_analytic -0.4123458 0.2197628 -3.204697 2.380005
2 2                   meta_analytic -0.3038899 0.1901984 -2.720590 2.112810
3 2                   meta_analytic -0.3275700 0.2863204 -3.965616 3.310476
  p_value   tau2_study   direction               significant
1 0.3117302 2.631386e-11 negative_better_for_cwe FALSE
2 0.3560178 4.309657e-12 negative_better_for_cwe FALSE
3 0.4572874 1.116911e-10 negative_better_for_cwe FALSE

In [255]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

cortisol_loo_controlled_results <- purrr::map_dfr(
  sort(unique(cortisol_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- cortisol_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

cortisol_loo_controlled_results <- cortisol_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_cortisol,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

cortisol_loo_controlled_results

  dropped_study study_label                     k_effects_remaining
1  1            Blades et al. 2024              1
2 10            Petraskova Touskova et al. 2022 1
  n_studies_remaining result_type            estimate   se        ci_lb
1 1                   single_study_remaining -0.7856538 0.6165727 -1.994136
2 1                   single_study_remaining -0.3580192 0.2352106 -0.819032
  ci_ub     p_value tau2_study direction               significant
1 0.4228286 NA      NA         negative_better_for_cwe NA
2 0.1029936 NA      NA         negative_better_for_cwe NA

In [256]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_cortisol <- c(0.00, 0.05, 0.10, 0.20, 0.40)

cortisol_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_cortisol,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = cortisol_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

cortisol_tau_sensitivity <- cortisol_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

cortisol_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb     ci_ub     p_value
1 0.00             -0.3457502 0.1817475 -1.127747 0.4362464 0.1974638
2 0.05             -0.3570355 0.2338201 -1.363082 0.6490111 0.2663244
3 0.10             -0.3674095 0.2730739 -1.542352 0.8075328 0.3107242
4 0.20             -0.3830669 0.3347473 -1.823368 1.0572347 0.3709656
5 0.40             -0.4016366 0.4279561 -2.242983 1.4397096 0.4470588
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [258]:
## ============================================================
## CORTISOL
## Plotting and export section aligned with Stress workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [259]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Cortisol has one effect per study in the current dataset
## ============================================================

cortisol_study_display_all <- cortisol_main_dat %>%
  dplyr::left_join(study_labels_cortisol, by = "study_id") %>%
  dplyr::left_join(
    cortisol_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

cortisol_study_display_controlled <- cortisol_controlled_dat %>%
  dplyr::left_join(study_labels_cortisol, by = "study_id") %>%
  dplyr::left_join(
    cortisol_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [260]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

cortisol_study_display_all <- cortisol_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

cortisol_study_display_controlled <- cortisol_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [261]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_cortisol_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = cortisol_study_display_all
)

res_cortisol_controlled_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = cortisol_study_display_controlled
)

cortisol_study_display_all <- cortisol_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_cortisol_all_plot) / sum(weights(res_cortisol_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

cortisol_study_display_controlled <- cortisol_study_display_controlled %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_cortisol_controlled_plot) / sum(weights(res_cortisol_controlled_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

In [262]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Cortisol"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for cortisol", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Cortisol"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for cortisol", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [263]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = cortisol_study_display_all,
  model = res_cortisol_all_plot,
  file = file.path(graph_path, "forest_cortisol_all_designs_journal_style.pdf"),
  outcome_title = "Cortisol, all designs"
)

save_forest_controlled_journal(
  dat = cortisol_study_display_controlled,
  model = res_cortisol_controlled_plot,
  file = file.path(graph_path, "forest_cortisol_controlled_journal_style.pdf"),
  outcome_title = "Cortisol, controlled studies"
)

agg_record_937313478
                   2

agg_record_937313478
                   2

In [264]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

cortisol_total_N_all <- sum(cortisol_N_by_study$N_study, na.rm = TRUE)

cortisol_total_N_controlled <- cortisol_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

cortisol_loo_plot_all <- cortisol_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    cortisol_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = cortisol_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

cortisol_loo_plot_controlled <- cortisol_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    cortisol_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = cortisol_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [265]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

cortisol_tau_plot <- cortisol_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [266]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = cortisol_loo_plot_all,
  file = file.path(graph_path, "forest_cortisol_leave_one_out_all_designs.pdf"),
  title_left = "Cortisol, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_cortisol_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = cortisol_loo_plot_controlled,
  file = file.path(graph_path, "forest_cortisol_leave_one_out_controlled_only.pdf"),
  title_left = "Cortisol, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = as.numeric(res_cortisol_controlled_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = cortisol_tau_plot,
  file = file.path(graph_path, "forest_cortisol_tau_sensitivity.pdf"),
  title_left = "Cortisol, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_cortisol_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1276687126
                    2

agg_record_1276687126
                    2

agg_record_1276687126
                    2

In [267]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_cortisol_study_display_all <- make_study_effect_table(cortisol_study_display_all)

tab_cortisol_study_display_controlled <- make_study_effect_table(cortisol_study_display_controlled)

tab_cortisol_effect_sizes_all <- es_cortisol_all %>%
  dplyr::left_join(study_labels_cortisol, by = "study_id") %>%
  dplyr::left_join(cortisol_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_cortisol_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(cortisol_main_dat), nrow(cortisol_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(cortisol_main_dat$study_id),
    dplyr::n_distinct(cortisol_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_cortisol_main_mv$b),
    as.numeric(res_cortisol_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_cortisol_main_mv$se),
    as.numeric(res_cortisol_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_cortisol_main_mv$ci.lb),
    as.numeric(res_cortisol_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_cortisol_main_mv$ci.ub),
    as.numeric(res_cortisol_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_cortisol_main_mv$pval),
    as.numeric(res_cortisol_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_cortisol_main_mv$sigma2),
    as.numeric(res_cortisol_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_cortisol_loo_all <- cortisol_loo_results %>%
  round_df_2()

tab_cortisol_loo_controlled <- cortisol_loo_controlled_results %>%
  round_df_2()

tab_cortisol_tau <- cortisol_tau_sensitivity %>%
  round_df_2()

tab_cortisol_N_by_study <- cortisol_N_by_study %>%
  round_df_2()

tab_cortisol_N_by_design <- cortisol_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_cortisol_effect_sizes_all,
  file.path(table_path, "cortisol_effect_sizes_all.csv")
)

readr::write_csv(
  tab_cortisol_study_display_all,
  file.path(table_path, "cortisol_study_display_main.csv")
)

readr::write_csv(
  tab_cortisol_study_display_controlled,
  file.path(table_path, "cortisol_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_cortisol_model_compare,
  file.path(table_path, "cortisol_model_comparison.csv")
)

readr::write_csv(
  tab_cortisol_loo_all,
  file.path(table_path, "cortisol_leave_one_out_all.csv")
)

readr::write_csv(
  tab_cortisol_loo_controlled,
  file.path(table_path, "cortisol_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_cortisol_tau,
  file.path(table_path, "cortisol_tau_sensitivity.csv")
)

readr::write_csv(
  tab_cortisol_N_by_study,
  file.path(table_path, "cortisol_sample_size_by_study.csv")
)

readr::write_csv(
  tab_cortisol_N_by_design,
  file.path(table_path, "cortisol_sample_size_by_design.csv")
)

In [268]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved cortisol PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved cortisol tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "cortisol.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "cortisol.*csv$", full.names = TRUE)

Saved cortisol PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved cortisol tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_cortisol_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_cortisol_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_cortisol_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_cortisol_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_cortisol_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/cortisol_tau_sensitivity.csv"

## **β-endorphin**
[Back to Table of Content](#table-of-content)

In [270]:
## ------------------------------------------------------------
## Filter to beta endorphin outcomes
## Study 7 keeps only Autumn and Winter mapping to Pre and Post
## Study 11 keeps Pre and Post at 30 min
## ------------------------------------------------------------

mental_beta <- nonmental %>%
  dplyr::filter(
    stringr::str_detect(stringr::str_to_lower(outcome_name), "endorph")
  ) %>%
  dplyr::filter(
    (study_id == 7 &
       timepoint_label_harmonised %in% c("Pre", "Post") &
       !is.na(timepoint_label) &
       stringr::str_detect(timepoint_label, "Autumn|Winter")) |
      (study_id == 11 &
         (timepoint_label_harmonised == "Pre" |
            (timepoint_label_harmonised == "Post" &
               abs(timepoint_days_num - 0.020833333) < 1e-8)))
  )

## Quick structural check
mental_beta %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_label,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id outcome_name       group_harmonised timepoint_label_harmonised
1  7       β-Endorphin        Control          Post
2  7       β-Endorphin        Control          Pre
3  7       β-Endorphin        Intervention     Post
4  7       β-Endorphin        Intervention     Pre
5 11       Serum β-endorphins SingleGroup      Post
6 11       Serum β-endorphins SingleGroup      Pre
  timepoint_label timepoint_days_num
1 Winter (Post)           NA
2 Autumn (Pre)            NA
3 Winter (Post)           NA
4 Autumn (Pre)            NA
5 Post            0.02083333
6 Pre             0.00000000

In [271]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_beta <- mental_beta %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [272]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_beta <- mental_beta %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [273]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

beta_prepost <- mental_beta %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
beta_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id outcome_name       group_harmonised timepoint_label_harmonised n
1  7       β-Endorphin        Control          Post                       1
2  7       β-Endorphin        Control          Pre                        1
3  7       β-Endorphin        Intervention     Post                       1
4  7       β-Endorphin        Intervention     Pre                        1
5 11       Serum β-endorphins SingleGroup      Post                       1
6 11       Serum β-endorphins SingleGroup      Pre                        1

In [274]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

beta_wide <- beta_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

beta_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name       group_harmonised n_change change_mean_calc
1  7       β-Endorphin        Control          10       -1.00
2  7       β-Endorphin        Intervention     21        1.00
3 11       Serum β-endorphins SingleGroup       7       -0.18
  change_sd_calc
1 8.345058
2 3.874274
3 4.105266

In [275]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

beta_wide <- beta_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

beta_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name       design
1  7       β-Endorphin        controlled
2 11       Serum β-endorphins single_group

In [276]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

beta_change_groups <- beta_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

beta_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name       design       group_harmonised change_mean_calc
1  7       β-Endorphin        controlled   Control          -1.00
2  7       β-Endorphin        controlled   Intervention      1.00
3 11       Serum β-endorphins single_group SingleGroup      -0.18
  change_sd_calc n_change
1 8.345058       10
2 3.874274       21
3 4.105266        7

In [277]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

beta_change_wide_study <- beta_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [278]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## Negative yi means lower beta endorphin change under CWE
## Positive yi means higher beta endorphin change under CWE
##
## Keep this only if that direction is what you want
## ------------------------------------------------------------

es_beta_controlled <- beta_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Beta-Endorphin",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_beta_controlled

  study_id outcome_name outcome_domain design_type yi        vi
1 7        β-Endorphin  Beta-Endorphin controlled  0.3445099 0.1497962

In [279]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_beta_single <- beta_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Beta-Endorphin",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_beta_single

  study_id outcome_name       outcome_domain design_type  yi          vi
1 11       Serum β-endorphins Beta-Endorphin single_group -0.03897433 0.1129833

In [280]:
## ------------------------------------------------------------
## Combine all analyzable beta endorphin effect sizes
## ------------------------------------------------------------

es_beta_all <- dplyr::bind_rows(
  es_beta_controlled,
  es_beta_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("beta_endorphin_", dplyr::row_number())
  )

es_beta_all

  study_id outcome_name       outcome_domain design_type  yi          vi
1  7       β-Endorphin        Beta-Endorphin controlled    0.34450990 0.1497962
2 11       Serum β-endorphins Beta-Endorphin single_group -0.03897433 0.1129833
  effect_id
1 beta_endorphin_1
2 beta_endorphin_2

In [281]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

beta_N_by_study_raw <- beta_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    N_study
  )

beta_N_by_study <- es_beta_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    beta_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_beta <- nrow(beta_N_by_study)
N_beta_total <- sum(beta_N_by_study$N_study, na.rm = TRUE)

beta_N_by_design <- beta_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nBeta endorphin meta analysis contributing studies\n")
cat(" k studies =", k_beta, "\n")
cat(" total N   =", N_beta_total, "\n")
print(beta_N_by_design)

Beta endorphin meta analysis contributing studies
 k studies = 2
 total N   = 38
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          1       31
2 single_group        1        7

In [282]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_beta <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [283]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

beta_main_dat <- es_beta_all %>%
  dplyr::arrange(study_id, outcome_name)

beta_controlled_dat <- es_beta_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nBeta endorphin main dataset\n")
cat(" k effects =", nrow(beta_main_dat), "\n")
cat(" studies =", paste(sort(unique(beta_main_dat$study_id)), collapse = ", "), "\n")

cat("\nBeta endorphin controlled only dataset\n")
cat(" k effects =", nrow(beta_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(beta_controlled_dat$study_id)), collapse = ", "), "\n")

Beta endorphin main dataset
 k effects = 2
 studies = 7, 11

Beta endorphin controlled only dataset
 k effects = 1
 studies = 7

In [284]:
## ============================================================
## BETA ENDORPHIN
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_beta_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = beta_main_dat
)

print(res_beta_main_mv)
broom::tidy(res_beta_main_mv)

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.5596, p-val = 0.4544

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.1259  0.2538  0.4961   1  0.7068  -3.0987  3.3505

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.1259065 0.2537826 0.4961196 0.7068121

In [285]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## If only one controlled study is available this becomes
## a descriptive single study result
## ------------------------------------------------------------

if (nrow(beta_controlled_dat) >= 2) {

  res_beta_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = beta_controlled_dat
  )

  print(res_beta_controlled_mv)

  beta_controlled_tidy <- broom::tidy(res_beta_controlled_mv)

} else if (nrow(beta_controlled_dat) == 1) {

  res_beta_controlled_mv <- NULL

  beta_controlled_tidy <- beta_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(beta_controlled_tidy)

} else {

  res_beta_controlled_mv <- NULL

  beta_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(beta_controlled_tidy)
}

     term    type  estimate std.error statistic p.value
1 overall summary 0.3445099 0.3870352        NA      NA

In [286]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

beta_model_compare <- dplyr::bind_rows(
  broom::tidy(res_beta_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  beta_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

beta_model_compare

  model            term    estimate  std.error statistic p.value
1 main_all_designs overall 0.1259065 0.2537826 0.4961196 0.7068121
2 controlled_only  overall 0.3445099 0.3870352        NA        NA

In [287]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

beta_loo_results <- purrr::map_dfr(
  sort(unique(beta_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- beta_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

beta_loo_results <- beta_loo_results %>%
  dplyr::left_join(
    study_labels_beta,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

beta_loo_results

  dropped_study study_label         k_effects_remaining n_studies_remaining
1  7            Hirvonen et al 2002 1                   1
2 11            Reed et al. 2023    1                   1
  result_type            estimate    se        ci_lb      ci_ub     p_value
1 single_study_remaining -0.03897433 0.3361299 -0.6977888 0.6198402 NA
2 single_study_remaining  0.34450990 0.3870352 -0.4140791 1.1030989 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         positive_worse_for_cwe  NA

In [288]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

beta_loo_controlled_results <- purrr::map_dfr(
  sort(unique(beta_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- beta_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

beta_loo_controlled_results <- beta_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_beta,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

beta_loo_controlled_results

  dropped_study study_label         k_effects_remaining n_studies_remaining
1 7             Hirvonen et al 2002 0                   0
  result_type       estimate se ci_lb ci_ub p_value tau2_study direction
1 no_data_remaining NA       NA NA    NA    NA      NA         NA
  significant
1 NA

In [289]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_beta <- c(0.00, 0.05, 0.10, 0.20, 0.40)

beta_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_beta,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = beta_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

beta_tau_sensitivity <- beta_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

beta_tau_sensitivity

  tau2_study_fixed estimate  se        ci_lb     ci_ub    p_value
1 0.00             0.1259065 0.2537826 -3.098707 3.350520 0.7068121
2 0.05             0.1333108 0.2996014 -3.673486 3.940107 0.7334758
3 0.10             0.1375152 0.3390616 -4.170671 4.445702 0.7547080
4 0.20             0.1421178 0.4064280 -5.022039 5.306275 0.7858504
5 0.40             0.1461261 0.5151467 -6.399433 6.691685 0.8240391
  direction              significant
1 positive_worse_for_cwe FALSE
2 positive_worse_for_cwe FALSE
3 positive_worse_for_cwe FALSE
4 positive_worse_for_cwe FALSE
5 positive_worse_for_cwe FALSE

In [290]:
## ============================================================
## BETA ENDORPHIN
## Plotting and export section aligned with Sleep workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [291]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Beta endorphin has one effect per study in the current dataset
## ============================================================

beta_study_display_all <- beta_main_dat %>%
  dplyr::left_join(study_labels_beta, by = "study_id") %>%
  dplyr::left_join(
    beta_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

beta_study_display_controlled <- beta_controlled_dat %>%
  dplyr::left_join(study_labels_beta, by = "study_id") %>%
  dplyr::left_join(
    beta_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [292]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

beta_study_display_all <- beta_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

beta_study_display_controlled <- beta_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [293]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_beta_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = beta_study_display_all
)

if (nrow(beta_study_display_controlled) >= 2) {
  res_beta_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = beta_study_display_controlled
  )
} else {
  res_beta_controlled_plot <- NULL
}

beta_study_display_all <- beta_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_beta_all_plot) / sum(weights(res_beta_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_beta_controlled_plot)) {
  beta_study_display_controlled <- beta_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_beta_controlled_plot) / sum(weights(res_beta_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  beta_study_display_controlled <- beta_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [294]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Beta-Endorphin"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for beta endorphin", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Beta-Endorphin"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled beta endorphin study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for beta endorphin", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [295]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = beta_study_display_all,
  model = res_beta_all_plot,
  file = file.path(graph_path, "forest_beta_endorphin_all_designs_journal_style.pdf"),
  outcome_title = "Beta endorphin, all designs"
)

save_forest_controlled_journal(
  dat = beta_study_display_controlled,
  model = res_beta_controlled_plot,
  file = file.path(graph_path, "forest_beta_endorphin_controlled_journal_style.pdf"),
  outcome_title = "Beta endorphin, controlled studies"
)

agg_record_88591694
                  2

agg_record_88591694
                  2

In [296]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

beta_total_N_all <- sum(beta_N_by_study$N_study, na.rm = TRUE)

beta_total_N_controlled <- beta_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

beta_loo_plot_all <- beta_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    beta_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = beta_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

beta_loo_plot_controlled <- beta_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    beta_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = beta_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [297]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

beta_tau_plot <- beta_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [298]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = beta_loo_plot_all,
  file = file.path(graph_path, "forest_beta_endorphin_leave_one_out_all_designs.pdf"),
  title_left = "Beta endorphin, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_beta_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = beta_loo_plot_controlled,
  file = file.path(graph_path, "forest_beta_endorphin_leave_one_out_controlled_only.pdf"),
  title_left = "Beta endorphin, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_beta_controlled_mv)) as.numeric(res_beta_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = beta_tau_plot,
  file = file.path(graph_path, "forest_beta_endorphin_tau_sensitivity.pdf"),
  title_left = "Beta endorphin, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_beta_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_624613994
                   2

agg_record_624613994
                   2

In [299]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_beta_study_display_all <- make_study_effect_table(beta_study_display_all)

tab_beta_study_display_controlled <- make_study_effect_table(beta_study_display_controlled)

tab_beta_effect_sizes_all <- es_beta_all %>%
  dplyr::left_join(study_labels_beta, by = "study_id") %>%
  dplyr::left_join(beta_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_beta_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(beta_main_dat), nrow(beta_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(beta_main_dat$study_id),
    dplyr::n_distinct(beta_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_beta_main_mv$b),
    if (nrow(beta_controlled_dat) == 1) beta_controlled_dat$yi[1] else as.numeric(res_beta_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_beta_main_mv$se),
    if (nrow(beta_controlled_dat) == 1) sqrt(beta_controlled_dat$vi[1]) else as.numeric(res_beta_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_beta_main_mv$ci.lb),
    if (nrow(beta_controlled_dat) == 1) beta_controlled_dat$yi[1] - 1.96 * sqrt(beta_controlled_dat$vi[1]) else as.numeric(res_beta_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_beta_main_mv$ci.ub),
    if (nrow(beta_controlled_dat) == 1) beta_controlled_dat$yi[1] + 1.96 * sqrt(beta_controlled_dat$vi[1]) else as.numeric(res_beta_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_beta_main_mv$pval),
    if (nrow(beta_controlled_dat) == 1) NA_real_ else as.numeric(res_beta_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_beta_main_mv$sigma2),
    if (nrow(beta_controlled_dat) == 1) NA_real_ else as.numeric(res_beta_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_beta_loo_all <- beta_loo_results %>%
  round_df_2()

tab_beta_loo_controlled <- beta_loo_controlled_results %>%
  round_df_2()

tab_beta_tau <- beta_tau_sensitivity %>%
  round_df_2()

tab_beta_N_by_study <- beta_N_by_study %>%
  round_df_2()

tab_beta_N_by_design <- beta_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_beta_effect_sizes_all,
  file.path(table_path, "beta_endorphin_effect_sizes_all.csv")
)

readr::write_csv(
  tab_beta_study_display_all,
  file.path(table_path, "beta_endorphin_study_display_main.csv")
)

readr::write_csv(
  tab_beta_study_display_controlled,
  file.path(table_path, "beta_endorphin_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_beta_model_compare,
  file.path(table_path, "beta_endorphin_model_comparison.csv")
)

readr::write_csv(
  tab_beta_loo_all,
  file.path(table_path, "beta_endorphin_leave_one_out_all.csv")
)

readr::write_csv(
  tab_beta_loo_controlled,
  file.path(table_path, "beta_endorphin_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_beta_tau,
  file.path(table_path, "beta_endorphin_tau_sensitivity.csv")
)

readr::write_csv(
  tab_beta_N_by_study,
  file.path(table_path, "beta_endorphin_sample_size_by_study.csv")
)

readr::write_csv(
  tab_beta_N_by_design,
  file.path(table_path, "beta_endorphin_sample_size_by_design.csv")
)

In [300]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved beta endorphin PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved beta endorphin tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "beta_endorphin.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "beta_endorphin.*csv$", full.names = TRUE)

Saved beta endorphin PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved beta endorphin tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_beta_endorphin_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_beta_endorphin_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_beta_endorphin_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_beta_endorphin_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_beta_endorphin_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/beta_endorphin_tau_sensitivity.csv"

## **Systolic Blood Pressure (SBP)**
[Back to Table of Content](#table-of-content)

In [301]:
## ------------------------------------------------------------
## Filter to systolic blood pressure outcomes
## Keep only Pre and Post
## ------------------------------------------------------------

mental_sbp <- nonmental %>%
  dplyr::filter(
    outcome_name %in% c("Systolic Blood Pressure (SBP)", "Systolic BP"),
    timepoint_label_harmonised %in% c("Pre", "Post")
  )

## Quick structural check
mental_sbp %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_label,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  )

   study_id outcome_name                  group_harmonised
1   3       Systolic Blood Pressure (SBP) Control
2   3       Systolic Blood Pressure (SBP) Control
3   3       Systolic Blood Pressure (SBP) Intervention
4   3       Systolic Blood Pressure (SBP) Intervention
5   6       Systolic BP                   Control
6   6       Systolic BP                   Control
7   6       Systolic BP                   Intervention
8   6       Systolic BP                   Intervention
9   7       Systolic BP                   Control
10  7       Systolic BP                   Control
11  7       Systolic BP                   Intervention
12  7       Systolic BP                   Intervention
13 11       Systolic BP                   SingleGroup
14 11       Systolic BP                   SingleGroup
   timepoint_label_harmonised timepoint_label     timepoint_days_num
1  Post                       Post                15.00000000
2  Pre                        Pre                  0.00000000
3  Post                       Post                15.00000000
4  Pre                        Pre                  0.00000000
5  Post                       Day 5 (whole week)           NA
6  Pre                        Day 1                        NA
7  Post                       Day 5 (whole week)           NA
8  Pre                        Day 1                        NA
9  Post                       Spring (Post)\r\r\n          NA
10 Pre                        Autumn (Pre)                 NA
11 Post                       Spring (Post)                NA
12 Pre                        Autumn (Pre)                 NA
13 Post                       Post                 0.02083333
14 Pre                        Pre                          NA

In [302]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_sbp <- mental_sbp %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [303]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_sbp <- mental_sbp %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [304]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

sbp_prepost <- mental_sbp %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
sbp_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id outcome_name                  group_harmonised
1   3       Systolic Blood Pressure (SBP) Control
2   3       Systolic Blood Pressure (SBP) Control
3   3       Systolic Blood Pressure (SBP) Intervention
4   3       Systolic Blood Pressure (SBP) Intervention
5   6       Systolic BP                   Control
6   6       Systolic BP                   Control
7   6       Systolic BP                   Intervention
8   6       Systolic BP                   Intervention
9   7       Systolic BP                   Control
10  7       Systolic BP                   Control
11  7       Systolic BP                   Intervention
12  7       Systolic BP                   Intervention
13 11       Systolic BP                   SingleGroup
14 11       Systolic BP                   SingleGroup
   timepoint_label_harmonised n
1  Post                       1
2  Pre                        1
3  Post                       1
4  Pre                        1
5  Post                       1
6  Pre                        1
7  Post                       1
8  Pre                        1
9  Post                       1
10 Pre                        1
11 Post                       1
12 Pre                        1
13 Post                       1
14 Pre                        1

In [305]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

sbp_wide <- sbp_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

sbp_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name                  group_harmonised n_change
1  3       Systolic Blood Pressure (SBP) Control           21
2  3       Systolic Blood Pressure (SBP) Intervention      20
3  6       Systolic BP                   Control          121
4  6       Systolic BP                   Intervention     121
5  7       Systolic BP                   Control           11
6  7       Systolic BP                   Intervention      25
7 11       Systolic BP                   SingleGroup       16
  change_mean_calc change_sd_calc
1 -1.0              9.165151
2 -2.0             10.000000
3 -2.0             18.083141
4 -1.0             17.000000
5 -6.5             17.186914
6 -5.7             12.101240
7 14.0             15.394804

In [306]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

sbp_wide <- sbp_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

sbp_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name                  design
1  3       Systolic Blood Pressure (SBP) controlled
2  6       Systolic BP                   controlled
3  7       Systolic BP                   controlled
4 11       Systolic BP                   single_group

In [307]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

sbp_change_groups <- sbp_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

sbp_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name                  design       group_harmonised
1  3       Systolic Blood Pressure (SBP) controlled   Control
2  3       Systolic Blood Pressure (SBP) controlled   Intervention
3  6       Systolic BP                   controlled   Control
4  6       Systolic BP                   controlled   Intervention
5  7       Systolic BP                   controlled   Control
6  7       Systolic BP                   controlled   Intervention
7 11       Systolic BP                   single_group SingleGroup
  change_mean_calc change_sd_calc n_change
1 -1.0              9.165151       21
2 -2.0             10.000000       20
3 -2.0             18.083141      121
4 -1.0             17.000000      121
5 -6.5             17.186914       11
6 -5.7             12.101240       25
7 14.0             15.394804       16

In [308]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

sbp_change_wide_study <- sbp_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [309]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## Negative yi means lower systolic blood pressure change under CWE
## Positive yi means higher systolic blood pressure change under CWE
##
## Keep this only if that direction is what you want
## ------------------------------------------------------------

es_sbp_controlled <- sbp_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Systolic blood pressure",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_sbp_controlled

  study_id outcome_name                  outcome_domain          design_type
1 3        Systolic Blood Pressure (SBP) Systolic blood pressure controlled
2 6        Systolic BP                   Systolic blood pressure controlled
3 7        Systolic BP                   Systolic blood pressure controlled
  yi          vi
1 -0.10235131 0.09775964
2  0.05680201 0.01653570
3  0.05670964 0.13095894

In [310]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_sbp_single <- sbp_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Systolic blood pressure",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_sbp_single

  study_id outcome_name outcome_domain          design_type  yi
1 11       Systolic BP  Systolic blood pressure single_group 0.8660931
  vi
1 0.08013051

In [311]:
## ------------------------------------------------------------
## Combine all analyzable systolic blood pressure effect sizes
## ------------------------------------------------------------

es_sbp_all <- dplyr::bind_rows(
  es_sbp_controlled,
  es_sbp_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("sbp_", dplyr::row_number())
  )

es_sbp_all

  study_id outcome_name                  outcome_domain          design_type
1  3       Systolic Blood Pressure (SBP) Systolic blood pressure controlled
2  6       Systolic BP                   Systolic blood pressure controlled
3  7       Systolic BP                   Systolic blood pressure controlled
4 11       Systolic BP                   Systolic blood pressure single_group
  yi          vi         effect_id
1 -0.10235131 0.09775964 sbp_1
2  0.05680201 0.01653570 sbp_2
3  0.05670964 0.13095894 sbp_3
4  0.86609307 0.08013051 sbp_4

In [312]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

sbp_N_by_study_raw <- sbp_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    N_study
  )

sbp_N_by_study <- es_sbp_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    sbp_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_sbp <- nrow(sbp_N_by_study)
N_sbp_total <- sum(sbp_N_by_study$N_study, na.rm = TRUE)

sbp_N_by_design <- sbp_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nSystolic blood pressure meta analysis contributing studies\n")
cat(" k studies =", k_sbp, "\n")
cat(" total N   =", N_sbp_total, "\n")
print(sbp_N_by_design)

Systolic blood pressure meta analysis contributing studies
 k studies = 4
 total N   = 335
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          3      319
2 single_group        1       16

In [313]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_sbp <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [314]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

sbp_main_dat <- es_sbp_all %>%
  dplyr::arrange(study_id, outcome_name)

sbp_controlled_dat <- es_sbp_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nSystolic blood pressure main dataset\n")
cat(" k effects =", nrow(sbp_main_dat), "\n")
cat(" studies =", paste(sort(unique(sbp_main_dat$study_id)), collapse = ", "), "\n")

cat("\nSystolic blood pressure controlled only dataset\n")
cat(" k effects =", nrow(sbp_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(sbp_controlled_dat$study_id)), collapse = ", "), "\n")

Systolic blood pressure main dataset
 k effects = 4
 studies = 3, 6, 7, 11

Systolic blood pressure controlled only dataset
 k effects = 3
 studies = 3, 6, 7

In [315]:
## ============================================================
## SYSTOLIC BLOOD PRESSURE
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_sbp_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = sbp_main_dat
)

print(res_sbp_main_mv)
broom::tidy(res_sbp_main_mv)

Multivariate Meta-Analysis Model (k = 4; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.1079  0.3285      4     no  study_id

Test for Heterogeneity:
Q(df = 3) = 7.6426, p-val = 0.0540

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.2144  0.2113  1.0145   3  0.3851  -0.4581  0.8868

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.2143605 0.2112974 1.014497  0.3850513

In [316]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## If only one controlled study is available this becomes
## a descriptive single study result
## ------------------------------------------------------------

if (nrow(sbp_controlled_dat) >= 2) {

  res_sbp_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = sbp_controlled_dat
  )

  print(res_sbp_controlled_mv)

  sbp_controlled_tidy <- broom::tidy(res_sbp_controlled_mv)

} else if (nrow(sbp_controlled_dat) == 1) {

  res_sbp_controlled_mv <- NULL

  sbp_controlled_tidy <- sbp_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(sbp_controlled_tidy)

} else {

  res_sbp_controlled_mv <- NULL

  sbp_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(sbp_controlled_tidy)
}

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 0.2252, p-val = 0.8935

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.0360  0.1130  0.3187   2  0.7801  -0.4501  0.5221

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [317]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

sbp_model_compare <- dplyr::bind_rows(
  broom::tidy(res_sbp_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  sbp_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

sbp_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall 0.21436049 0.2112974 1.0144966 0.3850513
2 controlled_only  overall 0.03601181 0.1129815 0.3187409 0.7801314

In [318]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

sbp_loo_results <- purrr::map_dfr(
  sort(unique(sbp_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- sbp_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

sbp_loo_results <- sbp_loo_results %>%
  dplyr::left_join(
    study_labels_sbp,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

sbp_loo_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1  3            Ketelhut et al. 2023 3                   3
2  6            Hinkka et al 2016    3                   3
3  7            Hirvonen et al 2002  3                   3
4 11            Reed et al. 2023     3                   3
  result_type   estimate   se        ci_lb      ci_ub     p_value
1 meta_analytic 0.30933852 0.2668056 -0.8386335 1.4573105 0.3659989
2 meta_analytic 0.29387695 0.3134568 -1.0548190 1.6425729 0.4474533
3 meta_analytic 0.25918284 0.2813853 -0.9515205 1.4698861 0.4542384
4 meta_analytic 0.03601181 0.1129815 -0.4501082 0.5221318 0.7801314
  tau2_study   direction              significant
1 1.479720e-01 positive_worse_for_cwe FALSE
2 1.932808e-01 positive_worse_for_cwe FALSE
3 1.782014e-01 positive_worse_for_cwe FALSE
4 3.745693e-12 positive_worse_for_cwe FALSE

In [319]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

sbp_loo_controlled_results <- purrr::map_dfr(
  sort(unique(sbp_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- sbp_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

sbp_loo_controlled_results <- sbp_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_sbp,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

sbp_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 3             Ketelhut et al. 2023 2                   2
2 6             Hinkka et al 2016    2                   2
3 7             Hirvonen et al 2002  2                   2
  result_type   estimate    se        ci_lb     ci_ub    p_value   tau2_study
1 meta_analytic  0.05679165 0.1211688 -1.482804 1.596387 0.7209730 7.244621e-12
2 meta_analytic -0.03436496 0.2365901 -3.040528 2.971798 0.9081725 2.435625e-12
3 meta_analytic  0.03377648 0.1189260 -1.477322 1.544875 0.8238310 6.593179e-12
  direction               significant
1 positive_worse_for_cwe  FALSE
2 negative_better_for_cwe FALSE
3 positive_worse_for_cwe  FALSE

In [320]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_sbp <- c(0.00, 0.05, 0.10, 0.20, 0.40)

sbp_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_sbp,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = sbp_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

sbp_tau_sensitivity <- sbp_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

sbp_tau_sensitivity

  tau2_study_fixed estimate  se        ci_lb      ci_ub     p_value
1 0.00             0.1500739 0.1049323 -0.1838676 0.4840153 0.2480237
2 0.05             0.2036672 0.1690116 -0.3342031 0.7415374 0.3145724
3 0.10             0.2135953 0.2062009 -0.4426279 0.8698185 0.3764384
4 0.20             0.2184039 0.2620003 -0.6153981 1.0522060 0.4656681
5 0.40             0.2198472 0.3455286 -0.8797791 1.3194735 0.5698272
  direction              significant
1 positive_worse_for_cwe FALSE
2 positive_worse_for_cwe FALSE
3 positive_worse_for_cwe FALSE
4 positive_worse_for_cwe FALSE
5 positive_worse_for_cwe FALSE

In [321]:
## ============================================================
## SYSTOLIC BLOOD PRESSURE
## Plotting and export section aligned with beta workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [322]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Systolic blood pressure has one effect per study in the current dataset
## ============================================================

sbp_study_display_all <- sbp_main_dat %>%
  dplyr::left_join(study_labels_sbp, by = "study_id") %>%
  dplyr::left_join(
    sbp_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

sbp_study_display_controlled <- sbp_controlled_dat %>%
  dplyr::left_join(study_labels_sbp, by = "study_id") %>%
  dplyr::left_join(
    sbp_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [323]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

sbp_study_display_all <- sbp_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

sbp_study_display_controlled <- sbp_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [324]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_sbp_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = sbp_study_display_all
)

if (nrow(sbp_study_display_controlled) >= 2) {
  res_sbp_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = sbp_study_display_controlled
  )
} else {
  res_sbp_controlled_plot <- NULL
}

sbp_study_display_all <- sbp_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_sbp_all_plot) / sum(weights(res_sbp_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_sbp_controlled_plot)) {
  sbp_study_display_controlled <- sbp_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_sbp_controlled_plot) / sum(weights(res_sbp_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  sbp_study_display_controlled <- sbp_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [325]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Systolic blood pressure"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for systolic blood pressure", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Systolic blood pressure"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled systolic blood pressure study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for systolic blood pressure", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [326]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = sbp_study_display_all,
  model = res_sbp_all_plot,
  file = file.path(graph_path, "forest_systolic_blood_pressure_all_designs_journal_style.pdf"),
  outcome_title = "Systolic blood pressure, all designs"
)

save_forest_controlled_journal(
  dat = sbp_study_display_controlled,
  model = res_sbp_controlled_plot,
  file = file.path(graph_path, "forest_systolic_blood_pressure_controlled_journal_style.pdf"),
  outcome_title = "Systolic blood pressure, controlled studies"
)

agg_record_246365435
                   2

agg_record_246365435
                   2

In [327]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

sbp_total_N_all <- sum(sbp_N_by_study$N_study, na.rm = TRUE)

sbp_total_N_controlled <- sbp_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

sbp_loo_plot_all <- sbp_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    sbp_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = sbp_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

sbp_loo_plot_controlled <- sbp_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    sbp_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = sbp_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [328]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

sbp_tau_plot <- sbp_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [329]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = sbp_loo_plot_all,
  file = file.path(graph_path, "forest_systolic_blood_pressure_leave_one_out_all_designs.pdf"),
  title_left = "Systolic blood pressure, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_sbp_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = sbp_loo_plot_controlled,
  file = file.path(graph_path, "forest_systolic_blood_pressure_leave_one_out_controlled_only.pdf"),
  title_left = "Systolic blood pressure, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_sbp_controlled_mv)) as.numeric(res_sbp_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = sbp_tau_plot,
  file = file.path(graph_path, "forest_systolic_blood_pressure_tau_sensitivity.pdf"),
  title_left = "Systolic blood pressure, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_sbp_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1223597726
                    2

agg_record_1223597726
                    2

agg_record_1223597726
                    2

In [330]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_sbp_study_display_all <- make_study_effect_table(sbp_study_display_all)

tab_sbp_study_display_controlled <- make_study_effect_table(sbp_study_display_controlled)

tab_sbp_effect_sizes_all <- es_sbp_all %>%
  dplyr::left_join(study_labels_sbp, by = "study_id") %>%
  dplyr::left_join(sbp_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_sbp_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(sbp_main_dat), nrow(sbp_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(sbp_main_dat$study_id),
    dplyr::n_distinct(sbp_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_sbp_main_mv$b),
    if (nrow(sbp_controlled_dat) == 1) sbp_controlled_dat$yi[1] else as.numeric(res_sbp_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_sbp_main_mv$se),
    if (nrow(sbp_controlled_dat) == 1) sqrt(sbp_controlled_dat$vi[1]) else as.numeric(res_sbp_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_sbp_main_mv$ci.lb),
    if (nrow(sbp_controlled_dat) == 1) sbp_controlled_dat$yi[1] - 1.96 * sqrt(sbp_controlled_dat$vi[1]) else as.numeric(res_sbp_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_sbp_main_mv$ci.ub),
    if (nrow(sbp_controlled_dat) == 1) sbp_controlled_dat$yi[1] + 1.96 * sqrt(sbp_controlled_dat$vi[1]) else as.numeric(res_sbp_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_sbp_main_mv$pval),
    if (nrow(sbp_controlled_dat) == 1) NA_real_ else as.numeric(res_sbp_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_sbp_main_mv$sigma2),
    if (nrow(sbp_controlled_dat) == 1) NA_real_ else as.numeric(res_sbp_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_sbp_loo_all <- sbp_loo_results %>%
  round_df_2()

tab_sbp_loo_controlled <- sbp_loo_controlled_results %>%
  round_df_2()

tab_sbp_tau <- sbp_tau_sensitivity %>%
  round_df_2()

tab_sbp_N_by_study <- sbp_N_by_study %>%
  round_df_2()

tab_sbp_N_by_design <- sbp_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_sbp_effect_sizes_all,
  file.path(table_path, "systolic_blood_pressure_effect_sizes_all.csv")
)

readr::write_csv(
  tab_sbp_study_display_all,
  file.path(table_path, "systolic_blood_pressure_study_display_main.csv")
)

readr::write_csv(
  tab_sbp_study_display_controlled,
  file.path(table_path, "systolic_blood_pressure_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_sbp_model_compare,
  file.path(table_path, "systolic_blood_pressure_model_comparison.csv")
)

readr::write_csv(
  tab_sbp_loo_all,
  file.path(table_path, "systolic_blood_pressure_leave_one_out_all.csv")
)

readr::write_csv(
  tab_sbp_loo_controlled,
  file.path(table_path, "systolic_blood_pressure_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_sbp_tau,
  file.path(table_path, "systolic_blood_pressure_tau_sensitivity.csv")
)

readr::write_csv(
  tab_sbp_N_by_study,
  file.path(table_path, "systolic_blood_pressure_sample_size_by_study.csv")
)

readr::write_csv(
  tab_sbp_N_by_design,
  file.path(table_path, "systolic_blood_pressure_sample_size_by_design.csv")
)

In [331]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved systolic blood pressure PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved systolic blood pressure tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "systolic_blood_pressure.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "systolic_blood_pressure.*csv$", full.names = TRUE)

Saved systolic blood pressure PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved systolic blood pressure tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_systolic_blood_pressure_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_systolic_blood_pressure_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_systolic_blood_pressure_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_systolic_blood_pressure_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_systolic_blood_pressure_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/systolic_blood_pressure_tau_sensitivity.csv"

## **Diastolic Blood Pressure (DBP)**
[Back to Table of Content](#table-of-content)

In [332]:
## ------------------------------------------------------------
## Filter to diastolic blood pressure outcomes
## Study 3 keeps Pre and Post
## Study 6 keeps Pre and Post
## Study 7 keeps Autumn and Spring mapping to Pre and Post
## Study 11 keeps Pre and Post at 30 min
## ------------------------------------------------------------

mental_dbp <- nonmental %>%
  dplyr::filter(
    outcome_name %in% c("Diastolic Blood Pressure (DBP)", "Diastolic BP"),
    units == "mmHg"
  ) %>%
  dplyr::filter(
    (
      study_id != 11 &
        timepoint_label_harmonised %in% c("Pre", "Post")
    ) |
      (
        study_id == 11 &
          timepoint_label_harmonised %in% c("Pre", "Post") &
          (timepoint_label_harmonised != "Post" |
             abs(timepoint_days_num - 0.020833333) < 1e-8)
      )
  )

## Quick structural check
mental_dbp %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_label,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  )

   study_id outcome_name                   group_harmonised
1   3       Diastolic Blood Pressure (DBP) Control
2   3       Diastolic Blood Pressure (DBP) Control
3   3       Diastolic Blood Pressure (DBP) Intervention
4   3       Diastolic Blood Pressure (DBP) Intervention
5   6       Diastolic BP                   Control
6   6       Diastolic BP                   Control
7   6       Diastolic BP                   Intervention
8   6       Diastolic BP                   Intervention
9   7       Diastolic BP                   Control
10  7       Diastolic BP                   Control
11  7       Diastolic BP                   Intervention
12  7       Diastolic BP                   Intervention
13 11       Diastolic BP                   SingleGroup
14 11       Diastolic BP                   SingleGroup
   timepoint_label_harmonised timepoint_label     timepoint_days_num
1  Post                       Post                15.00000000
2  Pre                        Pre                  0.00000000
3  Post                       Post                15.00000000
4  Pre                        Pre                  0.00000000
5  Post                       Day 5 (whole week)           NA
6  Pre                        Day 1                        NA
7  Post                       Day 5 (whole week)           NA
8  Pre                        Day 1                        NA
9  Post                       Spring (Post)\r\r\n          NA
10 Pre                        Autumn (Pre)                 NA
11 Post                       Spring (Post)                NA
12 Pre                        Autumn (Pre)                 NA
13 Post                       Post                 0.02083333
14 Pre                        Pre                          NA

In [333]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_dbp <- mental_dbp %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [334]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_dbp <- mental_dbp %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [335]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

dbp_prepost <- mental_dbp %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
dbp_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id outcome_name                   group_harmonised
1   3       Diastolic Blood Pressure (DBP) Control
2   3       Diastolic Blood Pressure (DBP) Control
3   3       Diastolic Blood Pressure (DBP) Intervention
4   3       Diastolic Blood Pressure (DBP) Intervention
5   6       Diastolic BP                   Control
6   6       Diastolic BP                   Control
7   6       Diastolic BP                   Intervention
8   6       Diastolic BP                   Intervention
9   7       Diastolic BP                   Control
10  7       Diastolic BP                   Control
11  7       Diastolic BP                   Intervention
12  7       Diastolic BP                   Intervention
13 11       Diastolic BP                   SingleGroup
14 11       Diastolic BP                   SingleGroup
   timepoint_label_harmonised n
1  Post                       1
2  Pre                        1
3  Post                       1
4  Pre                        1
5  Post                       1
6  Pre                        1
7  Post                       1
8  Pre                        1
9  Post                       1
10 Pre                        1
11 Post                       1
12 Pre                        1
13 Post                       1
14 Pre                        1

In [336]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

dbp_wide <- dbp_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

dbp_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name                   group_harmonised n_change
1  3       Diastolic Blood Pressure (DBP) Control           21
2  3       Diastolic Blood Pressure (DBP) Intervention      20
3  6       Diastolic BP                   Control          121
4  6       Diastolic BP                   Intervention     121
5  7       Diastolic BP                   Control           11
6  7       Diastolic BP                   Intervention      25
7 11       Diastolic BP                   SingleGroup       16
  change_mean_calc change_sd_calc
1  0                6.557439
2 -1                8.185353
3  0               10.535654
4 -1                9.539392
5 NA                      NA
6 NA                      NA
7  7                7.549834

In [337]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

dbp_wide <- dbp_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

dbp_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name                   design
1  3       Diastolic Blood Pressure (DBP) controlled
2  6       Diastolic BP                   controlled
3  7       Diastolic BP                   controlled
4 11       Diastolic BP                   single_group

In [338]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

dbp_change_groups <- dbp_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

dbp_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name                   design       group_harmonised
1  3       Diastolic Blood Pressure (DBP) controlled   Control
2  3       Diastolic Blood Pressure (DBP) controlled   Intervention
3  6       Diastolic BP                   controlled   Control
4  6       Diastolic BP                   controlled   Intervention
5 11       Diastolic BP                   single_group SingleGroup
  change_mean_calc change_sd_calc n_change
1  0                6.557439       21
2 -1                8.185353       20
3  0               10.535654      121
4 -1                9.539392      121
5  7                7.549834       16

In [339]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

dbp_change_wide_study <- dbp_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [340]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## Negative yi means lower diastolic blood pressure change under CWE
## Positive yi means higher diastolic blood pressure change under CWE
##
## Keep this only if that direction is what you want
## ------------------------------------------------------------

es_dbp_controlled <- dbp_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Diastolic blood pressure",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_dbp_controlled

  study_id outcome_name                   outcome_domain           design_type
1 3        Diastolic Blood Pressure (DBP) Diastolic blood pressure controlled
2 6        Diastolic BP                   Diastolic blood pressure controlled
  yi          vi
1 -0.13259877 0.09785502
2 -0.09919239 0.01654957

In [341]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_dbp_single <- dbp_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Diastolic blood pressure",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_dbp_single

  study_id outcome_name outcome_domain           design_type  yi
1 11       Diastolic BP Diastolic blood pressure single_group 0.8830216
  vi
1 0.08105581

In [342]:
## ------------------------------------------------------------
## Combine all analyzable diastolic blood pressure effect sizes
## ------------------------------------------------------------

es_dbp_all <- dplyr::bind_rows(
  es_dbp_controlled,
  es_dbp_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("dbp_", dplyr::row_number())
  )

es_dbp_all

  study_id outcome_name                   outcome_domain           design_type
1  3       Diastolic Blood Pressure (DBP) Diastolic blood pressure controlled
2  6       Diastolic BP                   Diastolic blood pressure controlled
3 11       Diastolic BP                   Diastolic blood pressure single_group
  yi          vi         effect_id
1 -0.13259877 0.09785502 dbp_1
2 -0.09919239 0.01654957 dbp_2
3  0.88302157 0.08105581 dbp_3

In [343]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

dbp_N_by_study_raw <- dbp_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    N_study
  )

dbp_N_by_study <- es_dbp_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    dbp_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_dbp <- nrow(dbp_N_by_study)
N_dbp_total <- sum(dbp_N_by_study$N_study, na.rm = TRUE)

dbp_N_by_design <- dbp_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nDiastolic blood pressure meta analysis contributing studies\n")
cat(" k studies =", k_dbp, "\n")
cat(" total N   =", N_dbp_total, "\n")
print(dbp_N_by_design)

Diastolic blood pressure meta analysis contributing studies
 k studies = 3
 total N   = 299
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          2      283
2 single_group        1       16

In [344]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_dbp <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [345]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

dbp_main_dat <- es_dbp_all %>%
  dplyr::arrange(study_id, outcome_name)

dbp_controlled_dat <- es_dbp_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nDiastolic blood pressure main dataset\n")
cat(" k effects =", nrow(dbp_main_dat), "\n")
cat(" studies =", paste(sort(unique(dbp_main_dat$study_id)), collapse = ", "), "\n")

cat("\nDiastolic blood pressure controlled only dataset\n")
cat(" k effects =", nrow(dbp_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(dbp_controlled_dat$study_id)), collapse = ", "), "\n")

Diastolic blood pressure main dataset
 k effects = 3
 studies = 3, 6, 11

Diastolic blood pressure controlled only dataset
 k effects = 2
 studies = 3, 6

In [346]:
## ============================================================
## DIASTOLIC BLOOD PRESSURE
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_dbp_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = dbp_main_dat
)

print(res_dbp_main_mv)
broom::tidy(res_dbp_main_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.2522  0.5022      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 10.2424, p-val = 0.0060

Model Results:

estimate      se    tval  df    pval    ci.lb   ci.ub
  0.1986  0.3231  0.6145   2  0.6015  -1.1917  1.5888

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate  std.error statistic p.value
1 overall summary 0.1985522 0.3231133 0.6144972 0.6014802

In [347]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## If only one controlled study is available this becomes
## a descriptive single study result
## ------------------------------------------------------------

if (nrow(dbp_controlled_dat) >= 2) {

  res_dbp_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = dbp_controlled_dat
  )

  print(res_dbp_controlled_mv)

  dbp_controlled_tidy <- broom::tidy(res_dbp_controlled_mv)

} else if (nrow(dbp_controlled_dat) == 1) {

  res_dbp_controlled_mv <- NULL

  dbp_controlled_tidy <- dbp_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(dbp_controlled_tidy)

} else {

  res_dbp_controlled_mv <- NULL

  dbp_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(dbp_controlled_tidy)
}

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.0098, p-val = 0.9213

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.1040  0.1190  -0.8743   1  0.5426  -1.6158  1.4077

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [348]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

dbp_model_compare <- dplyr::bind_rows(
  broom::tidy(res_dbp_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  dbp_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

dbp_model_compare

  model            term    estimate   std.error statistic  p.value
1 main_all_designs overall  0.1985522 0.3231133  0.6144972 0.6014802
2 controlled_only  overall -0.1040249 0.1189771 -0.8743274 0.5426212

In [349]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

dbp_loo_results <- purrr::map_dfr(
  sort(unique(dbp_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- dbp_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

dbp_loo_results <- dbp_loo_results %>%
  dplyr::left_join(
    study_labels_dbp,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

dbp_loo_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 11            Reed et al. 2023     2                   2
2  6            Hinkka et al 2016    2                   2
3  3            Ketelhut et al. 2023 2                   2
  result_type   estimate   se        ci_lb     ci_ub    p_value   tau2_study
1 meta_analytic -0.1040249 0.1189771 -1.615772 1.407722 0.5426212 5.539954e-12
2 meta_analytic  0.3834818 0.5077428 -6.068002 6.834966 0.5881936 4.262869e-01
3 meta_analytic  0.3590774 0.4900079 -5.867064 6.585219 0.5974008 4.335694e-01
  direction               significant
1 negative_better_for_cwe FALSE
2 positive_worse_for_cwe  FALSE
3 positive_worse_for_cwe  FALSE

In [350]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

dbp_loo_controlled_results <- purrr::map_dfr(
  sort(unique(dbp_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- dbp_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

dbp_loo_controlled_results <- dbp_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_dbp,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

dbp_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 3             Ketelhut et al. 2023 1                   1
2 6             Hinkka et al 2016    1                   1
  result_type            estimate    se        ci_lb      ci_ub     p_value
1 single_study_remaining -0.09919239 0.1286451 -0.3513369 0.1529521 NA
2 single_study_remaining -0.13259877 0.3128179 -0.7457218 0.4805243 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         negative_better_for_cwe NA

In [351]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_dbp <- c(0.00, 0.05, 0.10, 0.20, 0.40)

dbp_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_dbp,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = dbp_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

dbp_tau_sensitivity <- dbp_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

dbp_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb      ci_ub     p_value
1 0.00             0.04272416 0.1097769 -0.4296077 0.5150560 0.7346647
2 0.05             0.14787273 0.1843647 -0.6453847 0.9411301 0.5066715
3 0.10             0.17517050 0.2284713 -0.8078622 1.1582032 0.5233927
4 0.20             0.19409688 0.2944588 -1.0728570 1.4610508 0.5775364
5 0.40             0.20516510 0.3925932 -1.4840273 1.8943575 0.6533818
  direction              significant
1 positive_worse_for_cwe FALSE
2 positive_worse_for_cwe FALSE
3 positive_worse_for_cwe FALSE
4 positive_worse_for_cwe FALSE
5 positive_worse_for_cwe FALSE

In [352]:
## ============================================================
## DIASTOLIC BLOOD PRESSURE
## Plotting and export section aligned with beta workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [353]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Diastolic blood pressure has one effect per study in the current dataset
## ============================================================

dbp_study_display_all <- dbp_main_dat %>%
  dplyr::left_join(study_labels_dbp, by = "study_id") %>%
  dplyr::left_join(
    dbp_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

dbp_study_display_controlled <- dbp_controlled_dat %>%
  dplyr::left_join(study_labels_dbp, by = "study_id") %>%
  dplyr::left_join(
    dbp_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [354]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

dbp_study_display_all <- dbp_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

dbp_study_display_controlled <- dbp_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [355]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_dbp_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = dbp_study_display_all
)

if (nrow(dbp_study_display_controlled) >= 2) {
  res_dbp_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = dbp_study_display_controlled
  )
} else {
  res_dbp_controlled_plot <- NULL
}

dbp_study_display_all <- dbp_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_dbp_all_plot) / sum(weights(res_dbp_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_dbp_controlled_plot)) {
  dbp_study_display_controlled <- dbp_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_dbp_controlled_plot) / sum(weights(res_dbp_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  dbp_study_display_controlled <- dbp_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [356]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Diastolic blood pressure"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for diastolic blood pressure", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Diastolic blood pressure"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled diastolic blood pressure study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for diastolic blood pressure", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [357]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = dbp_study_display_all,
  model = res_dbp_all_plot,
  file = file.path(graph_path, "forest_diastolic_blood_pressure_all_designs_journal_style.pdf"),
  outcome_title = "Diastolic blood pressure, all designs"
)

save_forest_controlled_journal(
  dat = dbp_study_display_controlled,
  model = res_dbp_controlled_plot,
  file = file.path(graph_path, "forest_diastolic_blood_pressure_controlled_journal_style.pdf"),
  outcome_title = "Diastolic blood pressure, controlled studies"
)

agg_record_1281896621
                    2

agg_record_1281896621
                    2

In [358]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

dbp_total_N_all <- sum(dbp_N_by_study$N_study, na.rm = TRUE)

dbp_total_N_controlled <- dbp_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

dbp_loo_plot_all <- dbp_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    dbp_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = dbp_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

dbp_loo_plot_controlled <- dbp_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    dbp_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = dbp_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [359]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

dbp_tau_plot <- dbp_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [360]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = dbp_loo_plot_all,
  file = file.path(graph_path, "forest_diastolic_blood_pressure_leave_one_out_all_designs.pdf"),
  title_left = "Diastolic blood pressure, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_dbp_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = dbp_loo_plot_controlled,
  file = file.path(graph_path, "forest_diastolic_blood_pressure_leave_one_out_controlled_only.pdf"),
  title_left = "Diastolic blood pressure, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_dbp_controlled_mv)) as.numeric(res_dbp_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = dbp_tau_plot,
  file = file.path(graph_path, "forest_diastolic_blood_pressure_tau_sensitivity.pdf"),
  title_left = "Diastolic blood pressure, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_dbp_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_947005993
                   2

agg_record_947005993
                   2

agg_record_947005993
                   2

In [361]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_dbp_study_display_all <- make_study_effect_table(dbp_study_display_all)

tab_dbp_study_display_controlled <- make_study_effect_table(dbp_study_display_controlled)

tab_dbp_effect_sizes_all <- es_dbp_all %>%
  dplyr::left_join(study_labels_dbp, by = "study_id") %>%
  dplyr::left_join(dbp_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_dbp_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(dbp_main_dat), nrow(dbp_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(dbp_main_dat$study_id),
    dplyr::n_distinct(dbp_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_dbp_main_mv$b),
    if (nrow(dbp_controlled_dat) == 1) dbp_controlled_dat$yi[1] else as.numeric(res_dbp_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_dbp_main_mv$se),
    if (nrow(dbp_controlled_dat) == 1) sqrt(dbp_controlled_dat$vi[1]) else as.numeric(res_dbp_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_dbp_main_mv$ci.lb),
    if (nrow(dbp_controlled_dat) == 1) dbp_controlled_dat$yi[1] - 1.96 * sqrt(dbp_controlled_dat$vi[1]) else as.numeric(res_dbp_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_dbp_main_mv$ci.ub),
    if (nrow(dbp_controlled_dat) == 1) dbp_controlled_dat$yi[1] + 1.96 * sqrt(dbp_controlled_dat$vi[1]) else as.numeric(res_dbp_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_dbp_main_mv$pval),
    if (nrow(dbp_controlled_dat) == 1) NA_real_ else as.numeric(res_dbp_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_dbp_main_mv$sigma2),
    if (nrow(dbp_controlled_dat) == 1) NA_real_ else as.numeric(res_dbp_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_dbp_loo_all <- dbp_loo_results %>%
  round_df_2()

tab_dbp_loo_controlled <- dbp_loo_controlled_results %>%
  round_df_2()

tab_dbp_tau <- dbp_tau_sensitivity %>%
  round_df_2()

tab_dbp_N_by_study <- dbp_N_by_study %>%
  round_df_2()

tab_dbp_N_by_design <- dbp_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_dbp_effect_sizes_all,
  file.path(table_path, "diastolic_blood_pressure_effect_sizes_all.csv")
)

readr::write_csv(
  tab_dbp_study_display_all,
  file.path(table_path, "diastolic_blood_pressure_study_display_main.csv")
)

readr::write_csv(
  tab_dbp_study_display_controlled,
  file.path(table_path, "diastolic_blood_pressure_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_dbp_model_compare,
  file.path(table_path, "diastolic_blood_pressure_model_comparison.csv")
)

readr::write_csv(
  tab_dbp_loo_all,
  file.path(table_path, "diastolic_blood_pressure_leave_one_out_all.csv")
)

readr::write_csv(
  tab_dbp_loo_controlled,
  file.path(table_path, "diastolic_blood_pressure_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_dbp_tau,
  file.path(table_path, "diastolic_blood_pressure_tau_sensitivity.csv")
)

readr::write_csv(
  tab_dbp_N_by_study,
  file.path(table_path, "diastolic_blood_pressure_sample_size_by_study.csv")
)

readr::write_csv(
  tab_dbp_N_by_design,
  file.path(table_path, "diastolic_blood_pressure_sample_size_by_design.csv")
)

In [362]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved diastolic blood pressure PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved diastolic blood pressure tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "diastolic_blood_pressure.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "diastolic_blood_pressure.*csv$", full.names = TRUE)

Saved diastolic blood pressure PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved diastolic blood pressure tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_diastolic_blood_pressure_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_diastolic_blood_pressure_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_diastolic_blood_pressure_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_diastolic_blood_pressure_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_diastolic_blood_pressure_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/diastolic_blood_pressure_tau_sensitivity.csv"

## **Heart rate**
[Back to Table of Content](#table-of-content)

In [363]:
## ------------------------------------------------------------
## Filter to heart rate outcomes
## Keep only Pre and Post
## Exclude HR for study 3 because ΔHR is already available
## ------------------------------------------------------------

mental_hr <- nonmental %>%
  dplyr::filter(
    outcome_name %in% c("ΔHR", "HR", "Heart rate", "heart rate"),
    timepoint_label_harmonised %in% c("Pre", "Post")
  ) %>%
  dplyr::filter(
    !(study_id == 3 & outcome_name == "HR")
  )

## Quick structural check
mental_hr %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_label,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  )

   study_id outcome_name group_harmonised timepoint_label_harmonised
1   3       ΔHR          Control          Post
2   3       ΔHR          Control          Pre
3   3       ΔHR          Intervention     Post
4   3       ΔHR          Intervention     Pre
5   6       Heart rate   Control          Post
6   6       Heart rate   Control          Pre
7   6       Heart rate   Intervention     Post
8   6       Heart rate   Intervention     Pre
9  11       Heart rate   SingleGroup      Post
10 11       Heart rate   SingleGroup      Pre
11 12       heart rate   SingleGroup      Post
12 12       heart rate   SingleGroup      Pre
   timepoint_label    timepoint_days_num
1  Post               15.00000000
2  Pre                 0.00000000
3  Post               15.00000000
4  Pre                 0.00000000
5  Day 5 (whole week)          NA
6  Day 1                       NA
7  Day 5 (whole week)          NA
8  Day 1                       NA
9  Post                0.02083333
10 Pre                         NA
11 Post                0.00000000
12 Pre                 0.00000000

In [364]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_hr <- mental_hr %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [365]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_hr <- mental_hr %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [366]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

hr_prepost <- mental_hr %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
hr_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

   study_id outcome_name group_harmonised timepoint_label_harmonised n
1   3       ΔHR          Control          Post                       1
2   3       ΔHR          Control          Pre                        1
3   3       ΔHR          Intervention     Post                       1
4   3       ΔHR          Intervention     Pre                        1
5   6       Heart rate   Control          Post                       1
6   6       Heart rate   Control          Pre                        1
7   6       Heart rate   Intervention     Post                       1
8   6       Heart rate   Intervention     Pre                        1
9  11       Heart rate   SingleGroup      Post                       1
10 11       Heart rate   SingleGroup      Pre                        1
11 12       heart rate   SingleGroup      Post                       1
12 12       heart rate   SingleGroup      Pre                        1

In [367]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

hr_wide <- hr_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

hr_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name group_harmonised n_change change_mean_calc
1  3       ΔHR          Control           21        0.5
2  3       ΔHR          Intervention      20       -0.4
3  6       Heart rate   Control          121        2.0
4  6       Heart rate   Intervention     121       -2.0
5 11       Heart rate   SingleGroup       16      -13.0
6 12       heart rate   SingleGroup       33         NA
  change_sd_calc
1  5.307542
2  6.478426
3 11.000000
4 11.532563
5 10.816654
6        NA

In [368]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

hr_wide <- hr_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

hr_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name design
1  3       ΔHR          controlled
2  6       Heart rate   controlled
3 11       Heart rate   single_group
4 12       heart rate   single_group

In [369]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

hr_change_groups <- hr_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

hr_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name design       group_harmonised change_mean_calc
1  3       ΔHR          controlled   Control            0.5
2  3       ΔHR          controlled   Intervention      -0.4
3  6       Heart rate   controlled   Control            2.0
4  6       Heart rate   controlled   Intervention      -2.0
5 11       Heart rate   single_group SingleGroup      -13.0
  change_sd_calc n_change
1  5.307542       21
2  6.478426       20
3 11.000000      121
4 11.532563      121
5 10.816654       16

In [370]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

hr_change_wide_study <- hr_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [371]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## Negative yi means lower heart rate change under CWE
## Positive yi means higher heart rate change under CWE
##
## Keep this only if that direction is what you want
## ------------------------------------------------------------

es_hr_controlled <- hr_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Heart rate",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_hr_controlled

  study_id outcome_name outcome_domain design_type yi         vi
1 3        ΔHR          Heart rate     controlled  -0.1494086 0.09791864
2 6        Heart rate   Heart rate     controlled  -0.3538321 0.01679167

In [372]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## ------------------------------------------------------------

es_hr_single <- hr_change_wide_study %>%
  dplyr::filter(
    design == "single_group",
    !is.na(change_mean_calc_SingleGroup),
    !is.na(change_sd_calc_SingleGroup),
    !is.na(n_change_SingleGroup)
  ) %>%
  dplyr::mutate(
    d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
    J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
    yi  = J * d,
    v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
    vi  = J^2 * v_d,
    outcome_domain = "Heart rate",
    design_type = "single_group"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_hr_single

  study_id outcome_name outcome_domain design_type  yi        vi
1 11       Heart rate   Heart rate     single_group -1.144619 0.09763165

In [373]:
## ------------------------------------------------------------
## Combine all analyzable heart rate effect sizes
## ------------------------------------------------------------

es_hr_all <- dplyr::bind_rows(
  es_hr_controlled,
  es_hr_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("heart_rate_", dplyr::row_number())
  )

es_hr_all

  study_id outcome_name outcome_domain design_type  yi         vi
1  3       ΔHR          Heart rate     controlled   -0.1494086 0.09791864
2  6       Heart rate   Heart rate     controlled   -0.3538321 0.01679167
3 11       Heart rate   Heart rate     single_group -1.1446195 0.09763165
  effect_id
1 heart_rate_1
2 heart_rate_2
3 heart_rate_3

In [374]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

hr_N_by_study_raw <- hr_change_wide_study %>%
  dplyr::mutate(
    N_study = dplyr::case_when(
      design == "controlled"   ~ n_change_Intervention + n_change_Control,
      design == "single_group" ~ n_change_SingleGroup,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    N_study
  )

hr_N_by_study <- es_hr_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    hr_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_hr <- nrow(hr_N_by_study)
N_hr_total <- sum(hr_N_by_study$N_study, na.rm = TRUE)

hr_N_by_design <- hr_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nHeart rate meta analysis contributing studies\n")
cat(" k studies =", k_hr, "\n")
cat(" total N   =", N_hr_total, "\n")
print(hr_N_by_design)

Heart rate meta analysis contributing studies
 k studies = 3
 total N   = 299
# A tibble: 2 × 3
  design       k_design N_design
  <chr>           <int>    <dbl>
1 controlled          2      283
2 single_group        1       16

In [375]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_hr <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [376]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

hr_main_dat <- es_hr_all %>%
  dplyr::arrange(study_id, outcome_name)

hr_controlled_dat <- es_hr_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nHeart rate main dataset\n")
cat(" k effects =", nrow(hr_main_dat), "\n")
cat(" studies =", paste(sort(unique(hr_main_dat$study_id)), collapse = ", "), "\n")

cat("\nHeart rate controlled only dataset\n")
cat(" k effects =", nrow(hr_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(hr_controlled_dat$study_id)), collapse = ", "), "\n")

Heart rate main dataset
 k effects = 3
 studies = 3, 6, 11

Heart rate controlled only dataset
 k effects = 2
 studies = 3, 6

In [377]:
## ============================================================
## HEART RATE
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_hr_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = hr_main_dat
)

print(res_hr_main_mv)
broom::tidy(res_hr_main_mv)

Multivariate Meta-Analysis Model (k = 3; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.1616  0.4020      3     no  study_id

Test for Heterogeneity:
Q(df = 2) = 6.3802, p-val = 0.0412

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.5238  0.2740  -1.9113   2  0.1961  -1.7028  0.6553

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.5237563 0.2740311 -1.911302 0.1961279

In [378]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## If only one controlled study is available this becomes
## a descriptive single study result
## ------------------------------------------------------------

if (nrow(hr_controlled_dat) >= 2) {

  res_hr_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = hr_controlled_dat
  )

  print(res_hr_controlled_mv)

  hr_controlled_tidy <- broom::tidy(res_hr_controlled_mv)

} else if (nrow(hr_controlled_dat) == 1) {

  res_hr_controlled_mv <- NULL

  hr_controlled_tidy <- hr_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(hr_controlled_tidy)

} else {

  res_hr_controlled_mv <- NULL

  hr_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(hr_controlled_tidy)
}

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.3643, p-val = 0.5461

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.3239  0.1197  -2.7055   1  0.2254  -1.8451  1.1973

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [379]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

hr_model_compare <- dplyr::bind_rows(
  broom::tidy(res_hr_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  hr_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

hr_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall -0.5237563 0.2740311 -1.911302 0.1961279
2 controlled_only  overall -0.3239079 0.1197232 -2.705473 0.2253931

In [380]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

hr_loo_results <- purrr::map_dfr(
  sort(unique(hr_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- hr_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

hr_loo_results <- hr_loo_results %>%
  dplyr::left_join(
    study_labels_hr,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

hr_loo_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 11            Reed et al. 2023     2                   2
2  3            Ketelhut et al. 2023 2                   2
3  6            Hinkka et al 2016    2                   2
  result_type   estimate   se        ci_lb     ci_ub    p_value   tau2_study
1 meta_analytic -0.3239079 0.1197232 -1.845136 1.197320 0.2253931 7.600779e-12
2 meta_analytic -0.6981122 0.3920760 -5.679910 4.283686 0.3257731 2.554607e-01
3 meta_analytic -0.6471582 0.4976054 -6.969835 5.675518 0.4172999 3.974472e-01
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE

In [381]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

hr_loo_controlled_results <- purrr::map_dfr(
  sort(unique(hr_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- hr_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

hr_loo_controlled_results <- hr_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_hr,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

hr_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 3             Ketelhut et al. 2023 1                   1
2 6             Hinkka et al 2016    1                   1
  result_type            estimate   se        ci_lb      ci_ub       p_value
1 single_study_remaining -0.3538321 0.1295827 -0.6078141 -0.09985003 NA
2 single_study_remaining -0.1494086 0.3129195 -0.7627309  0.46391375 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         negative_better_for_cwe NA

In [382]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_hr <- c(0.00, 0.05, 0.10, 0.20, 0.40)

hr_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_hr,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = hr_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

hr_tau_sensitivity <- hr_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

hr_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb     ci_ub      p_value
1 0.00             -0.4289743 0.1117975 -0.910000 0.05205139 0.06170112
2 0.05             -0.4932584 0.1872974 -1.299134 0.31261722 0.11899103
3 0.10             -0.5127875 0.2314049 -1.508442 0.48286745 0.15703663
4 0.20             -0.5277861 0.2970984 -1.806097 0.75052517 0.21763785
5 0.40             -0.5374875 0.3947559 -2.235985 1.16100998 0.30642863
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [383]:
## ============================================================
## HEART RATE
## Plotting and export section aligned with beta workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [384]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Heart rate has one effect per study in the current dataset
## ============================================================

hr_study_display_all <- hr_main_dat %>%
  dplyr::left_join(study_labels_hr, by = "study_id") %>%
  dplyr::left_join(
    hr_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

hr_study_display_controlled <- hr_controlled_dat %>%
  dplyr::left_join(study_labels_hr, by = "study_id") %>%
  dplyr::left_join(
    hr_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [385]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

hr_study_display_all <- hr_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

hr_study_display_controlled <- hr_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [386]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_hr_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = hr_study_display_all
)

if (nrow(hr_study_display_controlled) >= 2) {
  res_hr_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = hr_study_display_controlled
  )
} else {
  res_hr_controlled_plot <- NULL
}

hr_study_display_all <- hr_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_hr_all_plot) / sum(weights(res_hr_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_hr_controlled_plot)) {
  hr_study_display_controlled <- hr_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_hr_controlled_plot) / sum(weights(res_hr_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  hr_study_display_controlled <- hr_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [387]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Heart rate"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for heart rate", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Heart rate"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled heart rate study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for heart rate", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [388]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = hr_study_display_all,
  model = res_hr_all_plot,
  file = file.path(graph_path, "forest_heart_rate_all_designs_journal_style.pdf"),
  outcome_title = "Heart rate, all designs"
)

save_forest_controlled_journal(
  dat = hr_study_display_controlled,
  model = res_hr_controlled_plot,
  file = file.path(graph_path, "forest_heart_rate_controlled_journal_style.pdf"),
  outcome_title = "Heart rate, controlled studies"
)

agg_record_1744579730
                    2

agg_record_1744579730
                    2

In [389]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

hr_total_N_all <- sum(hr_N_by_study$N_study, na.rm = TRUE)

hr_total_N_controlled <- hr_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

hr_loo_plot_all <- hr_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    hr_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = hr_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

hr_loo_plot_controlled <- hr_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    hr_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = hr_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [390]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

hr_tau_plot <- hr_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [391]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = hr_loo_plot_all,
  file = file.path(graph_path, "forest_heart_rate_leave_one_out_all_designs.pdf"),
  title_left = "Heart rate, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_hr_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = hr_loo_plot_controlled,
  file = file.path(graph_path, "forest_heart_rate_leave_one_out_controlled_only.pdf"),
  title_left = "Heart rate, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_hr_controlled_mv)) as.numeric(res_hr_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = hr_tau_plot,
  file = file.path(graph_path, "forest_heart_rate_tau_sensitivity.pdf"),
  title_left = "Heart rate, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_hr_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_528324128
                   2

agg_record_528324128
                   2

agg_record_528324128
                   2

In [392]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
  }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_hr_study_display_all <- make_study_effect_table(hr_study_display_all)

tab_hr_study_display_controlled <- make_study_effect_table(hr_study_display_controlled)

tab_hr_effect_sizes_all <- es_hr_all %>%
  dplyr::left_join(study_labels_hr, by = "study_id") %>%
  dplyr::left_join(hr_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_hr_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(hr_main_dat), nrow(hr_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(hr_main_dat$study_id),
    dplyr::n_distinct(hr_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_hr_main_mv$b),
    if (nrow(hr_controlled_dat) == 1) hr_controlled_dat$yi[1] else as.numeric(res_hr_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_hr_main_mv$se),
    if (nrow(hr_controlled_dat) == 1) sqrt(hr_controlled_dat$vi[1]) else as.numeric(res_hr_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_hr_main_mv$ci.lb),
    if (nrow(hr_controlled_dat) == 1) hr_controlled_dat$yi[1] - 1.96 * sqrt(hr_controlled_dat$vi[1]) else as.numeric(res_hr_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_hr_main_mv$ci.ub),
    if (nrow(hr_controlled_dat) == 1) hr_controlled_dat$yi[1] + 1.96 * sqrt(hr_controlled_dat$vi[1]) else as.numeric(res_hr_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_hr_main_mv$pval),
    if (nrow(hr_controlled_dat) == 1) NA_real_ else as.numeric(res_hr_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_hr_main_mv$sigma2),
    if (nrow(hr_controlled_dat) == 1) NA_real_ else as.numeric(res_hr_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_hr_loo_all <- hr_loo_results %>%
  round_df_2()

tab_hr_loo_controlled <- hr_loo_controlled_results %>%
  round_df_2()

tab_hr_tau <- hr_tau_sensitivity %>%
  round_df_2()

tab_hr_N_by_study <- hr_N_by_study %>%
  round_df_2()

tab_hr_N_by_design <- hr_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_hr_effect_sizes_all,
  file.path(table_path, "heart_rate_effect_sizes_all.csv")
)

readr::write_csv(
  tab_hr_study_display_all,
  file.path(table_path, "heart_rate_study_display_main.csv")
)

readr::write_csv(
  tab_hr_study_display_controlled,
  file.path(table_path, "heart_rate_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_hr_model_compare,
  file.path(table_path, "heart_rate_model_comparison.csv")
)

readr::write_csv(
  tab_hr_loo_all,
  file.path(table_path, "heart_rate_leave_one_out_all.csv")
)

readr::write_csv(
  tab_hr_loo_controlled,
  file.path(table_path, "heart_rate_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_hr_tau,
  file.path(table_path, "heart_rate_tau_sensitivity.csv")
)

readr::write_csv(
  tab_hr_N_by_study,
  file.path(table_path, "heart_rate_sample_size_by_study.csv")
)

readr::write_csv(
  tab_hr_N_by_design,
  file.path(table_path, "heart_rate_sample_size_by_design.csv")
)

In [393]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved heart rate PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved heart rate tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "heart_rate.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "heart_rate.*csv$", full.names = TRUE)

Saved heart rate PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved heart rate tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_heart_rate_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_heart_rate_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_heart_rate_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_heart_rate_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_heart_rate_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/heart_rate_tau_sensitivity.csv"

## **Pain**
[Back to Table of Content](#table-of-content)

In [405]:
## ------------------------------------------------------------
## Filter to pain outcomes
## Keep only Pre and Post
## ------------------------------------------------------------

mental_pain <- nonmental %>%
  dplyr::filter(
    outcome_category == "Pain",
    timepoint_label_harmonised %in% c("Pre", "Post")
  )

## Quick structural check
mental_pain %>%
  dplyr::distinct(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_label,
    timepoint_days_num
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    timepoint_days_num
  )

  study_id outcome_name   group_harmonised timepoint_label_harmonised
1 3        Perceived Pain Control          Post
2 3        Perceived Pain Control          Pre
3 3        Perceived Pain Intervention     Post
4 3        Perceived Pain Intervention     Pre
5 6        VAS            Control          Post
6 6        VAS            Control          Pre
7 6        VAS            Intervention     Post
8 6        VAS            Intervention     Pre
  timepoint_label    timepoint_days_num
1 Post               15
2 Pre                 0
3 Post               15
4 Pre                 0
5 Day 5 (whole week) NA
6 Day 1              NA
7 Day 5 (whole week) NA
8 Day 1              NA

In [406]:
## ------------------------------------------------------------
## Reconstruct change SD from confidence interval if available
## ------------------------------------------------------------

mental_pain <- mental_pain %>%
  dplyr::mutate(
    se_change_from_ci = dplyr::case_when(
      !is.na(change_mean) & is.na(change_sd) &
        !is.na(ci_l) & !is.na(ci_u) ~ (ci_u - ci_l) / (2 * 1.96),
      TRUE ~ NA_real_
    ),
    change_sd = dplyr::if_else(
      is.na(change_sd) & !is.na(se_change_from_ci) & !is.na(n),
      se_change_from_ci * sqrt(n),
      change_sd
    )
  ) %>%
  dplyr::select(-se_change_from_ci)

In [407]:
## ------------------------------------------------------------
## Estimate mean and SD from median and IQR where needed
## ------------------------------------------------------------

mental_pain <- mental_pain %>%
  dplyr::mutate(
    has_iqr = !is.na(median) & !is.na(iqr_l) & !is.na(iqr_u),

    mean_est = dplyr::if_else(
      has_iqr & is.na(mean),
      (iqr_l + median + iqr_u) / 3,
      mean
    ),

    sd_est = dplyr::if_else(
      has_iqr & is.na(sd),
      (iqr_u - iqr_l) / 1.35,
      sd
    ),

    mean = mean_est,
    sd   = sd_est
  ) %>%
  dplyr::select(-mean_est, -sd_est, -has_iqr)

In [408]:
## ------------------------------------------------------------
## Select one row per study × outcome × group × timepoint
## Prefer ITT over PP
## ------------------------------------------------------------

analysis_set_levels <- c("ITT", "PP")

pain_prepost <- mental_pain %>%
  dplyr::mutate(
    analysis_set = factor(analysis_set, levels = analysis_set_levels)
  ) %>%
  dplyr::arrange(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised,
    analysis_set
  ) %>%
  dplyr::group_by(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  ) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()

## Quick check after ITT preference
pain_prepost %>%
  dplyr::count(
    study_id,
    outcome_name,
    group_harmonised,
    timepoint_label_harmonised
  )

  study_id outcome_name   group_harmonised timepoint_label_harmonised n
1 3        Perceived Pain Control          Post                       1
2 3        Perceived Pain Control          Pre                        1
3 3        Perceived Pain Intervention     Post                       1
4 3        Perceived Pain Intervention     Pre                        1
5 6        VAS            Control          Post                       1
6 6        VAS            Control          Pre                        1
7 6        VAS            Intervention     Post                       1
8 6        VAS            Intervention     Pre                        1

In [409]:
## ------------------------------------------------------------
## Compute change scores as Post minus Pre per group
## I use reported change values where available
## Otherwise I derive them from Pre and Post values
## ------------------------------------------------------------

r_change <- 0.5

pain_wide <- pain_prepost %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, group_harmonised),
    names_from = timepoint_label_harmonised,
    values_from = c(n, mean, sd, change_mean, change_sd),
    names_glue = "{.value}_{timepoint_label_harmonised}"
  ) %>%
  dplyr::mutate(
    n_change = dplyr::coalesce(n_Post, n_Pre),

    change_mean_calc = dplyr::case_when(
      !is.na(change_mean_Post) ~ change_mean_Post,
      !is.na(mean_Pre) & !is.na(mean_Post) ~ mean_Post - mean_Pre,
      TRUE ~ NA_real_
    ),

    change_sd_calc = dplyr::case_when(
      !is.na(change_sd_Post) ~ change_sd_Post,
      !is.na(sd_Pre) & !is.na(sd_Post) ~ sqrt(
        sd_Pre^2 + sd_Post^2 - 2 * r_change * sd_Pre * sd_Post
      ),
      TRUE ~ NA_real_
    )
  )

pain_wide %>%
  dplyr::select(
    study_id,
    outcome_name,
    group_harmonised,
    n_change,
    change_mean_calc,
    change_sd_calc
  ) %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name   group_harmonised n_change change_mean_calc
1 3        Perceived Pain Control           21      -0.10
2 3        Perceived Pain Intervention      20      -1.05
3 6        VAS            Control          121      -1.00
4 6        VAS            Intervention     121      -1.40
  change_sd_calc
1 1.901263
2 1.608384
3 2.029778
4 2.116601

In [410]:
## ------------------------------------------------------------
## Classify study designs
## ------------------------------------------------------------

pain_wide <- pain_wide %>%
  dplyr::group_by(study_id, outcome_name) %>%
  dplyr::mutate(
    n_groups         = dplyr::n(),
    has_intervention = any(group_harmonised == "Intervention"),
    has_control      = any(group_harmonised == "Control"),
    has_single       = any(group_harmonised == "SingleGroup"),
    design = dplyr::case_when(
      has_intervention & has_control ~ "controlled",
      n_groups == 1 & has_single     ~ "single_group",
      TRUE                           ~ "other"
    )
  ) %>%
  dplyr::ungroup()

pain_wide %>%
  dplyr::distinct(study_id, outcome_name, design)

  study_id outcome_name   design
1 3        Perceived Pain controlled
2 6        VAS            controlled

In [411]:
## ------------------------------------------------------------
## Prepare group level change data
## Keep only groups with complete change information
## ------------------------------------------------------------

pain_change_groups <- pain_wide %>%
  dplyr::filter(
    !is.na(change_mean_calc),
    !is.na(change_sd_calc),
    !is.na(n_change)
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    design,
    group_harmonised,
    change_mean_calc,
    change_sd_calc,
    n_change
  )

pain_change_groups %>%
  dplyr::arrange(study_id, outcome_name, group_harmonised)

  study_id outcome_name   design     group_harmonised change_mean_calc
1 3        Perceived Pain controlled Control          -0.10
2 3        Perceived Pain controlled Intervention     -1.05
3 6        VAS            controlled Control          -1.00
4 6        VAS            controlled Intervention     -1.40
  change_sd_calc n_change
1 1.901263        21
2 1.608384        20
3 2.029778       121
4 2.116601       121

In [412]:
## ------------------------------------------------------------
## Create one row per study for effect size construction
## ------------------------------------------------------------

pain_change_wide_study <- pain_change_groups %>%
  tidyr::pivot_wider(
    id_cols = c(study_id, outcome_name, design),
    names_from = group_harmonised,
    values_from = c(change_mean_calc, change_sd_calc, n_change),
    names_glue = "{.value}_{group_harmonised}"
  )

In [413]:
## ------------------------------------------------------------
## Effect sizes for controlled studies
## Standardized mean difference of change scores
##
## Sign convention
## Negative yi means lower pain change under CWE
## Positive yi means higher pain change under CWE
## ------------------------------------------------------------

es_pain_controlled <- pain_change_wide_study %>%
  dplyr::filter(
    design == "controlled",
    !is.na(change_mean_calc_Intervention),
    !is.na(change_mean_calc_Control),
    !is.na(change_sd_calc_Intervention),
    !is.na(change_sd_calc_Control),
    !is.na(n_change_Intervention),
    !is.na(n_change_Control)
  ) %>%
  metafor::escalc(
    measure = "SMD",
    m1i = change_mean_calc_Intervention,
    sd1i = change_sd_calc_Intervention,
    n1i = n_change_Intervention,
    m2i = change_mean_calc_Control,
    sd2i = change_sd_calc_Control,
    n2i = n_change_Control,
    data = .,
    vtype = "UB"
  ) %>%
  dplyr::mutate(
    outcome_domain = "Pain",
    design_type = "controlled"
  ) %>%
  dplyr::select(
    study_id,
    outcome_name,
    outcome_domain,
    design_type,
    yi,
    vi
  )

es_pain_controlled

  study_id outcome_name   outcome_domain design_type yi         vi
1 3        Perceived Pain Pain           controlled  -0.5279162 0.10135942
2 6        VAS            Pain           controlled  -0.1922936 0.01660653

In [414]:
## ------------------------------------------------------------
## Effect sizes for single group pre post studies
## Only run this if SingleGroup columns exist
## ------------------------------------------------------------

has_single_group_cols_pain <- all(
  c(
    "change_mean_calc_SingleGroup",
    "change_sd_calc_SingleGroup",
    "n_change_SingleGroup"
  ) %in% names(pain_change_wide_study)
)

if (has_single_group_cols_pain) {

  es_pain_single <- pain_change_wide_study %>%
    dplyr::filter(
      design == "single_group",
      !is.na(change_mean_calc_SingleGroup),
      !is.na(change_sd_calc_SingleGroup),
      !is.na(n_change_SingleGroup)
    ) %>%
    dplyr::mutate(
      d   = change_mean_calc_SingleGroup / change_sd_calc_SingleGroup,
      J   = 1 - 3 / (4 * n_change_SingleGroup - 1),
      yi  = J * d,
      v_d = 1 / n_change_SingleGroup + (d^2) / (2 * n_change_SingleGroup),
      vi  = J^2 * v_d,
      outcome_domain = "Pain",
      design_type = "single_group"
    ) %>%
    dplyr::select(
      study_id,
      outcome_name,
      outcome_domain,
      design_type,
      yi,
      vi
    )

} else {

  es_pain_single <- tibble::tibble(
    study_id = numeric(),
    outcome_name = character(),
    outcome_domain = character(),
    design_type = character(),
    yi = numeric(),
    vi = numeric()
  )
}

es_pain_single

     study_id outcome_name outcome_domain design_type yi vi

In [415]:
## ------------------------------------------------------------
## Combine all analyzable pain effect sizes
## ------------------------------------------------------------

es_pain_all <- dplyr::bind_rows(
  es_pain_controlled,
  es_pain_single
) %>%
  dplyr::arrange(study_id, outcome_name) %>%
  dplyr::mutate(
    effect_id = paste0("pain_", dplyr::row_number())
  )

es_pain_all

  study_id outcome_name   outcome_domain design_type yi         vi
1 3        Perceived Pain Pain           controlled  -0.5279162 0.10135942
2 6        VAS            Pain           controlled  -0.1922936 0.01660653
  effect_id
1 pain_1
2 pain_2

In [417]:
## ------------------------------------------------------------
## Sample size summary
## Count only studies that actually contribute an effect size
## ------------------------------------------------------------

has_single_group_n_pain <- "n_change_SingleGroup" %in% names(pain_change_wide_study)

if (has_single_group_n_pain) {

  pain_N_by_study_raw <- pain_change_wide_study %>%
    dplyr::mutate(
      N_study = dplyr::case_when(
        design == "controlled" &
          !is.na(n_change_Intervention) &
          !is.na(n_change_Control) ~ n_change_Intervention + n_change_Control,
        design == "single_group" &
          !is.na(n_change_SingleGroup) ~ n_change_SingleGroup,
        TRUE ~ NA_real_
      )
    ) %>%
    dplyr::select(
      study_id,
      outcome_name,
      design,
      N_study
    )

} else {

  pain_N_by_study_raw <- pain_change_wide_study %>%
    dplyr::mutate(
      N_study = dplyr::case_when(
        design == "controlled" &
          !is.na(n_change_Intervention) &
          !is.na(n_change_Control) ~ n_change_Intervention + n_change_Control,
        TRUE ~ NA_real_
      )
    ) %>%
    dplyr::select(
      study_id,
      outcome_name,
      design,
      N_study
    )
}

pain_N_by_study <- es_pain_all %>%
  dplyr::distinct(study_id, outcome_name, design_type) %>%
  dplyr::left_join(
    pain_N_by_study_raw,
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::mutate(
    design = dplyr::case_when(
      design_type == "controlled"   ~ "controlled",
      design_type == "single_group" ~ "single_group",
      TRUE ~ NA_character_
    )
  ) %>%
  dplyr::select(study_id, outcome_name, design, N_study) %>%
  dplyr::distinct()

k_pain <- nrow(pain_N_by_study)
N_pain_total <- sum(pain_N_by_study$N_study, na.rm = TRUE)

pain_N_by_design <- pain_N_by_study %>%
  dplyr::group_by(design) %>%
  dplyr::summarise(
    k_design = dplyr::n(),
    N_design = sum(N_study, na.rm = TRUE),
    .groups = "drop"
  )

cat("\nPain meta analysis contributing studies\n")
cat(" k studies =", k_pain, "\n")
cat(" total N   =", N_pain_total, "\n")
print(pain_N_by_design)

Pain meta analysis contributing studies
 k studies = 2
 total N   = 283
# A tibble: 1 × 3
  design     k_design N_design
  <chr>         <int>    <dbl>
1 controlled        2      283

In [418]:
## ------------------------------------------------------------
## Study labels
## ------------------------------------------------------------

study_labels_pain <- metadata %>%
  dplyr::distinct(study_id, author, year_of_publication) %>%
  dplyr::mutate(
    author = as.character(author),
    year_of_publication = as.character(year_of_publication),
    study_label = paste(author, year_of_publication)
  ) %>%
  dplyr::select(study_id, study_label)

In [419]:
## ------------------------------------------------------------
## Main analysis datasets
## ------------------------------------------------------------

pain_main_dat <- es_pain_all %>%
  dplyr::arrange(study_id, outcome_name)

pain_controlled_dat <- es_pain_all %>%
  dplyr::filter(design_type == "controlled") %>%
  dplyr::arrange(study_id, outcome_name)

cat("\nPain main dataset\n")
cat(" k effects =", nrow(pain_main_dat), "\n")
cat(" studies =", paste(sort(unique(pain_main_dat$study_id)), collapse = ", "), "\n")

cat("\nPain controlled only dataset\n")
cat(" k effects =", nrow(pain_controlled_dat), "\n")
cat(" studies =", paste(sort(unique(pain_controlled_dat$study_id)), collapse = ", "), "\n")

Pain main dataset
 k effects = 2
 studies = 3, 6

Pain controlled only dataset
 k effects = 2
 studies = 3, 6

In [420]:
## ============================================================
## PAIN
## MAIN MODEL AND CONTROLLED ONLY SENSITIVITY
## Multilevel random effects framework as default
## Hartung Knapp like inference via t distribution
## ============================================================

res_pain_main_mv <- metafor::rma.mv(
  yi = yi,
  V = vi,
  random = ~ 1 | study_id,
  method = "REML",
  test = "t",
  dfs = "contain",
  data = pain_main_dat
)

print(res_pain_main_mv)
broom::tidy(res_pain_main_mv)

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.9549, p-val = 0.3285

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.2395  0.1195  -2.0053   1  0.2945  -1.7573  1.2782

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

  term    type    estimate   std.error statistic p.value
1 overall summary -0.2395405 0.1194519 -2.00533  0.2944901

In [421]:
## ------------------------------------------------------------
## Controlled only sensitivity model
## If only one controlled study is available this becomes
## a descriptive single study result
## ------------------------------------------------------------

if (nrow(pain_controlled_dat) >= 2) {

  res_pain_controlled_mv <- metafor::rma.mv(
    yi = yi,
    V = vi,
    random = ~ 1 | study_id,
    method = "REML",
    test = "t",
    dfs = "contain",
    data = pain_controlled_dat
  )

  print(res_pain_controlled_mv)

  pain_controlled_tidy <- broom::tidy(res_pain_controlled_mv)

} else if (nrow(pain_controlled_dat) == 1) {

  res_pain_controlled_mv <- NULL

  pain_controlled_tidy <- pain_controlled_dat %>%
    dplyr::mutate(
      term = "overall",
      type = "summary",
      estimate = yi,
      std.error = sqrt(vi),
      statistic = NA_real_,
      p.value = NA_real_
    ) %>%
    dplyr::select(term, type, estimate, std.error, statistic, p.value)

  print(pain_controlled_tidy)

} else {

  res_pain_controlled_mv <- NULL

  pain_controlled_tidy <- tibble::tibble(
    term = "overall",
    type = "summary",
    estimate = NA_real_,
    std.error = NA_real_,
    statistic = NA_real_,
    p.value = NA_real_
  )

  print(pain_controlled_tidy)
}

Multivariate Meta-Analysis Model (k = 2; method: REML)

Variance Components:

            estim    sqrt  nlvls  fixed    factor
sigma^2    0.0000  0.0000      2     no  study_id

Test for Heterogeneity:
Q(df = 1) = 0.9549, p-val = 0.3285

Model Results:

estimate      se     tval  df    pval    ci.lb   ci.ub
 -0.2395  0.1195  -2.0053   1  0.2945  -1.7573  1.2782

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

In [422]:
## ------------------------------------------------------------
## Compact comparison table
## ------------------------------------------------------------

pain_model_compare <- dplyr::bind_rows(
  broom::tidy(res_pain_main_mv) %>%
    dplyr::mutate(model = "main_all_designs"),
  pain_controlled_tidy %>%
    dplyr::mutate(model = "controlled_only")
) %>%
  dplyr::select(model, term, estimate, std.error, statistic, p.value)

pain_model_compare

  model            term    estimate   std.error statistic p.value
1 main_all_designs overall -0.2395405 0.1194519 -2.00533  0.2944901
2 controlled_only  overall -0.2395405 0.1194519 -2.00533  0.2944901

In [423]:
## ------------------------------------------------------------
## Leave one out by study
## ------------------------------------------------------------

pain_loo_results <- purrr::map_dfr(
  sort(unique(pain_main_dat$study_id)),
  function(drop_study) {

    loo_dat <- pain_main_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

pain_loo_results <- pain_loo_results %>%
  dplyr::left_join(
    study_labels_pain,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(p_value)

pain_loo_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 3             Ketelhut et al. 2023 1                   1
2 6             Hinkka et al 2016    1                   1
  result_type            estimate   se        ci_lb      ci_ub      p_value
1 single_study_remaining -0.1922936 0.1288663 -0.4448716 0.06028438 NA
2 single_study_remaining -0.5279162 0.3183699 -1.1519212 0.09608892 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         negative_better_for_cwe NA

In [424]:
## ------------------------------------------------------------
## Leave one out among controlled studies only
## ------------------------------------------------------------

pain_loo_controlled_results <- purrr::map_dfr(
  sort(unique(pain_controlled_dat$study_id)),
  function(drop_study) {

    loo_dat <- pain_controlled_dat %>%
      dplyr::filter(study_id != drop_study)

    n_remaining <- dplyr::n_distinct(loo_dat$study_id)

    if (n_remaining >= 2) {

      loo_model <- metafor::rma.mv(
        yi = yi,
        V = vi,
        random = ~ 1 | study_id,
        method = "REML",
        test = "t",
        dfs = "contain",
        data = loo_dat
      )

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = as.numeric(loo_model$b),
        se = loo_model$se,
        ci_lb = loo_model$ci.lb,
        ci_ub = loo_model$ci.ub,
        p_value = loo_model$pval,
        tau2_study = loo_model$sigma2[1],
        result_type = "meta_analytic",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = p_value < 0.05
      )

    } else if (n_remaining == 1) {

      single_yi <- loo_dat$yi[1]
      single_vi <- loo_dat$vi[1]
      single_se <- sqrt(single_vi)
      single_ci_lb <- single_yi - 1.96 * single_se
      single_ci_ub <- single_yi + 1.96 * single_se

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = nrow(loo_dat),
        n_studies_remaining = n_remaining,
        estimate = single_yi,
        se = single_se,
        ci_lb = single_ci_lb,
        ci_ub = single_ci_ub,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "single_study_remaining",
        direction = dplyr::case_when(
          estimate < 0 ~ "negative_better_for_cwe",
          estimate > 0 ~ "positive_worse_for_cwe",
          TRUE ~ "null"
        ),
        significant = NA
      )

    } else {

      tibble::tibble(
        dropped_study = drop_study,
        k_effects_remaining = 0,
        n_studies_remaining = 0,
        estimate = NA_real_,
        se = NA_real_,
        ci_lb = NA_real_,
        ci_ub = NA_real_,
        p_value = NA_real_,
        tau2_study = NA_real_,
        result_type = "no_data_remaining",
        direction = NA_character_,
        significant = NA
      )
    }
  }
)

pain_loo_controlled_results <- pain_loo_controlled_results %>%
  dplyr::left_join(
    study_labels_pain,
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::select(
    dropped_study,
    study_label,
    k_effects_remaining,
    n_studies_remaining,
    result_type,
    estimate,
    se,
    ci_lb,
    ci_ub,
    p_value,
    tau2_study,
    direction,
    significant
  ) %>%
  dplyr::arrange(dropped_study)

pain_loo_controlled_results

  dropped_study study_label          k_effects_remaining n_studies_remaining
1 3             Ketelhut et al. 2023 1                   1
2 6             Hinkka et al 2016    1                   1
  result_type            estimate   se        ci_lb      ci_ub      p_value
1 single_study_remaining -0.1922936 0.1288663 -0.4448716 0.06028438 NA
2 single_study_remaining -0.5279162 0.3183699 -1.1519212 0.09608892 NA
  tau2_study direction               significant
1 NA         negative_better_for_cwe NA
2 NA         negative_better_for_cwe NA

In [425]:
## ------------------------------------------------------------
## Tau sensitivity analysis
## There is one heterogeneity component when each study
## contributes one effect only
## ------------------------------------------------------------

tau2_grid_pain <- c(0.00, 0.05, 0.10, 0.20, 0.40)

pain_tau_sensitivity <- purrr::map_dfr(
  tau2_grid_pain,
  function(tau2_value) {

    tau_model <- metafor::rma.mv(
      yi = yi,
      V = vi,
      random = ~ 1 | study_id,
      sigma2 = tau2_value,
      method = "REML",
      test = "t",
      dfs = "contain",
      data = pain_main_dat
    )

    tibble::tibble(
      tau2_study_fixed = tau2_value,
      estimate = as.numeric(tau_model$b),
      se = tau_model$se,
      ci_lb = tau_model$ci.lb,
      ci_ub = tau_model$ci.ub,
      p_value = tau_model$pval
    )
  }
)

pain_tau_sensitivity <- pain_tau_sensitivity %>%
  dplyr::mutate(
    direction = dplyr::case_when(
      estimate < 0 ~ "negative_better_for_cwe",
      estimate > 0 ~ "positive_worse_for_cwe",
      TRUE ~ "null"
    ),
    significant = p_value < 0.05
  )

pain_tau_sensitivity

  tau2_study_fixed estimate   se        ci_lb     ci_ub    p_value
1 0.00             -0.2395405 0.1194519 -1.757321 1.278240 0.2944901
2 0.05             -0.2948539 0.2150645 -3.027508 2.437800 0.4011863
3 0.10             -0.3153753 0.2717422 -3.768187 3.137437 0.4527749
4 0.20             -0.3326465 0.3549993 -4.843341 4.178048 0.5206869
5 0.40             -0.3446114 0.4770065 -6.405554 5.716331 0.6017103
  direction               significant
1 negative_better_for_cwe FALSE
2 negative_better_for_cwe FALSE
3 negative_better_for_cwe FALSE
4 negative_better_for_cwe FALSE
5 negative_better_for_cwe FALSE

In [426]:
## ============================================================
## PAIN
## Plotting and export section aligned with beta workflow
## ============================================================

## ------------------------------------------------------------
## Paths
## ------------------------------------------------------------

graph_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs"
table_path <- "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables"

dir.create(graph_path, recursive = TRUE, showWarnings = FALSE)
dir.create(table_path, recursive = TRUE, showWarnings = FALSE)

In [427]:
## ============================================================
## CREATE STUDY LEVEL DISPLAY DATA FOR FOREST PLOTS ONLY
## Important
## Main inference remains based on rma.mv
## Pain has one effect per study in the current dataset
## ============================================================

pain_study_display_all <- pain_main_dat %>%
  dplyr::left_join(study_labels_pain, by = "study_id") %>%
  dplyr::left_join(
    pain_N_by_study %>% dplyr::select(study_id, outcome_name, design, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = dplyr::case_when(
      design_type == "controlled"   ~ "Controlled",
      design_type == "single_group" ~ "Single group",
      TRUE ~ design_type
    )
  ) %>%
  dplyr::arrange(study_id, outcome_name)

pain_study_display_controlled <- pain_controlled_dat %>%
  dplyr::left_join(study_labels_pain, by = "study_id") %>%
  dplyr::left_join(
    pain_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, outcome_name, N_study),
    by = c("study_id", "outcome_name")
  ) %>%
  dplyr::distinct(study_id, outcome_name, .keep_all = TRUE) %>%
  dplyr::mutate(
    sei = sqrt(vi),
    ci_lb_plot = yi - 1.96 * sei,
    ci_ub_plot = yi + 1.96 * sei,
    effect_ci = sprintf("%.2f (%.2f to %.2f)", yi, ci_lb_plot, ci_ub_plot),
    N_lab = ifelse(is.na(N_study), "", as.character(as.integer(N_study))),
    design_label = "Controlled"
  ) %>%
  dplyr::arrange(study_id, outcome_name)

In [428]:
## ------------------------------------------------------------
## Wrap long study labels
## ------------------------------------------------------------

pain_study_display_all <- pain_study_display_all %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

pain_study_display_controlled <- pain_study_display_controlled %>%
  dplyr::mutate(
    study_label_plot = dplyr::if_else(
      study_label == "Petraskova Touskova et al. 2022",
      "Petraskova Touskova et al.\n2022",
      study_label
    )
  )

In [429]:
## ------------------------------------------------------------
## Plot only models for pooled diamonds
## These are for display only
## Main inference still comes from rma.mv
## ------------------------------------------------------------

res_pain_all_plot <- metafor::rma.uni(
  yi = yi,
  vi = vi,
  method = "REML",
  test = "knha",
  data = pain_study_display_all
)

if (nrow(pain_study_display_controlled) >= 2) {
  res_pain_controlled_plot <- metafor::rma.uni(
    yi = yi,
    vi = vi,
    method = "REML",
    test = "knha",
    data = pain_study_display_controlled
  )
} else {
  res_pain_controlled_plot <- NULL
}

pain_study_display_all <- pain_study_display_all %>%
  dplyr::mutate(
    weight_random = 100 * weights(res_pain_all_plot) / sum(weights(res_pain_all_plot)),
    weight_lab = sprintf("%.0f%%", round(weight_random, 0))
  )

if (!is.null(res_pain_controlled_plot)) {
  pain_study_display_controlled <- pain_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100 * weights(res_pain_controlled_plot) / sum(weights(res_pain_controlled_plot)),
      weight_lab = sprintf("%.0f%%", round(weight_random, 0))
    )
} else {
  pain_study_display_controlled <- pain_study_display_controlled %>%
    dplyr::mutate(
      weight_random = 100,
      weight_lab = "100%"
    )
}

In [430]:
## ============================================================
## JOURNAL STYLE FOREST PLOT HELPERS
## ============================================================

save_forest_all_designs_journal <- function(
    dat,
    model,
    file,
    outcome_title = "Pain"
) {

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-5.3, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  metafor::addpoly(
    x = model,
    row = row_overall,
    mlab = "",
    cex = 0.9
  )

  x_study  <- -5.15
  x_design <- -3.15
  x_n      <- -2.20
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_design, k + 1.15, "Design", font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-5.25, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_design, rows, dat$design_label, cex = 0.84)
  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)
  text(
    x_right,
    row_overall,
    sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub),
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for pain", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_forest_controlled_journal <- function(
    dat,
    model = NULL,
    file,
    outcome_title = "Pain"
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No controlled pain study available", cex = 1.1)
    mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  row_overall <- 0
  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$yi,
    vi = dat$vi,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = c(-4.8, 4.8),
    alim = c(-2.0, 2.0),
    at = -2:2,
    refline = 0,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  if (!is.null(model) && nrow(dat) >= 2) {
    metafor::addpoly(
      x = model,
      row = row_overall,
      mlab = "",
      cex = 0.9
    )
  }

  x_study  <- -4.65
  x_n      <- -2.45
  x_weight <-  2.45
  x_right  <-  4.65

  text(x_study,  k + 1.15, "Study", pos = 4, font = 2, cex = 0.9)
  text(x_n,      k + 1.15, "N", font = 2, cex = 0.9)
  text(x_weight, k + 1.15, "Weight", font = 2, cex = 0.9)
  text(x_right,  k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(-4.75, k + 0.55, 4.75, k + 0.55, lwd = 1)

  for (i in seq_len(k)) {
    this_row <- rows[i]
    this_lab <- dat$study_label_plot[i]

    if (grepl("\n", this_lab, fixed = TRUE)) {
      parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
      text(x_study, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
      text(x_study, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
    } else {
      text(x_study, this_row, this_lab, pos = 4, cex = 0.88)
    }
  }

  text(x_n,      rows, dat$N_lab, cex = 0.88)
  text(x_weight, rows, dat$weight_lab, cex = 0.88)
  text(x_right,  rows, dat$effect_ci, pos = 2, cex = 0.88)

  text(x_study, row_overall, "Overall", pos = 4, font = 2, cex = 0.9)
  text(x_weight, row_overall, "100%", cex = 0.88, font = 2)

  if (!is.null(model) && nrow(dat) >= 2) {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", as.numeric(model$b), model$ci.lb, model$ci.ub)
  } else {
    overall_text <- sprintf("%.2f (%.2f to %.2f)", dat$yi[1], dat$ci_lb_plot[1], dat$ci_ub_plot[1])
  }

  text(
    x_right,
    row_overall,
    overall_text,
    pos = 2,
    cex = 0.88,
    font = 2
  )

  mtext("Standardised mean difference for pain", side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at =  1, line = 4.6, cex = 0.9)

  mtext(outcome_title, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

save_sensitivity_forest_journal <- function(
    dat,
    file,
    title_left,
    xlab_text,
    refline_value,
    xlim = c(-6.2, 4.8),
    alim = c(-2, 2),
    at = -2:2
) {

  pdf(file = file, width = 12.5, height = 7.2)

  op <- par(
    mar = c(7.2, 1.5, 2.5, 1.5),
    xpd = NA
  )

  if (is.null(dat) || nrow(dat) == 0) {
    plot.new()
    text(0.5, 0.55, "No sensitivity model available", cex = 1.1)
    mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)
    mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
    par(op)
    dev.off()
    return(invisible(NULL))
  }

  k <- nrow(dat)
  rows <- k:1

  ylim_bottom <- -1.8
  ylim_top <- k + 1.6

  metafor::forest(
    x = dat$TE,
    sei = dat$seTE,
    slab = rep("", k),
    rows = rows,
    ylim = c(ylim_bottom, ylim_top),
    xlim = xlim,
    alim = alim,
    at = at,
    refline = refline_value,
    annotate = FALSE,
    header = FALSE,
    cex = 0.9,
    psize = 1.4,
    efac = 1,
    top = 0,
    xlab = ""
  )

  x_model    <- xlim[1] + 0.15
  x_n        <- -2.85
  x_estimate <- -2.10
  x_se       <- -1.45
  x_right    <- xlim[2] - 0.15

  text(x_model,    k + 1.15, "Model", pos = 4, font = 2, cex = 0.9)
  text(x_n,        k + 1.15, "N", font = 2, cex = 0.9)
  text(x_estimate, k + 1.15, "Estimate", font = 2, cex = 0.9)
  text(x_se,       k + 1.15, "SE", font = 2, cex = 0.9)
  text(x_right,    k + 1.15, "SMD (95% CI)", pos = 2, font = 2, cex = 0.9)

  segments(xlim[1] + 0.05, k + 0.55, xlim[2] - 0.05, k + 0.55, lwd = 1)

  if ("model_label_plot" %in% names(dat)) {
    for (i in seq_len(k)) {
      this_row <- rows[i]
      this_lab <- dat$model_label_plot[i]

      if (grepl("\n", this_lab, fixed = TRUE)) {
        parts <- strsplit(this_lab, "\n", fixed = TRUE)[[1]]
        text(x_model, this_row + 0.14, parts[1], pos = 4, cex = 0.84)
        text(x_model, this_row - 0.14, parts[2], pos = 4, cex = 0.84)
      } else {
        text(x_model, this_row, this_lab, pos = 4, cex = 0.88)
      }
    }
  } else {
    text(x_model, rows, dat$model_label, pos = 4, cex = 0.88)
  }

  text(x_n,        rows, dat$N_lab, cex = 0.88)
  text(x_estimate, rows, dat$estimate_lab, cex = 0.88)
  text(x_se,       rows, dat$se_lab, cex = 0.88)
  text(x_right,    rows, dat$effect_ci, pos = 2, cex = 0.88)

  mtext(xlab_text, side = 1, line = 2.8, cex = 0.95)
  mtext("Favours CWE", side = 1, at = -1, line = 4.6, cex = 0.9)
  mtext("Favours control", side = 1, at = 1, line = 4.6, cex = 0.9)

  mtext(title_left, side = 3, adj = 0, line = 0.5, font = 2, cex = 0.95)

  par(op)
  dev.off()
}

In [431]:
## ============================================================
## SAVE MAIN FOREST PLOTS
## ============================================================

save_forest_all_designs_journal(
  dat = pain_study_display_all,
  model = res_pain_all_plot,
  file = file.path(graph_path, "forest_pain_all_designs_journal_style.pdf"),
  outcome_title = "Pain, all designs"
)

save_forest_controlled_journal(
  dat = pain_study_display_controlled,
  model = res_pain_controlled_plot,
  file = file.path(graph_path, "forest_pain_controlled_journal_style.pdf"),
  outcome_title = "Pain, controlled studies"
)

agg_record_1229031448
                    2

agg_record_1229031448
                    2

In [432]:
## ============================================================
## PREPARE LEAVE ONE OUT DISPLAY DATA
## ============================================================

pain_total_N_all <- sum(pain_N_by_study$N_study, na.rm = TRUE)

pain_total_N_controlled <- pain_N_by_study %>%
  dplyr::filter(design == "controlled") %>%
  dplyr::summarise(total = sum(N_study, na.rm = TRUE)) %>%
  dplyr::pull(total)

pain_loo_plot_all <- pain_loo_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    pain_N_by_study %>% dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = pain_total_N_all - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

pain_loo_plot_controlled <- pain_loo_controlled_results %>%
  dplyr::filter(!is.na(estimate), !is.na(se)) %>%
  dplyr::left_join(
    pain_N_by_study %>%
      dplyr::filter(design == "controlled") %>%
      dplyr::select(study_id, N_study),
    by = c("dropped_study" = "study_id")
  ) %>%
  dplyr::mutate(
    N_remaining = pain_total_N_controlled - N_study,
    model_label = paste0("Drop: ", study_label),
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = ifelse(is.na(N_remaining), "", as.character(as.integer(N_remaining))),
    estimate_lab = ifelse(is.na(TE), "", sprintf("%.2f", TE)),
    se_lab = ifelse(is.na(seTE), "", sprintf("%.2f", seTE)),
    effect_ci = ifelse(
      is.na(TE) | is.na(ci_lb_plot) | is.na(ci_ub_plot),
      "",
      sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
    ),
    model_label_plot = model_label
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_remaining,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [433]:
## ============================================================
## PREPARE TAU SENSITIVITY DISPLAY DATA
## ============================================================

pain_tau_plot <- pain_tau_sensitivity %>%
  dplyr::mutate(
    model_label = paste0("Tau^2 fixed at ", formatC(tau2_study_fixed, format = "f", digits = 2)),
    model_label_plot = model_label,
    TE = estimate,
    seTE = se,
    ci_lb_plot = ci_lb,
    ci_ub_plot = ci_ub,
    N_lab = "",
    estimate_lab = sprintf("%.2f", TE),
    se_lab = sprintf("%.2f", seTE),
    effect_ci = sprintf("%.2f (%.2f to %.2f)", TE, ci_lb_plot, ci_ub_plot)
  ) %>%
  dplyr::select(
    model_label,
    model_label_plot,
    N_lab,
    TE,
    seTE,
    estimate_lab,
    se_lab,
    effect_ci
  )

In [434]:
## ============================================================
## SAVE SENSITIVITY PLOTS
## ============================================================

save_sensitivity_forest_journal(
  dat = pain_loo_plot_all,
  file = file.path(graph_path, "forest_pain_leave_one_out_all_designs.pdf"),
  title_left = "Pain, leave one out, all designs",
  xlab_text = "Pooled SMD after omitting one study",
  refline_value = as.numeric(res_pain_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = pain_loo_plot_controlled,
  file = file.path(graph_path, "forest_pain_leave_one_out_controlled_only.pdf"),
  title_left = "Pain, leave one out, controlled studies",
  xlab_text = "Pooled SMD after omitting one controlled study",
  refline_value = if (!is.null(res_pain_controlled_mv)) as.numeric(res_pain_controlled_mv$b) else 0,
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

save_sensitivity_forest_journal(
  dat = pain_tau_plot,
  file = file.path(graph_path, "forest_pain_tau_sensitivity.pdf"),
  title_left = "Pain, tau sensitivity",
  xlab_text = "Pooled SMD under fixed tau^2 assumptions",
  refline_value = as.numeric(res_pain_main_mv$b),
  xlim = c(-6.2, 4.8),
  alim = c(-2, 2),
  at = -2:2
)

agg_record_1009995413
                    2

agg_record_1009995413
                    2

agg_record_1009995413
                    2

In [435]:
## ============================================================
## EXPORT TABLES
## ============================================================

make_study_effect_table <- function(df) {

  df_export <- df

  if (!"design_type" %in% names(df_export)) {
    if ("design" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design))
    } else if ("design_label" %in% names(df_export)) {
      df_export <- df_export %>%
        dplyr::mutate(design_type = as.character(design_label))
    } else {
      df_export <- df_export %>%
        dplyr::mutate(design_type = NA_character_)
    }
  }

  if (!"N_study" %in% names(df_export)) {
    df_export <- df_export %>%
      dplyr::mutate(N_study = NA_real_)
    }

  df_export %>%
    dplyr::transmute(
      study_id,
      outcome_name,
      study_label,
      design_type,
      N_study,
      yi,
      vi,
      se = sqrt(vi),
      ci_lb = yi - 1.96 * sqrt(vi),
      ci_ub = yi + 1.96 * sqrt(vi)
    ) %>%
    round_df_2()
}

tab_pain_study_display_all <- make_study_effect_table(pain_study_display_all)

tab_pain_study_display_controlled <- make_study_effect_table(pain_study_display_controlled)

tab_pain_effect_sizes_all <- es_pain_all %>%
  dplyr::left_join(study_labels_pain, by = "study_id") %>%
  dplyr::left_join(pain_N_by_study, by = c("study_id", "outcome_name")) %>%
  dplyr::transmute(
    study_id,
    outcome_name,
    study_label,
    design_type,
    N_study,
    yi,
    vi,
    se = sqrt(vi),
    ci_lb = yi - 1.96 * sqrt(vi),
    ci_ub = yi + 1.96 * sqrt(vi)
  ) %>%
  round_df_2()

tab_pain_model_compare <- tibble::tibble(
  model = c("main_all_designs", "controlled_only"),
  k_effects = c(nrow(pain_main_dat), nrow(pain_controlled_dat)),
  n_studies = c(
    dplyr::n_distinct(pain_main_dat$study_id),
    dplyr::n_distinct(pain_controlled_dat$study_id)
  ),
  estimate = c(
    as.numeric(res_pain_main_mv$b),
    if (nrow(pain_controlled_dat) == 1) pain_controlled_dat$yi[1] else as.numeric(res_pain_controlled_mv$b)
  ),
  se = c(
    as.numeric(res_pain_main_mv$se),
    if (nrow(pain_controlled_dat) == 1) sqrt(pain_controlled_dat$vi[1]) else as.numeric(res_pain_controlled_mv$se)
  ),
  ci_lb = c(
    as.numeric(res_pain_main_mv$ci.lb),
    if (nrow(pain_controlled_dat) == 1) pain_controlled_dat$yi[1] - 1.96 * sqrt(pain_controlled_dat$vi[1]) else as.numeric(res_pain_controlled_mv$ci.lb)
  ),
  ci_ub = c(
    as.numeric(res_pain_main_mv$ci.ub),
    if (nrow(pain_controlled_dat) == 1) pain_controlled_dat$yi[1] + 1.96 * sqrt(pain_controlled_dat$vi[1]) else as.numeric(res_pain_controlled_mv$ci.ub)
  ),
  p_value = c(
    as.numeric(res_pain_main_mv$pval),
    if (nrow(pain_controlled_dat) == 1) NA_real_ else as.numeric(res_pain_controlled_mv$pval)
  ),
  tau2_study = c(
    as.numeric(res_pain_main_mv$sigma2),
    if (nrow(pain_controlled_dat) == 1) NA_real_ else as.numeric(res_pain_controlled_mv$sigma2)
  )
) %>%
  round_df_2()

tab_pain_loo_all <- pain_loo_results %>%
  round_df_2()

tab_pain_loo_controlled <- pain_loo_controlled_results %>%
  round_df_2()

tab_pain_tau <- pain_tau_sensitivity %>%
  round_df_2()

tab_pain_N_by_study <- pain_N_by_study %>%
  round_df_2()

tab_pain_N_by_design <- pain_N_by_design %>%
  round_df_2()

readr::write_csv(
  tab_pain_effect_sizes_all,
  file.path(table_path, "pain_effect_sizes_all.csv")
)

readr::write_csv(
  tab_pain_study_display_all,
  file.path(table_path, "pain_study_display_main.csv")
)

readr::write_csv(
  tab_pain_study_display_controlled,
  file.path(table_path, "pain_study_display_controlled_only.csv")
)

readr::write_csv(
  tab_pain_model_compare,
  file.path(table_path, "pain_model_comparison.csv")
)

readr::write_csv(
  tab_pain_loo_all,
  file.path(table_path, "pain_leave_one_out_all.csv")
)

readr::write_csv(
  tab_pain_loo_controlled,
  file.path(table_path, "pain_leave_one_out_controlled_only.csv")
)

readr::write_csv(
  tab_pain_tau,
  file.path(table_path, "pain_tau_sensitivity.csv")
)

readr::write_csv(
  tab_pain_N_by_study,
  file.path(table_path, "pain_sample_size_by_study.csv")
)

readr::write_csv(
  tab_pain_N_by_design,
  file.path(table_path, "pain_sample_size_by_design.csv")
)

In [436]:
## ------------------------------------------------------------
## Quick console check
## ------------------------------------------------------------

cat("\nSaved pain PDFs to:\n", graph_path, "\n", sep = "")
cat("\nSaved pain tables to:\n", table_path, "\n", sep = "")

list.files(graph_path, pattern = "pain.*pdf$", full.names = TRUE)
list.files(table_path, pattern = "pain.*csv$", full.names = TRUE)

Saved pain PDFs to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs

Saved pain tables to:
/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_pain_all_designs_journal_style.pdf"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_pain_controlled_journal_style.pdf"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_pain_leave_one_out_all_designs.pdf"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_pain_leave_one_out_controlled_only.pdf"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/graphs/forest_pain_tau_sensitivity.pdf"

[1] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_effect_sizes_all.csv"
[2] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_leave_one_out_all.csv"
[3] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_leave_one_out_controlled_only.csv"
[4] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_model_comparison.csv"
[5] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_sample_size_by_design.csv"
[6] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_sample_size_by_study.csv"
[7] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_study_display_controlled_only.csv"
[8] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_study_display_main.csv"
[9] "/Users/stevenschepanski/Documents/04_ANALYSIS/CWEMetaAnalysis/tables/pain_tau_sensitivity.csv"